"use client";
import { useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { LogOut, Menu, X, ChevronDown } from "lucide-react";
import { getSidebarNavigation, type NavItem } from "@/core/navigation/navigationRegistry";
import { usePermissions } from "@/core/permissions/usePermissions";
import { createClient } from "@/infrastructure/supabase/client";
import { cn } from "@/shared/utils/cn";
import { useI18n } from "@/core/i18n/I18nProvider";
import { LanguageSwitcher } from "@/core/i18n/LanguageSwitcher";
interface WorkspaceShellProps { children: React.ReactNode; user: { email?: string } | null; }
export function WorkspaceShell({ children, user }: WorkspaceShellProps) {
  const pathname = usePathname(); const router = useRouter(); const { hasPermission } = usePermissions(); const { locale, messages, workspace } = useI18n(); const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false); const [openGroups, setOpenGroups] = useState<Record<string, boolean>>({}); const supabase = createClient(); const isArabic = locale === "ar";
  const canSee = (item: NavItem) => item.requiredPermission === null || hasPermission(item.requiredPermission); const filterChildren = (item: NavItem): NavItem => ({ ...item, children: item.children?.filter(canSee).map(filterChildren) }); const filteredNav = getSidebarNavigation().map(filterChildren).filter((item) => canSee(item) || (item.children && item.children.length > 0)); const getLabel = (item: NavItem) => item.label ? item.label[locale] : item.labelKey ? messages.nav[item.labelKey] : item.href; const isPathActive = (item: NavItem): boolean => pathname === item.href.split("?")[0] || (item.children?.some(isPathActive) ?? false); const groupContainsPath = (item: NavItem): boolean => item.children?.some((child) => pathname === child.href.split("?")[0] || pathname.startsWith(`${child.href.split("?")[0]}/`) || groupContainsPath(child)) ?? false;
  const handleSignOut = async () => { await supabase.auth.signOut(); router.push("/login"); router.refresh(); };
  const renderItem = (item: NavItem, nested = false): React.ReactNode => { const children = item.children ?? []; const expandable = children.length > 0; const active = isPathActive(item); const open = openGroups[item.href] ?? groupContainsPath(item); const Icon = item.icon; const toggle = () => setOpenGroups((v) => ({ ...v, [item.href]: !open })); const closeOnMobile = () => setMobileSidebarOpen(false); return <div key={`${item.href}-${nested ? "nested" : "root"}`}><div className={cn("flex items-center rounded-lg text-sm font-medium transition-colors", nested && (isArabic ? "mr-4" : "ml-4"), active ? "bg-blue-50 text-blue-700" : "text-gray-700 hover:bg-gray-100 hover:text-gray-900")}>{expandable ? <button type="button" onClick={toggle} className="flex min-w-0 flex-1 items-center gap-3 px-3 py-2 text-start" aria-expanded={open}><Icon className="h-4 w-4 shrink-0" /><span className="truncate">{getLabel(item)}</span></button> : <Link href={item.href} prefetch onClick={closeOnMobile} className="flex min-w-0 flex-1 items-center gap-3 px-3 py-2"><Icon className="h-4 w-4 shrink-0" /><span className="truncate">{getLabel(item)}</span></Link>}{expandable && <button type="button" onClick={toggle} className="p-2" aria-label={open ? workspace.collapse : workspace.expand}><ChevronDown className={cn("h-4 w-4 shrink-0 transition-transform", open && "rotate-180")} /></button>}</div>{expandable && open && <div className="mt-1 space-y-0.5 border-l border-gray-200 pl-1 rtl:border-l-0 rtl:border-r rtl:pr-1">{children.map((child) => renderItem(child, true))}</div>}</div>; };
  return <div className="flex min-h-screen w-full bg-gray-50">{mobileSidebarOpen && <div className="fixed inset-0 z-40 bg-black/50 lg:hidden" onClick={() => setMobileSidebarOpen(false)} /> }<aside className={cn("fixed inset-y-0 z-50 w-72 bg-white shadow-lg transition-transform duration-200 ease-in-out lg:translate-x-0", isArabic ? "right-0" : "left-0", mobileSidebarOpen ? "translate-x-0" : isArabic ? "translate-x-full" : "-translate-x-full")}><div className="flex h-full flex-col"><div className="flex items-center justify-between border-b px-6 py-4"><Link href="/" className="text-xl font-bold text-blue-600" onClick={() => setMobileSidebarOpen(false)}>ClinicSaaS™</Link><button className="rounded p-2 hover:bg-gray-100" onClick={() => setMobileSidebarOpen(false)} aria-label={workspace.closeSidebar}><X className="h-5 w-5" /></button></div><nav className="flex-1 space-y-1 overflow-y-auto px-3 py-4">{filteredNav.map((item) => renderItem(item))}</nav><div className="border-t px-4 py-3"><LanguageSwitcher /><button onClick={handleSignOut} className="mt-3 flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-gray-700 hover:bg-gray-100"><LogOut className="h-4 w-4" />{workspace.signOut}</button></div></div></aside><main className="min-w-0 flex-1 lg:ml-72 rtl:lg:ml-0 rtl:lg:mr-72"><div className="sticky top-0 z-30 flex h-14 items-center border-b bg-white/95 px-4 backdrop-blur lg:hidden"><button onClick={() => setMobileSidebarOpen(true)} className="rounded p-2 hover:bg-gray-100" aria-label={workspace.openSidebar}><Menu className="h-5 w-5" /></button></div><div className="p-4 md:p-6">{children}</div></main></div>;
}
