/** Agenda availability engine: Workforce owns work reality; Agenda owns booking truth. */
import { createClient } from "@/infrastructure/supabase/server";
import type { AvailabilityCheckInput, AvailabilityResult, WorkingHours } from "./agenda.types";
import type { SupabaseClient } from "@supabase/supabase-js";
type AvailabilityClient = SupabaseClient<any, any, any>;
export const DefaultWorkingHours:WorkingHours[]=[];
async function resolveWorkforceEmployee(supabase:AvailabilityClient,tenantId:string,doctorId:string){const{data}=await supabase.from("workforce_employees").select("id,status").eq("tenant_id",tenantId).eq("user_id",doctorId).eq("status","active").maybeSingle();return data?.id??null;}
export async function loadProviderAvailability(supabase:AvailabilityClient,tenantId:string,doctorId:string):Promise<WorkingHours[]>{const employeeId=await resolveWorkforceEmployee(supabase,tenantId,doctorId);if(employeeId){const today=new Date().toISOString().slice(0,10);const{data,error}=await supabase.from("workforce_staff_schedules").select("day_of_week,starts_at,ends_at,status,effective_from,effective_to").eq("tenant_id",tenantId).eq("employee_id",employeeId).eq("status","active").or(`effective_from.is.null,effective_from.lte.${today}`).or(`effective_to.is.null,effective_to.gte.${today}`).order("day_of_week");if(!error&&data?.length)return data.map(row=>({day:row.day_of_week as 0|1|2|3|4|5|6,start:row.starts_at,end:row.ends_at,isWorking:true}));}const{data,error}=await supabase.from("clinic_provider_availability").select("day_of_week,start_time,end_time,is_active").eq("tenant_id",tenantId).eq("doctor_id",doctorId).eq("is_active",true).or(`valid_from.is.null,valid_from.lte.${new Date().toISOString()}`).or(`valid_until.is.null,valid_until.gte.${new Date().toISOString()}`).order("day_of_week");if(error||!data?.length)return [];return data.map(row=>({day:row.day_of_week as 0|1|2|3|4|5|6,start:row.start_time,end:row.end_time,isWorking:row.is_active}));}
export async function loadBlockedPeriods(supabase:AvailabilityClient,tenantId:string,doctorId?:string,roomId?:string|null):Promise<Array<{start:string;end:string;title:string}>>{let query=supabase.from("master_agenda_events").select("scheduled_start,scheduled_end,buffer_end,booking_notes,event_type,doctor_id,room_id").eq("tenant_id",tenantId).in("event_type",["block","break"]).not("status","in","(cancelled,no_show,completed)");if(doctorId)query=query.eq("doctor_id",doctorId);if(roomId)query=query.eq("room_id",roomId);const{data,error}=await query;if(error)return[];return(data??[]).map(row=>({start:row.scheduled_start,end:row.buffer_end||row.scheduled_end,title:row.booking_notes||row.event_type}));}
async function loadWorkforceLeaveBlocks(supabase:AvailabilityClient,tenantId:string,doctorId:string,start:string,end:string):Promise<Array<{start:string;end:string;title:string}>>{const employeeId=await resolveWorkforceEmployee(supabase,tenantId,doctorId);if(!employeeId)return[];const{data,error}=await supabase.rpc("get_workforce_unavailability",{p_tenant_id:tenantId,p_employee_id:employeeId,p_start:start,p_end:end});if(!error&&data?.length)return data.map((row:any)=>({start:row.starts_at,end:row.ends_at,title:row.reason||`Workforce ${String(row.absence_type||"unavailability").replaceAll("_"," ")}`}));const{data:legacy,error:legacyError}=await supabase.from("workforce_leave_requests").select("starts_on,ends_on,status,reason").eq("tenant_id",tenantId).eq("employee_id",employeeId).eq("status","approved");if(legacyError)return[];return(legacy??[]).map(row=>{const finish=new Date(`${row.ends_on}T00:00:00`);finish.setDate(finish.getDate()+1);return{start:`${row.starts_on}T00:00:00`,end:finish.toISOString(),title:row.reason||"Workforce leave"};});}
async function providerEligibility(supabase:AvailabilityClient,tenantId:string,doctorId:string,procedureId:string|null){if(!procedureId)return true;const{count,error:capabilityError}=await supabase.from("workforce_procedure_capabilities").select("id",{count:"exact",head:true}).eq("tenant_id",tenantId).eq("procedure_id",procedureId).is("deleted_at",null);if(capabilityError)return false;if((count??0)===0)return true;const employeeId=await resolveWorkforceEmployee(supabase,tenantId,doctorId);if(!employeeId)return false;const{data:capability,error}=await supabase.from("workforce_procedure_capabilities").select("id").eq("tenant_id",tenantId).eq("procedure_id",procedureId).eq("workforce_employee_id",employeeId).is("deleted_at",null).maybeSingle();if(error)return false;return !!capability;}
export async function checkAvailability(input:AvailabilityCheckInput,providedClient?:AvailabilityClient):Promise<AvailabilityResult>{const supabase=providedClient??await createClient();const{tenantId,doctorId,roomId,procedureId,scheduledStart,scheduledEnd,bufferEnd}=input;const startDate=new Date(scheduledStart);const endDate=new Date(bufferEnd||scheduledEnd);const workingHours=await loadProviderAvailability(supabase,tenantId,doctorId);const withinWorkingHours=isWithinWorkingHours(startDate,endDate,workingHours);const blockedPeriods=[...(await loadBlockedPeriods(supabase,tenantId,doctorId,roomId)),...(await loadWorkforceLeaveBlocks(supabase,tenantId,doctorId,scheduledStart,bufferEnd||scheduledEnd))];const notBlocked=!isBlocked(startDate,endDate,blockedPeriods);const doctorAvailable=await isDoctorAvailable(supabase,tenantId,doctorId,scheduledStart,bufferEnd||scheduledEnd);const roomAvailable=roomId?await isRoomAvailable(supabase,tenantId,roomId,scheduledStart,bufferEnd||scheduledEnd):true;const providerEligible=await providerEligibility(supabase,tenantId,doctorId,procedureId??null);const isAvailable=withinWorkingHours&&notBlocked&&doctorAvailable&&roomAvailable&&providerEligible;let reason:string|null=null;if(!providerEligible)reason="Provider is not qualified for the selected procedure";else if(!withinWorkingHours)reason="Requested time is outside provider working hours";else if(!notBlocked)reason="Requested period is blocked or the provider is unavailable";else if(!doctorAvailable)reason="Provider is already booked";else if(!roomAvailable)reason="Room is already booked";return{isAvailable,reason,details:{doctorAvailable,roomAvailable,providerEligible,withinWorkingHours,notBlocked}};}
function isWithinWorkingHours(start:Date,end:Date,workingHours:WorkingHours[]):boolean{const day=start.getDay() as 0|1|2|3|4|5|6;const config=workingHours.find(wh=>wh.day===day);if(!config||!config.isWorking)return false;const[startHour,startMinute]=config.start.split(":").map(Number);const[endHour,endMinute]=config.end.split(":").map(Number);const workStart=new Date(start);workStart.setHours(startHour,startMinute,0,0);const workEnd=new Date(start);workEnd.setHours(endHour,endMinute,0,0);return start>=workStart&&end<=workEnd;}
function isBlocked(start:Date,end:Date,periods:Array<{start:string;end:string}>):boolean{for(const period of periods){const blockStart=new Date(period.start);const blockEnd=new Date(period.end);if(start<blockEnd&&end>blockStart)return true;}return false;}
async function isDoctorAvailable(supabase:AvailabilityClient,tenantId:string,doctorId:string,start:string,end:string){const{data,error}=await supabase.from("master_agenda_events").select("id").eq("tenant_id",tenantId).eq("doctor_id",doctorId).not("status","in","(cancelled,no_show,completed)").or(`and(scheduled_start.lte.${end},buffer_end.gte.${start}),and(scheduled_start.gte.${start},scheduled_start.lt.${end})`).limit(1);if(error)return false;return(data??[]).length===0;}
async function isRoomAvailable(supabase:AvailabilityClient,tenantId:string,roomId:string,start:string,end:string){const{data,error}=await supabase.from("master_agenda_events").select("id").eq("tenant_id",tenantId).eq("room_id",roomId).not("status","in","(cancelled,no_show,completed)").or(`and(scheduled_start.lte.${end},buffer_end.gte.${start}),and(scheduled_start.gte.${start},scheduled_start.lt.${end})`).limit(1);if(error)return false;return(data??[]).length===0;}
export async function checkAvailabilityBatch(inputs:AvailabilityCheckInput[],providedClient?:AvailabilityClient){const results:AvailabilityResult[]=[];for(const input of inputs)results.push(await checkAvailability(input,providedClient));return results;}
export function calculateBufferEnd(scheduledEnd:string,bufferMinutes:number){const endDate=new Date(scheduledEnd);endDate.setMinutes(endDate.getMinutes()+bufferMinutes);return endDate.toISOString();}
export function getEffectiveEnd(scheduledEnd:string,bufferEnd?:string|null){return bufferEnd||scheduledEnd;}
