import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import { createClient } from "@/infrastructure/supabase/server";
import { resolveTenantId } from "@/core/auth/resolveTenantId";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import { createEmployee, createWorkforcePosition, recordAttendance, createLeaveRequest, createPayrollPeriod, createCommissionRule } from "@/domain/workforce/workforce.actions";

export default async function WorkforcePage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const tenantId = await resolveTenantId(user.id);
  if (!tenantId) redirect("/login");
  const permissions = await getEffectivePermissions(user.id, tenantId);
  if (!permissions.includes("workforce:read" as never) && !permissions.includes("workforce:manage" as never)) redirect("/");
  const locale = (await cookies()).get("core-system-locale")?.value === "ar" ? "ar" : "en";
  const ar = locale === "ar";
  const [{ data: employees }, { data: positions }, { data: leaveTypes }, { data: attendance }, { data: leaveRequests }, { data: payroll }, { data: commissions }] = await Promise.all([
    supabase.from("workforce_employees").select("id,employee_number,first_name,last_name,status,hire_date,position:workforce_positions(name,name_ar)").eq("tenant_id", tenantId).order("created_at", { ascending: false }),
    supabase.from("workforce_positions").select("id,name,name_ar,department,employment_type,status").eq("tenant_id", tenantId).order("name"),
    supabase.from("workforce_leave_types").select("id,name,name_ar").eq("tenant_id", tenantId).eq("status", "active").order("name"),
    supabase.from("workforce_attendance").select("id,attendance_date,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).order("attendance_date", { ascending: false }).limit(10),
    supabase.from("workforce_leave_requests").select("id,starts_on,ends_on,days,status,employee:workforce_employees(first_name,last_name),leave_type:workforce_leave_types(name,name_ar)").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(10),
    supabase.from("workforce_payroll_periods").select("id,period_start,period_end,status,currency").eq("tenant_id", tenantId).order("period_start", { ascending: false }).limit(8),
    supabase.from("workforce_commission_rules").select("id,name,basis,rate,fixed_amount_subunits,status").eq("tenant_id", tenantId).order("name"),
  ]);

  async function addEmployee(formData: FormData): Promise<void> { "use server"; await createEmployee({ first_name:String(formData.get("first_name")||""), last_name:String(formData.get("last_name")||""), employee_number:String(formData.get("employee_number")||"")||undefined, position_id:String(formData.get("position_id")||"")||null, email:String(formData.get("email")||"")||undefined, phone:String(formData.get("phone")||"")||undefined, hire_date:String(formData.get("hire_date")||"")||null }); }
  async function addPosition(formData: FormData): Promise<void> { "use server"; await createWorkforcePosition({ name:String(formData.get("name")||""), name_ar:String(formData.get("name_ar")||"")||undefined, department:String(formData.get("department")||"")||undefined }); }
  async function addAttendance(formData: FormData): Promise<void> { "use server"; await recordAttendance({ employee_id:String(formData.get("employee_id")||""), attendance_date:String(formData.get("attendance_date")||""), status:String(formData.get("status")||"present") }); }
  async function addLeave(formData: FormData): Promise<void> { "use server"; await createLeaveRequest({ employee_id:String(formData.get("employee_id")||""), leave_type_id:String(formData.get("leave_type_id")||""), starts_on:String(formData.get("starts_on")||""), ends_on:String(formData.get("ends_on")||""), days:Number(formData.get("days")||0), reason:String(formData.get("reason")||"")||null }); }
  async function addPayroll(formData: FormData): Promise<void> { "use server"; await createPayrollPeriod({ period_start:String(formData.get("period_start")||""), period_end:String(formData.get("period_end")||""), currency:String(formData.get("currency")||"JOD") }); }
  async function addCommission(formData: FormData): Promise<void> { "use server"; await createCommissionRule({ name:String(formData.get("name")||""), basis:String(formData.get("basis")||"collected_revenue"), rate:Number(formData.get("rate")||0) }); }

  const employeeRows = employees ?? [];
  return <div className="space-y-8" dir={ar ? "rtl" : "ltr"}>
    <div><h1 className="text-2xl font-bold">{ar ? "القوى العاملة والعمليات" : "Workforce & Operations"}</h1><p className="mt-1 text-sm text-muted-foreground">{ar ? "إدارة الموظفين والتوظيف والحضور والإجازات والرواتب والقدرة التشغيلية دون إنشاء نظام مواعيد بديل." : "Manage staff, employment, attendance, leave, payroll and capacity without creating a second appointment engine."}</p></div>
    <section className="grid gap-4 md:grid-cols-4">
      {[[(ar?"الموظفون":"Employees"), employeeRows.length],[(ar?"المناصب":"Positions"),(positions??[]).length],[(ar?"طلبات الإجازة":"Leave Requests"),(leaveRequests??[]).length],[(ar?"فترات الرواتب":"Payroll Periods"),(payroll??[]).length]].map(([label,value])=><div key={String(label)} className="rounded-lg border bg-card p-4"><div className="text-sm text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>)}
    </section>
    <div className="grid gap-6 xl:grid-cols-2">
      <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"الموظفون":"Employees"}</h2><form action={addEmployee} className="grid gap-2 sm:grid-cols-2"><input name="first_name" required placeholder={ar?"الاسم":"First name"} className="rounded border p-2"/><input name="last_name" required placeholder={ar?"اسم العائلة":"Last name"} className="rounded border p-2"/><input name="employee_number" placeholder={ar?"الرقم الوظيفي":"Employee number"} className="rounded border p-2"/><select name="position_id" className="rounded border p-2"><option value="">{ar?"المنصب":"Position"}</option>{(positions??[]).map((p:any)=><option key={p.id} value={p.id}>{ar?(p.name_ar||p.name):p.name}</option>)}</select><input name="email" type="email" placeholder="Email" className="rounded border p-2"/><input name="phone" placeholder={ar?"الهاتف":"Phone"} className="rounded border p-2"/><input name="hire_date" type="date" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"إضافة موظف":"Add employee"}</button></form><div className="mt-5 divide-y">{employeeRows.slice(0,10).map((e:any)=><div key={e.id} className="flex items-center justify-between py-2"><span>{e.first_name} {e.last_name}</span><span className="text-sm text-muted-foreground">{e.position?.name_ar||e.position?.name||"—"} · {e.status}</span></div>)}</div></section>
      <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"المناصب":"Positions"}</h2><form action={addPosition} className="grid gap-2 sm:grid-cols-2"><input name="name" required placeholder={ar?"اسم المنصب":"Position name"} className="rounded border p-2"/><input name="name_ar" placeholder={ar?"الاسم العربي":"Arabic name"} className="rounded border p-2"/><input name="department" placeholder={ar?"القسم":"Department"} className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground">{ar?"إضافة":"Add"}</button></form><div className="mt-5 divide-y">{(positions??[]).map((p:any)=><div key={p.id} className="flex justify-between py-2"><span>{ar?(p.name_ar||p.name):p.name}</span><span className="text-sm text-muted-foreground">{p.department||"—"}</span></div>)}</div></section>
      <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"الحضور":"Attendance"}</h2><form action={addAttendance} className="grid gap-2 sm:grid-cols-2"><select name="employee_id" required className="rounded border p-2">{employeeRows.map((e:any)=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select><input name="attendance_date" type="date" required className="rounded border p-2"/><select name="status" className="rounded border p-2"><option value="present">{ar?"حاضر":"Present"}</option><option value="late">{ar?"متأخر":"Late"}</option><option value="absent">{ar?"غائب":"Absent"}</option><option value="partial">{ar?"جزئي":"Partial"}</option><option value="leave">{ar?"إجازة":"Leave"}</option></select><button className="rounded bg-primary px-4 py-2 text-primary-foreground">{ar?"تسجيل":"Record"}</button></form><div className="mt-5 divide-y">{(attendance??[]).map((a:any)=><div key={a.id} className="flex justify-between py-2"><span>{a.employee?.first_name} {a.employee?.last_name}</span><span className="text-sm text-muted-foreground">{a.attendance_date} · {a.status}</span></div>)}</div></section>
      <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"الإجازات":"Leave"}</h2><form action={addLeave} className="grid gap-2 sm:grid-cols-2"><select name="employee_id" required className="rounded border p-2">{employeeRows.map((e:any)=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select><select name="leave_type_id" required className="rounded border p-2">{(leaveTypes??[]).map((l:any)=><option key={l.id} value={l.id}>{ar?(l.name_ar||l.name):l.name}</option>)}</select><input name="starts_on" type="date" required className="rounded border p-2"/><input name="ends_on" type="date" required className="rounded border p-2"/><input name="days" type="number" step="0.5" min="0.5" required placeholder={ar?"الأيام":"Days"} className="rounded border p-2"/><input name="reason" placeholder={ar?"السبب":"Reason"} className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"طلب إجازة":"Request leave"}</button></form><div className="mt-5 divide-y">{(leaveRequests??[]).map((r:any)=><div key={r.id} className="flex justify-between py-2"><span>{r.employee?.first_name} {r.employee?.last_name}</span><span className="text-sm text-muted-foreground">{r.starts_on} → {r.ends_on} · {r.status}</span></div>)}</div></section>
      <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"الرواتب":"Payroll"}</h2><form action={addPayroll} className="grid gap-2 sm:grid-cols-3"><input name="period_start" type="date" required className="rounded border p-2"/><input name="period_end" type="date" required className="rounded border p-2"/><input name="currency" defaultValue="JOD" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-3">{ar?"فتح فترة رواتب":"Open payroll period"}</button></form><div className="mt-5 divide-y">{(payroll??[]).map((p:any)=><div key={p.id} className="flex justify-between py-2"><span>{p.period_start} → {p.period_end}</span><span className="text-sm text-muted-foreground">{p.status}</span></div>)}</div></section>
      <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"العمولات والحوافز":"Commissions & Incentives"}</h2><form action={addCommission} className="grid gap-2 sm:grid-cols-2"><input name="name" required placeholder={ar?"اسم القاعدة":"Rule name"} className="rounded border p-2"/><select name="basis" className="rounded border p-2"><option value="collected_revenue">{ar?"الإيراد المحصل":"Collected revenue"}</option><option value="invoice_value">{ar?"قيمة الفاتورة":"Invoice value"}</option><option value="procedure_count">{ar?"عدد الإجراءات":"Procedure count"}</option><option value="fixed_bonus">{ar?"مكافأة ثابتة":"Fixed bonus"}</option></select><input name="rate" type="number" step="0.0001" min="0" placeholder={ar?"النسبة":"Rate"} className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground">{ar?"إضافة قاعدة":"Add rule"}</button></form><div className="mt-5 divide-y">{(commissions??[]).map((c:any)=><div key={c.id} className="flex justify-between py-2"><span>{c.name}</span><span className="text-sm text-muted-foreground">{c.basis} · {c.rate}</span></div>)}</div></section>
    </div>
  </div>;
}
