import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import { createClient } from "@/infrastructure/supabase/server";
import { resolveTenantId } from "@/core/auth/resolveTenantId";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import { createEmployee, createWorkforcePosition, recordAttendance, createLeaveRequest, createPayrollPeriod, createCommissionRule, createEmploymentRecord, createStaffSchedule, createBenefit, createPayrollEntry, createCommissionEntry, createStaffingNeed, createCandidate } from "@/domain/workforce/workforce.actions";

export default async function WorkforcePage() {
  const supabase = await createClient(); const { data:{ user } } = await supabase.auth.getUser(); if(!user)redirect("/login"); const tenantId=await resolveTenantId(user.id); if(!tenantId)redirect("/login"); const permissions=await getEffectivePermissions(user.id,tenantId); if(!permissions.includes("workforce:read" as never)&&!permissions.includes("workforce:manage" as never))redirect("/"); const locale=(await cookies()).get("core-system-locale")?.value==="ar"?"ar":"en"; const ar=locale==="ar";
  const [{data:employees},{data:positions},{data:leaveTypes},{data:attendance},{data:leaveRequests},{data:payroll},{data:commissions},{data:employment},{data:schedules},{data:benefits},{data:payrollEntries},{data:commissionEntries},{data:staffingNeeds},{data:candidates}] = await Promise.all([
    supabase.from("workforce_employees").select("id,employee_number,first_name,last_name,status,hire_date,position:workforce_positions(name,name_ar)").eq("tenant_id",tenantId).order("created_at",{ascending:false}),
    supabase.from("workforce_positions").select("id,name,name_ar,department,employment_type,status").eq("tenant_id",tenantId).order("name"),
    supabase.from("workforce_leave_types").select("id,name,name_ar").eq("tenant_id",tenantId).eq("status","active").order("name"),
    supabase.from("workforce_attendance").select("id,attendance_date,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("attendance_date",{ascending:false}).limit(10),
    supabase.from("workforce_leave_requests").select("id,starts_on,ends_on,days,status,employee:workforce_employees(first_name,last_name),leave_type:workforce_leave_types(name,name_ar)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(10),
    supabase.from("workforce_payroll_periods").select("id,period_start,period_end,status,currency").eq("tenant_id",tenantId).order("period_start",{ascending:false}).limit(8),
    supabase.from("workforce_commission_rules").select("id,name,basis,rate,fixed_amount_subunits,status").eq("tenant_id",tenantId).order("name"),
    supabase.from("workforce_employment_records").select("id,employee_id,effective_from,effective_to,employment_type,base_salary_subunits,currency,working_hours_per_week,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("effective_from",{ascending:false}).limit(20),
    supabase.from("workforce_staff_schedules").select("id,employee_id,day_of_week,starts_at,ends_at,capacity_units,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("day_of_week").limit(30),
    supabase.from("workforce_benefits").select("id,employee_id,benefit_name,value_subunits,currency,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(20),
    supabase.from("workforce_payroll_entries").select("id,payroll_period_id,employee_id,base_salary_subunits,allowances_subunits,overtime_subunits,bonuses_subunits,commissions_subunits,deductions_subunits,net_subunits,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(20),
    supabase.from("workforce_commission_entries").select("id,employee_id,commission_rule_id,source_type,basis_amount_subunits,eligible_amount_subunits,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(20),
    supabase.from("workforce_staffing_needs").select("id,title,needed_from,needed_to,quantity,status,position:workforce_positions(name,name_ar)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(20),
    supabase.from("workforce_candidates").select("id,first_name,last_name,email,phone,stage,staffing_need_id").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(20),
  ]);
  const employeeRows=employees??[]; const positionRows=positions??[]; const payrollRows=payroll??[]; const commissionRows=commissions??[];
  async function addEmployee(fd:FormData){"use server";await createEmployee({first_name:String(fd.get("first_name")||""),last_name:String(fd.get("last_name")||""),employee_number:String(fd.get("employee_number")||"")||undefined,position_id:String(fd.get("position_id")||"")||null,email:String(fd.get("email")||"")||undefined,phone:String(fd.get("phone")||"")||undefined,hire_date:String(fd.get("hire_date")||"")||null});}
  async function addPosition(fd:FormData){"use server";await createWorkforcePosition({name:String(fd.get("name")||""),name_ar:String(fd.get("name_ar")||"")||undefined,department:String(fd.get("department")||"")||undefined});}
  async function addAttendance(fd:FormData){"use server";await recordAttendance({employee_id:String(fd.get("employee_id")),attendance_date:String(fd.get("attendance_date")),status:String(fd.get("status")),check_in:String(fd.get("check_in")||"")||null,check_out:String(fd.get("check_out")||"")||null,overtime_minutes:Number(fd.get("overtime_minutes")||0)});}
  async function addLeave(fd:FormData){"use server";await createLeaveRequest({employee_id:String(fd.get("employee_id")),leave_type_id:String(fd.get("leave_type_id")),starts_on:String(fd.get("starts_on")),ends_on:String(fd.get("ends_on")),days:Number(fd.get("days")||0),reason:String(fd.get("reason")||"")||null});}
  async function addPayroll(fd:FormData){"use server";await createPayrollPeriod({period_start:String(fd.get("period_start")),period_end:String(fd.get("period_end")),currency:String(fd.get("currency")||"JOD")});}
  async function addCommission(fd:FormData){"use server";await createCommissionRule({name:String(fd.get("name")||""),basis:String(fd.get("basis")||"collected_revenue"),rate:Number(fd.get("rate")||0)});}
  async function addEmployment(fd:FormData){"use server";await createEmploymentRecord({employee_id:String(fd.get("employee_id")),position_id:String(fd.get("position_id")||"")||null,effective_from:String(fd.get("effective_from")),employment_type:String(fd.get("employment_type")||"full_time"),base_salary_subunits:Math.round(Number(fd.get("base_salary")||0)*100),currency:String(fd.get("currency")||"JOD"),working_hours_per_week:Number(fd.get("hours")||40),notes:String(fd.get("notes")||"")||null});}
  async function addSchedule(fd:FormData){"use server";await createStaffSchedule({employee_id:String(fd.get("employee_id")),day_of_week:Number(fd.get("day_of_week")),starts_at:String(fd.get("starts_at")),ends_at:String(fd.get("ends_at")),capacity_units:Number(fd.get("capacity")||1)});}
  async function addBenefit(fd:FormData){"use server";await createBenefit({employee_id:String(fd.get("employee_id")),benefit_name:String(fd.get("benefit_name")),value_subunits:Math.round(Number(fd.get("value")||0)*100),currency:String(fd.get("currency")||"JOD")});}
  async function addPayrollEntry(fd:FormData){"use server";await createPayrollEntry({payroll_period_id:String(fd.get("payroll_period_id")),employee_id:String(fd.get("employee_id")),base_salary_subunits:Math.round(Number(fd.get("base_salary")||0)*100),allowances_subunits:Math.round(Number(fd.get("allowances")||0)*100),overtime_subunits:Math.round(Number(fd.get("overtime")||0)*100),bonuses_subunits:Math.round(Number(fd.get("bonuses")||0)*100),commissions_subunits:Math.round(Number(fd.get("commissions")||0)*100),deductions_subunits:Math.round(Number(fd.get("deductions")||0)*100)});}
  async function addCommissionEntry(fd:FormData){"use server";await createCommissionEntry({employee_id:String(fd.get("employee_id")),commission_rule_id:String(fd.get("commission_rule_id")),source_type:String(fd.get("source_type")||"manual"),basis_amount_subunits:Math.round(Number(fd.get("basis")||0)*100),eligible_amount_subunits:Math.round(Number(fd.get("eligible")||0)*100)});}
  async function addNeed(fd:FormData){"use server";await createStaffingNeed({position_id:String(fd.get("position_id")||"")||null,title:String(fd.get("title")||""),needed_from:String(fd.get("needed_from")||"")||null,needed_to:String(fd.get("needed_to")||"")||null,quantity:Number(fd.get("quantity")||1),notes:String(fd.get("notes")||"")||null});}
  async function addCandidate(fd:FormData){"use server";await createCandidate({staffing_need_id:String(fd.get("staffing_need_id")||"")||null,first_name:String(fd.get("first_name")),last_name:String(fd.get("last_name")),phone:String(fd.get("phone")||"")||undefined,email:String(fd.get("email")||"")||undefined,stage:String(fd.get("stage")||"candidate")});}
  const empSelect=(name="employee_id")=><select name={name} required className="rounded border p-2">{employeeRows.map((e:any)=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select>;
  return <div className="space-y-8" dir={ar?"rtl":"ltr"}>
    <header><h1 className="text-2xl font-bold">{ar?"القوى العاملة والعمليات":"Workforce & Operations"}</h1><p className="mt-1 text-sm text-muted-foreground">{ar?"دورة حياة الموظف، الحساب الوظيفي، الجداول والقدرة، الحضور والإجازات، الرواتب والعمولات والتوظيف.":"Employee lifecycle, staffing accounts, schedules/capacity, attendance/leave, payroll/commissions and recruitment."}</p></header>
    <section className="grid gap-4 md:grid-cols-4">{[[ar?"الموظفون":"Employees",employeeRows.length],[ar?"الجداول":"Schedules",(schedules??[]).length],[ar?"طلبات الإجازة":"Leave Requests",(leaveRequests??[]).length],[ar?"فترات الرواتب":"Payroll Periods",payrollRows.length]].map(([label,value])=><div key={String(label)} className="rounded-lg border bg-card p-4"><div className="text-sm text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>)}</section>
    <div className="grid gap-6 xl:grid-cols-2">
      <Section title={ar?"الموظفون":"Employees"}><form action={addEmployee} className="grid gap-2 sm:grid-cols-2"><input name="first_name" required placeholder={ar?"الاسم":"First name"} className="rounded border p-2"/><input name="last_name" required placeholder={ar?"اسم العائلة":"Last name"} className="rounded border p-2"/><input name="employee_number" placeholder={ar?"الرقم الوظيفي":"Employee number"} className="rounded border p-2"/><select name="position_id" className="rounded border p-2"><option value="">{ar?"المنصب":"Position"}</option>{positionRows.map((p:any)=><option key={p.id} value={p.id}>{ar?(p.name_ar||p.name):p.name}</option>)}</select><input name="email" type="email" placeholder={ar?"البريد الإلكتروني":"Email"} className="rounded border p-2"/><input name="phone" placeholder={ar?"الهاتف":"Phone"} className="rounded border p-2"/><input name="hire_date" type="date" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"إضافة موظف":"Add employee"}</button></form><List rows={employeeRows.slice(0,10)} render={(e:any)=><><span>{e.first_name} {e.last_name}</span><span className="text-sm text-muted-foreground">{e.position?.name_ar||e.position?.name||"—"} · {e.status}</span></>}/></Section>
      <Section title={ar?"المناصب":"Positions"}><form action={addPosition} className="grid gap-2 sm:grid-cols-2"><input name="name" required placeholder={ar?"اسم المنصب":"Position name"} className="rounded border p-2"/><input name="name_ar" placeholder={ar?"الاسم العربي":"Arabic name"} className="rounded border p-2"/><input name="department" placeholder={ar?"القسم":"Department"} className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground">{ar?"إضافة":"Add"}</button></form><List rows={positionRows} render={(p:any)=><><span>{ar?(p.name_ar||p.name):p.name}</span><span className="text-sm text-muted-foreground">{p.department||"—"}</span></>}/></Section>
      <Section title={ar?"سجل العمل والراتب الأساسي":"Employment & Compensation"}><form action={addEmployment} className="grid gap-2 sm:grid-cols-2">{empSelect()}<select name="position_id" className="rounded border p-2">{positionRows.map((p:any)=><option key={p.id} value={p.id}>{ar?(p.name_ar||p.name):p.name}</option>)}</select><input name="effective_from" type="date" required className="rounded border p-2"/><select name="employment_type" className="rounded border p-2"><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option></select><input name="base_salary" type="number" step="0.01" min="0" placeholder="Base salary" className="rounded border p-2"/><input name="hours" type="number" min="1" value="40" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"حفظ سجل التوظيف":"Save employment record"}</button></form><List rows={(employment??[]).slice(0,10)} render={(e:any)=><><span>{e.employee?.first_name} {e.employee?.last_name}</span><span className="text-sm text-muted-foreground">{e.employment_type} · {e.base_salary_subunits/100} {e.currency}</span></>}/></Section>
      <Section title={ar?"جداول العمل والقدرة":"Staff Schedules & Capacity"}><form action={addSchedule} className="grid gap-2 sm:grid-cols-2">{empSelect()}<select name="day_of_week" className="rounded border p-2">{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((d,i)=><option key={d} value={i}>{d}</option>)}</select><input name="starts_at" type="time" defaultValue="09:00" className="rounded border p-2"/><input name="ends_at" type="time" defaultValue="17:00" className="rounded border p-2"/><input name="capacity" type="number" min="0.1" step="0.1" defaultValue="1" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"إضافة جدول":"Add schedule"}</button></form><List rows={(schedules??[]).slice(0,10)} render={(s:any)=><><span>{s.employee?.first_name} {s.employee?.last_name}</span><span className="text-sm text-muted-foreground">{s.day_of_week} · {s.starts_at}–{s.ends_at} · {s.capacity_units}</span></>}/></Section>
      <Section title={ar?"الحضور والتأخير":"Attendance & Lateness"}><form action={addAttendance} className="grid gap-2 sm:grid-cols-2">{empSelect()}<input name="attendance_date" type="date" required className="rounded border p-2"/><select name="status" className="rounded border p-2"><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="partial">Partial</option><option value="leave">Leave</option></select><input name="check_in" type="time" className="rounded border p-2"/><input name="check_out" type="time" className="rounded border p-2"/><input name="overtime_minutes" type="number" min="0" defaultValue="0" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"تسجيل":"Record"}</button></form><List rows={(attendance??[])} render={(a:any)=><><span>{a.employee?.first_name} {a.employee?.last_name}</span><span className="text-sm text-muted-foreground">{a.attendance_date} · {a.status}</span></>}/></Section>
      <Section title={ar?"الإجازات":"Leave"}><form action={addLeave} className="grid gap-2 sm:grid-cols-2">{empSelect()}{(leaveTypes??[]).length?<select name="leave_type_id" required className="rounded border p-2">{(leaveTypes??[]).map((l:any)=><option key={l.id} value={l.id}>{ar?(l.name_ar||l.name):l.name}</option>)}</select>:<input name="leave_type_id" required placeholder="Leave type id" className="rounded border p-2"/>}<input name="starts_on" type="date" required className="rounded border p-2"/><input name="ends_on" type="date" required className="rounded border p-2"/><input name="days" type="number" step="0.5" min="0.5" required placeholder="Days" className="rounded border p-2"/><input name="reason" placeholder={ar?"السبب":"Reason"} className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"طلب إجازة":"Request leave"}</button></form><List rows={(leaveRequests??[])} render={(r:any)=><><span>{r.employee?.first_name} {r.employee?.last_name}</span><span className="text-sm text-muted-foreground">{r.starts_on} → {r.ends_on} · {r.status}</span></>}/></Section>
      <Section title={ar?"الرواتب":"Payroll"}><form action={addPayroll} className="grid gap-2 sm:grid-cols-3"><input name="period_start" type="date" required className="rounded border p-2"/><input name="period_end" type="date" required className="rounded border p-2"/><input name="currency" defaultValue="JOD" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-3">{ar?"فتح فترة":"Open period"}</button></form><form action={addPayrollEntry} className="mt-4 grid gap-2 sm:grid-cols-2">{empSelect()}<select name="payroll_period_id" required className="rounded border p-2">{payrollRows.map((p:any)=><option key={p.id} value={p.id}>{p.period_start} → {p.period_end}</option>)}</select><input name="base_salary" type="number" step="0.01" placeholder="Base salary" className="rounded border p-2"/><input name="allowances" type="number" step="0.01" placeholder="Allowances" className="rounded border p-2"/><input name="overtime" type="number" step="0.01" placeholder="Overtime" className="rounded border p-2"/><input name="bonuses" type="number" step="0.01" placeholder="Bonuses" className="rounded border p-2"/><input name="commissions" type="number" step="0.01" placeholder="Commissions" className="rounded border p-2"/><input name="deductions" type="number" step="0.01" placeholder="Deductions" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"إضافة مسير":"Add payroll entry"}</button></form><List rows={(payrollEntries??[])} render={(p:any)=><><span>{p.employee?.first_name} {p.employee?.last_name}</span><span className="text-sm text-muted-foreground">Net {p.net_subunits/100} · {p.status}</span></>}/></Section>
      <Section title={ar?"المزايا":"Benefits"}><form action={addBenefit} className="grid gap-2 sm:grid-cols-2">{empSelect()}<input name="benefit_name" required placeholder="Benefit" className="rounded border p-2"/><input name="value" type="number" step="0.01" min="0" placeholder="Value" className="rounded border p-2"/><input name="currency" defaultValue="JOD" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"إضافة ميزة":"Add benefit"}</button></form><List rows={(benefits??[])} render={(b:any)=><><span>{b.employee?.first_name} {b.employee?.last_name} · {b.benefit_name}</span><span className="text-sm text-muted-foreground">{b.value_subunits/100} {b.currency}</span></>}/></Section>
      <Section title={ar?"العمولات":"Commissions"}><form action={addCommission} className="grid gap-2 sm:grid-cols-2"><input name="name" required placeholder="Rule name" className="rounded border p-2"/><select name="basis" className="rounded border p-2"><option value="collected_revenue">Collected revenue</option><option value="invoice_value">Invoice value</option><option value="procedure_count">Procedure count</option><option value="fixed_bonus">Fixed bonus</option></select><input name="rate" type="number" step="0.0001" min="0" placeholder="Rate" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground">{ar?"إضافة قاعدة":"Add rule"}</button></form><form action={addCommissionEntry} className="mt-4 grid gap-2 sm:grid-cols-2">{empSelect()}<select name="commission_rule_id" required className="rounded border p-2">{commissionRows.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input name="source_type" defaultValue="manual" className="rounded border p-2"/><input name="basis" type="number" step="0.01" placeholder="Basis amount" className="rounded border p-2"/><input name="eligible" type="number" step="0.01" placeholder="Eligible amount" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"إضافة عمولة":"Add commission entry"}</button></form><List rows={(commissionEntries??[])} render={(c:any)=><><span>{c.employee?.first_name} {c.employee?.last_name}</span><span className="text-sm text-muted-foreground">{c.source_type} · {c.status}</span></>}/></Section>
      <Section title={ar?"التوظيف والاحتياج":"Recruitment & Staffing Needs"}><form action={addNeed} className="grid gap-2 sm:grid-cols-2"><input name="title" required placeholder="Staffing need" className="rounded border p-2"/><select name="position_id" className="rounded border p-2"><option value="">Position</option>{positionRows.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input name="needed_from" type="date" className="rounded border p-2"/><input name="needed_to" type="date" className="rounded border p-2"/><input name="quantity" type="number" min="1" defaultValue="1" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"إضافة احتياج":"Add staffing need"}</button></form><form action={addCandidate} className="mt-4 grid gap-2 sm:grid-cols-2"><select name="staffing_need_id" className="rounded border p-2"><option value="">Need</option>{(staffingNeeds??[]).map((n:any)=><option key={n.id} value={n.id}>{n.title}</option>)}</select><input name="first_name" required placeholder="Candidate first name" className="rounded border p-2"/><input name="last_name" required placeholder="Candidate last name" className="rounded border p-2"/><input name="phone" placeholder="Phone" className="rounded border p-2"/><input name="email" type="email" placeholder="Email" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{ar?"إضافة مرشح":"Add candidate"}</button></form><List rows={(staffingNeeds??[])} render={(n:any)=><><span>{n.title}</span><span className="text-sm text-muted-foreground">{n.quantity} · {n.status}</span></>}/><List rows={(candidates??[])} render={(c:any)=><><span>{c.first_name} {c.last_name}</span><span className="text-sm text-muted-foreground">{c.stage}</span></>}/></Section>
    </div>
  </div>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>}
function List({rows,render}:{rows:any[];render:(row:any)=>React.ReactNode}){return <div className="mt-5 divide-y">{rows.slice(0,20).map((row:any)=><div key={row.id} className="flex items-center justify-between gap-3 py-2">{render(row)}</div>)}{rows.length===0&&<p className="text-sm text-muted-foreground">No records yet.</p>}</div>}
