"use client";
import { useState } from "react"; import { useAuth } from "@/core/auth/AuthContext"; import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card"; import { Button } from "@/shared/components/ui/button"; import { Input } from "@/shared/components/ui/input"; import { Badge } from "@/shared/components/ui/badge"; import { findPatientByPhone, checkInPatient } from "@/domain/queue/queue.actions"; import { createPatientFromObject } from "@/domain/patients/patients.actions"; import { Stethoscope, Clock, Phone, CheckCircle2, AlertCircle, ArrowRight } from "lucide-react"; import { useI18n } from "@/core/i18n/I18nProvider";
export function AmbientKioskView({ tenantId: propTenantId }: { tenantId?: string }) { const { tenantId: authTenantId } = useAuth(); const tenantId = propTenantId || authTenantId; const { locale, kiosk: t } = useI18n(); const [mode, setMode] = useState<"idle" | "checkin" | "register" | "queue" | "error">("idle"); const [phone, setPhone] = useState(""); const [patientName, setPatientName] = useState(""); const [queueNumber, setQueueNumber] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  if (!tenantId) return <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-4" dir={locale === "ar" ? "rtl" : "ltr"}><Card className="border-slate-700 bg-slate-800/80 text-center"><CardContent className="p-8 text-slate-400">{t.loading}</CardContent></Card></div>;
  const checkin = async () => { if (phone.length < 8) { setError(t.invalidPhone); setMode("error"); return; } setBusy(true); setError(""); try { const patient = await findPatientByPhone(phone, tenantId); if (patient) { const session = await checkInPatient({ patient_id: patient.id }); setQueueNumber("A" + session.id.slice(-2).toUpperCase()); setMode("queue"); } else setMode("register"); } catch (e) { setError(e instanceof Error ? e.message : t.lookupFailed); setMode("error"); } finally { setBusy(false); } };
  const register = async () => { if (!patientName.trim() || phone.length < 8) { setError(t.incomplete); setMode("error"); return; } setBusy(true); try { const patient = await createPatientFromObject({ tenant_id: tenantId, first_name: patientName, last_name: "", phone_primary: phone, patient_status: "active" }); if (patient.error) throw new Error(patient.error); if (patient.data) { const session = await checkInPatient({ patient_id: patient.data.id }); setQueueNumber("A" + session.id.slice(-2).toUpperCase()); setMode("queue"); } } catch (e) { setError(e instanceof Error ? e.message : t.registrationFailed); setMode("error"); } finally { setBusy(false); } };
  const reset = () => { setMode("idle"); setPhone(""); setPatientName(""); setQueueNumber(null); setError(""); setBusy(false); };
  const shell = (content: React.ReactNode) => <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-4" dir={locale === "ar" ? "rtl" : "ltr"}><div className="w-full max-w-lg">{content}</div></div>;
  if (mode === "idle") return shell(<Card className="border-slate-700 bg-slate-800/80"><CardHeader className="text-center"><div className="mx-auto mb-4 flex h-20 w-20 items-center justify-center rounded-full bg-primary/10"><Stethoscope className="h-10 w-10 text-primary" /></div><CardTitle className="text-3xl text-white">{t.welcome}</CardTitle><p className="mt-2 text-slate-400">{t.checkinPrompt}</p></CardHeader><CardContent><Button onClick={() => setMode("checkin")} className="h-16 w-full text-lg" size="lg"><Clock className="me-2 h-6 w-6" />{t.checkin}</Button></CardContent></Card>);
  if (mode === "checkin") return shell(<Card className="border-slate-700 bg-slate-800/80"><CardHeader className="text-center"><CardTitle className="text-2xl text-white">{t.checkinTitle}</CardTitle><p className="text-slate-400">{t.phonePrompt}</p></CardHeader><CardContent className="space-y-4"><div className="relative"><Phone className="absolute start-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" /><Input value={phone} onChange={e => setPhone(e.target.value)} placeholder={t.phoneExample} className="h-14 ps-10 text-lg" type="tel" maxLength={10} /></div><Button onClick={() => void checkin()} className="h-14 w-full text-lg" disabled={busy}>{busy ? t.searching : t.search}</Button><Button onClick={reset} variant="ghost" className="w-full text-slate-400">{t.back}</Button></CardContent></Card>);
  if (mode === "register") return shell(<Card className="border-slate-700 bg-slate-800/80"><CardHeader className="text-center"><CardTitle className="text-2xl text-white">{t.newPatient}</CardTitle><p className="text-slate-400">{t.registerPrompt}</p></CardHeader><CardContent className="space-y-4"><Input value={phone} onChange={e => setPhone(e.target.value)} placeholder={t.phone} className="h-12" type="tel" maxLength={10} /><Input value={patientName} onChange={e => setPatientName(e.target.value)} placeholder={t.fullName} className="h-12" /><Button onClick={() => void register()} className="h-14 w-full text-lg" disabled={busy}>{busy ? t.registering : t.registerAndCheckin}</Button><Button onClick={() => setMode("checkin")} variant="ghost" className="w-full text-slate-400">{t.back}</Button></CardContent></Card>);
  if (mode === "queue" && queueNumber) return shell(<Card className="border-slate-700 bg-slate-800/80 text-center"><CardHeader><div className="mx-auto mb-2 flex h-16 w-16 items-center justify-center rounded-full bg-green-500/20"><CheckCircle2 className="h-8 w-8 text-green-400" /></div><CardTitle className="text-2xl text-white">{t.success}</CardTitle></CardHeader><CardContent className="space-y-6"><div><p className="mb-2 text-slate-400">{t.queueNumber}</p><div className="text-6xl font-bold text-primary">{queueNumber}</div></div><Badge variant="secondary" className="px-4 py-2 text-lg">{t.waiting}</Badge><p className="text-slate-400">{t.calledSoon}</p><Button onClick={reset} className="h-12 w-full text-lg">{t.done}</Button></CardContent></Card>);
  return shell(<Card className="border-red-700 bg-slate-800/80 text-center"><CardHeader><div className="mx-auto mb-2 flex h-16 w-16 items-center justify-center rounded-full bg-red-500/20"><AlertCircle className="h-8 w-8 text-red-400" /></div><CardTitle className="text-2xl text-white">{t.error}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-slate-400">{error || t.retryMessage}</p><Button onClick={reset} className="w-full"><ArrowRight className="me-2 h-4 w-4 rtl:rotate-180" />{t.retry}</Button></CardContent></Card>);
}
