"use client";

import { useState } from "react";
import { useTenantId } from "@/core/auth/useTenantId";
import { usePermissions } from "@/core/permissions/usePermissions";
import { useI18n } from "@/core/i18n/I18nProvider";
import { useAuditTrail, useAuditActions, useAuditTableNames } from "@/domain/audit/audit.queries";
import type { AuditFilterParams } from "@/domain/audit/audit.types";
import { Button } from "@/shared/components/ui/button";
import { Input } from "@/shared/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Badge } from "@/shared/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/shared/components/ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select";
import { ClipboardList, Search, Loader2, AlertCircle, Calendar, User, Database, Activity, X, ChevronLeft, ChevronRight } from "lucide-react";

const PAGE_SIZE = 25;

export function AuditLogManager() {
  const { locale, admin: a, audit: t } = useI18n();
  const { tenantId } = useTenantId();
  const { hasPermission, isLoading: permsLoading } = usePermissions();
  const [filters, setFilters] = useState<AuditFilterParams>({ page: 1, pageSize: PAGE_SIZE });
  const [search, setSearch] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState("");
  const { data: result, isLoading, error } = useAuditTrail(tenantId, filters); const { data: actions } = useAuditActions(tenantId); const { data: tables } = useAuditTableNames(tenantId);
  const direction = locale === "ar" ? "rtl" : "ltr";
  const actionLabel = (action: string) => t.actions[action.toLowerCase() as keyof typeof t.actions] ?? t.unknownAction;
  const resourceLabel = (resource: string) => t.resources[resource as keyof typeof t.resources] ?? t.unknownResource;
  const roleLabel = (role: string | null | undefined) => role ? t.roles[role as keyof typeof t.roles] ?? t.unknownRole : t.unknownRole;
  if (permsLoading || isLoading) return <div className="flex items-center justify-center py-12" dir={direction}><Loader2 className="h-6 w-6 animate-spin text-primary" /><span className="ms-3 text-muted-foreground">{permsLoading ? a.users.loading : a.audit.loading}</span></div>;
  if (!hasPermission("audit:read")) return <div className="flex flex-col items-center justify-center py-12 text-center" dir={direction}><AlertCircle className="mb-3 h-10 w-10 text-destructive" /><h3 className="text-lg font-semibold">{a.audit.accessDenied}</h3></div>;
  const clear = () => { setSearch(""); setDateFrom(""); setDateTo(""); setFilters({ page: 1, pageSize: PAGE_SIZE }); };
  const hasFilters = !!(filters.search || filters.action || filters.tableName || filters.dateFrom || filters.dateTo);
  const formatDate = (iso: string) => new Date(iso).toLocaleString(locale === "ar" ? "ar-u-nu-latn" : "en-US-u-nu-latn", { dateStyle: "medium", timeStyle: "short", numberingSystem: "latn" });
  return <div className="space-y-6" dir={direction}>
    <div className="flex items-center gap-3"><ClipboardList className="h-6 w-6 text-primary" /><div><h2 className="text-xl font-semibold">{a.audit.title}</h2><p className="text-sm text-muted-foreground">{a.audit.description}</p></div></div>
    <Card><CardContent className="pt-6"><div className="flex flex-wrap items-end gap-4"><div className="min-w-[240px] flex-1"><label className="mb-1.5 block text-sm font-medium">{t.searchLabel}</label><div className="flex gap-2"><Input placeholder={t.searchPlaceholder} value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => { if (e.key === "Enter") setFilters(p => ({ ...p, search: search.trim() || undefined, page: 1 })); }} /><Button variant="secondary" size="icon" onClick={() => setFilters(p => ({ ...p, search: search.trim() || undefined, page: 1 }))}><Search className="h-4 w-4" /></Button></div></div><div className="min-w-[160px]"><label className="mb-1.5 block text-sm font-medium">{a.audit.action}</label><Select value={filters.action || "all"} onValueChange={v => setFilters(p => ({ ...p, action: v === "all" ? undefined : v, page: 1 }))}><SelectTrigger><SelectValue placeholder={t.allActions} /></SelectTrigger><SelectContent><SelectItem value="all">{t.allActions}</SelectItem>{actions?.map(v => <SelectItem key={v} value={v}>{actionLabel(v)}</SelectItem>)}</SelectContent></Select></div><div className="min-w-[160px]"><label className="mb-1.5 block text-sm font-medium">{a.audit.resource}</label><Select value={filters.tableName || "all"} onValueChange={v => setFilters(p => ({ ...p, tableName: v === "all" ? undefined : v, page: 1 }))}><SelectTrigger><SelectValue placeholder={t.allTables} /></SelectTrigger><SelectContent><SelectItem value="all">{t.allTables}</SelectItem>{tables?.map(v => <SelectItem key={v} value={v}>{resourceLabel(v)}</SelectItem>)}</SelectContent></Select></div><div><label className="mb-1.5 block text-sm font-medium">{t.from}</label><Input type="date" value={dateFrom} onChange={e => { setDateFrom(e.target.value); setFilters(p => ({ ...p, dateFrom: e.target.value || undefined, page: 1 })); }} /></div><div><label className="mb-1.5 block text-sm font-medium">{t.to}</label><Input type="date" value={dateTo} onChange={e => { setDateTo(e.target.value); setFilters(p => ({ ...p, dateTo: e.target.value || undefined, page: 1 })); }} /></div>{hasFilters && <Button variant="ghost" size="sm" onClick={clear}><X className="me-1 h-4 w-4" />{t.clearFilters}</Button>}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Activity className="h-4 w-4" />{a.audit.title}{result && <Badge variant="secondary">{result.totalCount}</Badge>}</CardTitle></CardHeader><CardContent>{error ? <div className="py-12 text-center"><AlertCircle className="mx-auto mb-3 h-10 w-10 text-destructive" /><p className="text-destructive">{a.audit.loadFailed}</p></div> : !result || result.records.length === 0 ? <div className="py-12 text-center"><ClipboardList className="mx-auto mb-3 h-10 w-10 text-muted-foreground" /><h3 className="text-lg font-semibold">{a.audit.noEntries}</h3></div> : <><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>{a.audit.timestamp}</TableHead><TableHead>{a.audit.action}</TableHead><TableHead>{a.audit.resource}</TableHead><TableHead>{a.audit.actor}</TableHead><TableHead>{a.audit.role}</TableHead><TableHead>{t.record}</TableHead></TableRow></TableHeader><TableBody>{result.records.map(record => <TableRow key={record.id}><TableCell className="whitespace-nowrap text-sm"><span className="inline-flex items-center gap-1.5"><Calendar className="h-3.5 w-3.5 text-muted-foreground" />{formatDate(record.created_at)}</span></TableCell><TableCell><Badge variant="outline">{actionLabel(record.action)}</Badge></TableCell><TableCell><span className="inline-flex items-center gap-1.5"><Database className="h-3.5 w-3.5 text-muted-foreground" /><span className="text-sm">{resourceLabel(record.table_name)}</span></span></TableCell><TableCell><span className="inline-flex items-center gap-1.5"><User className="h-3.5 w-3.5 text-muted-foreground" />{record.actor?.full_name || record.actor?.email || a.audit.unknown}</span></TableCell><TableCell>{roleLabel(record.actor_role)}</TableCell><TableCell className="font-mono text-xs text-muted-foreground">{record.record_id ? `${record.record_id.slice(0, 8)}…` : "—"}</TableCell></TableRow>)}</TableBody></Table></div>{result.totalPages > 1 && <div className="mt-4 flex items-center justify-between border-t pt-4"><span className="text-sm text-muted-foreground">{result.page} / {result.totalPages}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={result.page <= 1} onClick={() => setFilters(p => ({ ...p, page: p.page! - 1 }))}><ChevronLeft className="me-1 h-4 w-4" />{t.previous}</Button><Button variant="outline" size="sm" disabled={result.page >= result.totalPages} onClick={() => setFilters(p => ({ ...p, page: p.page! + 1 }))}>{t.next}<ChevronRight className="ms-1 h-4 w-4" /></Button></div></div>}</>}</CardContent></Card>
  </div>;
}
