"use client";
import { useState } from "react";
import { usePermissions } from "@/core/permissions/usePermissions";
import { useI18n } from "@/core/i18n/I18nProvider";
import { ClinicProfileForm } from "@/features/settings/ClinicProfileForm";
import { RolesManager } from "@/features/settings/roles/RolesManager";
import { UsersManager } from "@/features/settings/users/UsersManager";
import { OverridesManager } from "@/features/settings/overrides/OverridesManager";
import { AuditLogManager } from "@/features/settings/audit";
import { SystemPreferencesManager } from "@/features/settings/system";
import { NotificationsManager } from "@/features/settings/notifications";
import { SubscriptionCenter } from "@/features/settings/subscriptions";
import { ProceduresManager } from "@/features/settings/procedures";
import { RoomsManager } from "@/features/settings/rooms";
import { UserSettingsManager } from "@/features/settings/user/UserSettingsManager";
import { RoleTemplatesManager } from "@/features/settings/templates/RoleTemplatesManager";
import { LayoutDashboard, Building2, Users, ShieldCheck, FileText, UserCog, Bell, CreditCard, ClipboardList, Settings, Stethoscope, DoorOpen, UserRound } from "lucide-react";

const tabs=[{id:"overview",icon:LayoutDashboard,permission:null,key:"overview"},{id:"clinic-profile",icon:Building2,permission:"settings:read",key:"clinic"},{id:"users",icon:Users,permission:"users:read",key:"users"},{id:"roles",icon:ShieldCheck,permission:"roles:read",key:"roles"},{id:"templates",icon:FileText,permission:"templates:manage",key:"templates"},{id:"overrides",icon:UserCog,permission:"overrides:manage",key:"overrides"},{id:"notifications",icon:Bell,permission:"notifications:manage",key:"notifications"},{id:"subscription",icon:CreditCard,permission:"subscription:read",key:"subscription"},{id:"audit",icon:ClipboardList,permission:"audit:read",key:"audit"},{id:"procedures",icon:Stethoscope,permission:"procedures:read",key:"procedures"},{id:"rooms",icon:DoorOpen,permission:"settings:read",key:"clinic"},{id:"system",icon:Settings,permission:"settings:update",key:"preferences"},{id:"user-settings",icon:UserRound,permission:null,key:"mySettings"}] as const;
export default function SettingsPage(){const[activeTab,setActiveTab]=useState("overview");const{hasPermission,isLoading}=usePermissions();const{admin:a}=useI18n();if(isLoading)return <div className="flex items-center justify-center py-12"><div className="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent"/><span className="ms-3 text-muted-foreground">{a.users.loading}</span></div>;const visible=tabs.filter(t=>t.permission===null||hasPermission(t.permission as any));return <div className="space-y-6"><h1 className="text-2xl font-bold">{a.settings.title}</h1><div className="flex flex-wrap gap-2 border-b border-border pb-2">{visible.map(tab=>{const Icon=tab.icon;const active=activeTab===tab.id;return <button key={tab.id} onClick={()=>setActiveTab(tab.id)} aria-current={active?"page":undefined} className={`inline-flex items-center gap-2 rounded-t-md px-4 py-2 text-sm font-medium ${active?"border-b-2 border-primary text-primary":"text-muted-foreground hover:text-foreground"}`}><Icon className="h-4 w-4"/>{tab.id==="user-settings"?((a.settings as any).mySettings||"My Settings"):a.settings[tab.key]}</button>})}</div><div className="rounded-lg border border-border bg-card p-6 shadow-sm">{activeTab==="overview"&&<div className="space-y-4"><h2 className="text-xl font-semibold">{a.settings.overview}</h2><p className="text-muted-foreground">{a.settings.description}</p></div>}{activeTab==="clinic-profile"&&<ClinicProfileForm/>}{activeTab==="users"&&<UsersManager/>}{activeTab==="roles"&&<RolesManager/>}{activeTab==="templates"&&<RoleTemplatesManager/>}{activeTab==="overrides"&&<OverridesManager/>}{activeTab==="notifications"&&<NotificationsManager/>}{activeTab==="subscription"&&<SubscriptionCenter/>}{activeTab==="audit"&&<AuditLogManager/>}{activeTab==="procedures"&&<ProceduresManager/>}{activeTab==="rooms"&&<RoomsManager/>}{activeTab==="system"&&<SystemPreferencesManager/>}{activeTab==="user-settings"&&<UserSettingsManager/>}</div></div>}
