"use client";
import { useState } from "react";
import { useRoleTemplates } from "@/domain/role-templates/roleTemplates.queries";
import { createRole } from "@/domain/roles/roles.actions";
import { useI18n } from "@/core/i18n/I18nProvider";
import { Card,CardContent,CardHeader,CardTitle } from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import { Badge } from "@/shared/components/ui/badge";
import { Loader2,Copy,CheckCircle,AlertCircle } from "lucide-react";

export function RoleTemplatesManager(){const{locale}=useI18n();const{data:templates=[],isLoading,refetch}=useRoleTemplates();const[busy,setBusy]=useState<string|null>(null);const[result,setResult]=useState<{id:string;success:boolean;message:string}|null>(null);const ar=locale==="ar";if(isLoading)return <div className="py-8 flex justify-center"><Loader2 className="h-5 w-5 animate-spin"/></div>;const useTemplate=async(t:any)=>{setBusy(t.id);setResult(null);const base=`${String(t.template_key||"role")}_custom`;const key=`${base}_${Date.now().toString(36)}`;try{const r=await createRole({role_key:key,role_name:ar?`${t.template_name_ar||t.template_name} مخصص`:`${t.template_name} Custom`,role_name_ar:ar?`${t.template_name_ar||t.template_name} مخصص`:undefined,description:t.description||undefined,workspace:t.workspace||undefined,permissionIds:(t.role_template_permissions??[]).map((p:any)=>p.permission_id)});if(r.success){setResult({id:t.id,success:true,message:ar?"تم إنشاء الدور المخصص بنجاح.":"Custom role created successfully."});void refetch();}else setResult({id:t.id,success:false,message:ar?`تعذر إنشاء الدور: ${r.error||"خطأ غير معروف"}`:`Could not create the role: ${r.error||"Unknown error"}`});}catch{setResult({id:t.id,success:false,message:ar?"تعذر إنشاء الدور.":"Could not create the role."});}finally{setBusy(null);}};return <div className="space-y-4" dir={ar?"rtl":"ltr"}><div><h2 className="text-xl font-semibold">{ar?"قوالب الأدوار":"Role Templates"}</h2><p className="text-sm text-muted-foreground">{ar?"قوالب استرشادية قابلة للنسخ والتعديل؛ لا تمنح صلاحيات بحد ذاتها.":"Advisory starting configurations. Templates never authorize users directly."}</p></div><div className="grid gap-4 md:grid-cols-2">{templates.map((t:any)=><Card key={t.id}><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle className="text-base">{ar?t.template_name_ar||t.template_name:t.template_name}</CardTitle><Badge variant="outline">{t.workspace||"—"}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">{t.description||""}</p><p className="text-xs text-muted-foreground">{(t.role_template_permissions??[]).length} {ar?"صلاحية استرشادية":"advisory permissions"}</p><Button size="sm" onClick={()=>void useTemplate(t)} disabled={busy===t.id} className="gap-2">{busy===t.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Copy className="h-4 w-4"/>}{ar?"نسخ كدور مخصص":"Use as custom role"}</Button>{result?.id===t.id&&<div className={`flex items-center gap-2 text-sm ${result.success?"text-green-600":"text-destructive"}`}>{result.success?<CheckCircle className="h-4 w-4"/>:<AlertCircle className="h-4 w-4"/>}{result.message}</div>}</CardContent></Card>)}</div></div>}