"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/infrastructure/supabase/server";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import type { CreateRoleInput,UpdateRoleInput,RoleActionResult } from "./roles.types";
export interface UpdateRolePermissionsResult{success:boolean;error:string|null;}
async function resolveCaller(){const s=await createClient();const{data:{user},error}=await s.auth.getUser();if(error||!user)throw"UNAUTHORIZED";const{data:cu,error:ce}=await s.from("clinic_users").select("id,tenant_id").eq("auth_user_id",user.id).maybeSingle();if(ce||!cu)throw"TENANT_RESOLUTION_FAILED";return{s,user,tenantId:cu.tenant_id};}
async function requirePermission(userId:string,tenantId:string,p:string){if(!(await getEffectivePermissions(userId,tenantId)).includes(p as any))throw"PERMISSION_DENIED";}
const err=(e:unknown)=>typeof e==="string"&&/^[A-Z][A-Z0-9_]+$/.test(e)?e:"UNKNOWN";
export async function updateRolePermissions(roleId:string,permissionIds:string[]):Promise<UpdateRolePermissionsResult>{try{const{s,user,tenantId}=await resolveCaller();await requirePermission(user.id,tenantId,"roles:manage");const{data:role}=await s.from("roles").select("id,is_system_role,tenant_id").eq("id",roleId).maybeSingle();if(!role)return{success:false,error:"ROLE_NOT_FOUND"};if(role.is_system_role)return{success:false,error:"SYSTEM_TEMPLATE_NOT_EDITABLE"};if(role.tenant_id!==tenantId)return{success:false,error:"ROLE_WRONG_TENANT"};const{error}=await s.rpc("set_role_permissions",{p_role_id:roleId,p_permission_ids:[...new Set(permissionIds)]});if(error)return{success:false,error:error.message.includes("PERMISSION_DENIED")?"PERMISSION_DENIED":"ROLE_PERMISSIONS_UPDATE_FAILED"};revalidatePath("/settings");return{success:true,error:null};}catch(e){return{success:false,error:err(e)};}}
export async function createRole(input:CreateRoleInput):Promise<RoleActionResult>{try{const{s,user,tenantId}=await resolveCaller();await requirePermission(user.id,tenantId,"roles:manage");const key=input.role_key.trim().toLowerCase().replace(/\s+/g,"_");if(!/^[a-z0-9_]{2,}$/.test(key))return{success:false,error:"ROLE_KEY_INVALID"};if(!input.workspace)return{success:false,error:"ROLE_WORKSPACE_REQUIRED"};const{data:conflict}=await s.from("roles").select("id").eq("role_key",key).or(`tenant_id.eq.${tenantId},is_system_role.eq.true`).limit(1);if(conflict?.length)return{success:false,error:"ROLE_KEY_EXISTS"};const{data:role,error:ie}=await s.from("roles").insert({role_key:key,role_name:input.role_name.trim(),role_name_ar:input.role_name_ar?.trim()||null,description:input.description?.trim()||null,is_system_role:false,tenant_id:tenantId,workspace:input.workspace}).select("id").single();if(ie||!role)return{success:false,error:"ROLE_CREATE_FAILED"};if(input.permissionIds?.length){const{error:pe}=await s.rpc("set_role_permissions",{p_role_id:role.id,p_permission_ids:[...new Set(input.permissionIds)]});if(pe)return{success:false,error:"ROLE_PERMISSION_ASSIGN_FAILED"};}revalidatePath("/settings");return{success:true,error:null,roleId:role.id};}catch(e){return{success:false,error:err(e)};}}
export async function updateRole(input:UpdateRoleInput):Promise<RoleActionResult>{try{const{s,user,tenantId}=await resolveCaller();await requirePermission(user.id,tenantId,"roles:manage");const{data:role}=await s.from("roles").select("id,is_system_role,tenant_id").eq("id",input.roleId).maybeSingle();if(!role)return{success:false,error:"ROLE_NOT_FOUND"};if(role.is_system_role)return{success:false,error:"SYSTEM_TEMPLATE_NOT_EDITABLE"};if(role.tenant_id!==tenantId)return{success:false,error:"ROLE_WRONG_TENANT"};const u:Record<string,unknown>={};if(input.role_name!==undefined)u.role_name=input.role_name.trim();if(input.role_name_ar!==undefined)u.role_name_ar=input.role_name_ar.trim()||null;if(input.description!==undefined)u.description=input.description.trim()||null;if(input.workspace!==undefined)u.workspace=input.workspace;if(!Object.keys(u).length)return{success:true,error:null};const{error}=await s.from("roles").update(u).eq("id",input.roleId).eq("tenant_id",tenantId);if(error)return{success:false,error:"ROLE_UPDATE_FAILED"};revalidatePath("/settings");return{success:true,error:null};}catch(e){return{success:false,error:err(e)};}}
export async function deleteRole(roleId:string):Promise<RoleActionResult>{try{const{s,user,tenantId}=await resolveCaller();await requirePermission(user.id,tenantId,"roles:manage");const{data:role}=await s.from("roles").select("id,is_system_role,tenant_id").eq("id",roleId).maybeSingle();if(!role)return{success:false,error:"ROLE_NOT_FOUND"};if(role.is_system_role)return{success:false,error:"SYSTEM_TEMPLATE_NOT_EDITABLE"};if(role.tenant_id!==tenantId)return{success:false,error:"ROLE_WRONG_TENANT"};const{count}=await s.from("clinic_users").select("id",{count:"exact",head:true}).eq("role_id",roleId);if((count??0)>0)return{success:false,error:"ROLE_IN_USE"};const{error}=await s.from("roles").delete().eq("id",roleId).eq("tenant_id",tenantId);if(error)return{success:false,error:"ROLE_DELETE_FAILED"};revalidatePath("/settings");return{success:true,error:null};}catch(e){return{success:false,error:err(e)};}}
