"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/infrastructure/supabase/server";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import type { CreateRoleInput, UpdateRoleInput, RoleActionResult } from "./roles.types";

export interface UpdateRolePermissionsResult { success: boolean; error: string | null; }
async function resolveCaller() { const supabase = await createClient(); const { data: { user }, error } = await supabase.auth.getUser(); if (error || !user) throw "UNAUTHORIZED"; const { data: cu, error: ce } = await supabase.from("clinic_users").select("id,tenant_id").eq("auth_user_id", user.id).maybeSingle(); if (ce || !cu?.tenant_id) throw "TENANT_RESOLUTION_FAILED"; return { user, tenantId: cu.tenant_id }; }
async function requirePermission(userId: string, tenantId: string, permission: string) { if (!(await getEffectivePermissions(userId, tenantId)).includes(permission as any)) throw "PERMISSION_DENIED"; }
const code = (e: unknown) => typeof e === "string" && /^[A-Z][A-Z0-9_]+$/.test(e) ? e : "UNKNOWN";

export async function updateRolePermissions(roleId: string, permissionIds: string[]): Promise<UpdateRolePermissionsResult> {
  try { const supabase = await createClient(); const { user, tenantId } = await resolveCaller(); await requirePermission(user.id, tenantId, "roles:manage"); const { data: role } = await supabase.from("roles").select("id,is_system_role,tenant_id").eq("id", roleId).maybeSingle(); if (!role) return { success:false,error:"ROLE_NOT_FOUND" }; if (role.is_system_role) return { success:false,error:"SYSTEM_TEMPLATE_NOT_EDITABLE" }; if (role.tenant_id !== tenantId) return { success:false,error:"ROLE_WRONG_TENANT" }; const ids=[...new Set(permissionIds)]; const { data: valid } = ids.length ? await supabase.from("permissions").select("id").in("id",ids) : {data:[] as {id:string}[]}; const validIds=(valid??[]).map(p=>p.id); const {error:de}=await supabase.from("role_permissions").delete().eq("role_id",roleId); if(de) return {success:false,error:"ROLE_PERMISSIONS_UPDATE_FAILED"}; if(validIds.length){const {error:ie}=await supabase.from("role_permissions").insert(validIds.map(permission_id=>({role_id:roleId,permission_id}))); if(ie)return {success:false,error:"ROLE_PERMISSIONS_SAVE_FAILED"};} revalidatePath("/settings"); return {success:true,error:null}; } catch(e){return {success:false,error:code(e)};}
}

export async function createRole(input: CreateRoleInput): Promise<RoleActionResult> {
  try { const supabase=await createClient(); const {user,tenantId}=await resolveCaller(); await requirePermission(user.id,tenantId,"roles:manage"); const key=input.role_key.trim().toLowerCase().replace(/\s+/g,"_"); if(!/^[a-z0-9_]{2,}$/.test(key))return{success:false,error:"ROLE_KEY_INVALID"}; if(!input.workspace)return{success:false,error:"ROLE_WORKSPACE_REQUIRED"}; const {data:conflict}=await supabase.from("roles").select("id").eq("role_key",key).or(`tenant_id.eq.${tenantId},is_system_role.eq.true`).limit(1); if(conflict?.length)return{success:false,error:"ROLE_KEY_EXISTS"}; const {data:role,error}=await supabase.from("roles").insert({role_key:key,role_name:input.role_name.trim(),role_name_ar:input.role_name_ar?.trim()||null,description:input.description?.trim()||null,is_system_role:false,tenant_id:tenantId,workspace:input.workspace}).select("id").single(); if(error||!role)return{success:false,error:"ROLE_CREATE_FAILED"}; if(input.permissionIds?.length){const ids=[...new Set(input.permissionIds)];const{data:valid}=await supabase.from("permissions").select("id").in("id",ids);const validIds=(valid??[]).map(p=>p.id);if(validIds.length){const{error:pe}=await supabase.from("role_permissions").insert(validIds.map(permission_id=>({role_id:role.id,permission_id})));if(pe)return{success:false,error:"ROLE_PERMISSION_ASSIGN_FAILED"};}} revalidatePath("/settings"); return{success:true,error:null,roleId:role.id}; }catch(e){return{success:false,error:code(e)};}
}

export async function updateRole(input: UpdateRoleInput): Promise<RoleActionResult> {
  try {const supabase=await createClient();const{user,tenantId}=await resolveCaller();await requirePermission(user.id,tenantId,"roles:manage");const{data:role}=await supabase.from("roles").select("id,is_system_role,tenant_id").eq("id",input.roleId).maybeSingle();if(!role)return{success:false,error:"ROLE_NOT_FOUND"};if(role.is_system_role)return{success:false,error:"SYSTEM_TEMPLATE_NOT_EDITABLE"};if(role.tenant_id!==tenantId)return{success:false,error:"ROLE_WRONG_TENANT"};const updates:Record<string,unknown>={};if(input.role_name!==undefined)updates.role_name=input.role_name.trim();if(input.role_name_ar!==undefined)updates.role_name_ar=input.role_name_ar.trim()||null;if(input.description!==undefined)updates.description=input.description.trim()||null;if(input.workspace!==undefined)updates.workspace=input.workspace;if(!Object.keys(updates).length)return{success:true,error:null};const{error}=await supabase.from("roles").update(updates).eq("id",input.roleId).eq("tenant_id",tenantId);if(error)return{success:false,error:"ROLE_UPDATE_FAILED"};revalidatePath("/settings");return{success:true,error:null};}catch(e){return{success:false,error:code(e)};}
}

export async function deleteRole(roleId:string):Promise<RoleActionResult>{
  try{const supabase=await createClient();const{user,tenantId}=await resolveCaller();await requirePermission(user.id,tenantId,"roles:manage");const{data:role}=await supabase.from("roles").select("id,is_system_role,tenant_id").eq("id",roleId).maybeSingle();if(!role)return{success:false,error:"ROLE_NOT_FOUND"};if(role.is_system_role)return{success:false,error:"SYSTEM_TEMPLATE_NOT_EDITABLE"};if(role.tenant_id!==tenantId)return{success:false,error:"ROLE_WRONG_TENANT"};const{count}=await supabase.from("clinic_users").select("id",{count:"exact",head:true}).eq("role_id",roleId);if((count??0)>0)return{success:false,error:"ROLE_IN_USE"};const{error}=await supabase.from("roles").delete().eq("id",roleId).eq("tenant_id",tenantId);if(error)return{success:false,error:"ROLE_DELETE_FAILED"};revalidatePath("/settings");return{success:true,error:null};}catch(e){return{success:false,error:code(e)};}
}
