import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import { createClient } from "@/infrastructure/supabase/server";
import { resolveTenantId } from "@/core/auth/resolveTenantId";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import { createPayrollPeriod, } from "@/domain/workforce/workforce.actions";
import { createPayrollEntryFromWorkforce } from "@/domain/workforce/workforce.payroll.actions";
import { createEmployeeAdvance, createPayrollDeduction } from "@/domain/workforce/workforce.payroll.adjustments.actions";
import { createPayrollEarning, issuePayrollPayslip } from "@/domain/workforce/workforce.payroll.core.actions";
import { approvePayrollEntry, payPayrollEntry, setPayrollPeriodStatus } from "@/domain/workforce/workforce.payroll.lifecycle.actions";
import { setBenefitEmployeeContribution } from "@/domain/workforce/workforce.payroll.benefits.actions";

const deductions = [["late_arrival","Late arrival","تأخر"],["early_departure","Early departure","انصراف مبكر"],["unpaid_absence","Unpaid absence","غياب غير مدفوع"],["unpaid_leave","Unpaid leave","إجازة غير مدفوعة"],["benefit_contribution","Benefit contribution","مساهمة منفعة"],["salary_advance","Salary advance","سلفة راتب"],["loan_repayment","Loan repayment","سداد قرض"],["disciplinary","Disciplinary","تأديبي"],["administrative_adjustment","Administrative adjustment","تسوية إدارية"],["overpayment_recovery","Overpayment recovery","استرداد"],["manual_adjustment","Manual adjustment","تسوية يدوية"],["statutory_tax","Statutory tax","ضريبة قانونية"],["statutory_social_security","Social security","ضمان اجتماعي"]] as const;
const earnings = [["allowance","Allowance","بدل"],["overtime","Overtime","عمل إضافي"],["bonus","Bonus","مكافأة"],["other_earning","Other earning","استحقاق آخر"]] as const;

export default async function WorkforcePayrollPage() {
  const supabase = await createClient(); const { data:{user} } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const tenantId = await resolveTenantId(user.id); if (!tenantId) redirect("/login");
  const permissions = await getEffectivePermissions(user.id, tenantId); if (!permissions.includes("workforce:payroll" as any) && !permissions.includes("workforce:manage" as any)) redirect("/workforce");
  const ar = (await cookies()).get("core-system-locale")?.value === "ar";
  const [employees,periods,entries,advances,deductionsQ,earningsQ,installments,payslips,benefits,countryRules] = await Promise.all([
    supabase.from("workforce_employees").select("id,first_name,last_name").eq("tenant_id",tenantId).eq("status","active").order("first_name"),
    supabase.from("workforce_payroll_periods").select("id,period_start,period_end,status,currency").eq("tenant_id",tenantId).order("period_start",{ascending:false}).limit(12),
    supabase.from("workforce_payroll_entries").select("id,employee_id,payroll_period_id,base_salary_subunits,allowances_subunits,overtime_subunits,bonuses_subunits,commissions_subunits,deductions_subunits,net_subunits,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(30),
    supabase.from("workforce_employee_advances").select("id,employee_id,advance_type,amount_subunits,currency,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(30),
    supabase.from("workforce_payroll_deductions").select("id,employee_id,deduction_type,amount_subunits,currency,source_type,status,reason,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(30),
    supabase.from("workforce_payroll_earnings").select("id,employee_id,earning_type,amount_subunits,currency,source_type,status,reason,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(30),
    supabase.from("workforce_advance_installments").select("id,advance_id,installment_no,due_date,amount_subunits,status,payroll_entry_id").eq("tenant_id",tenantId).order("due_date").limit(50),
    supabase.from("workforce_payslips").select("id,employee_id,currency,gross_subunits,deductions_subunits,net_subunits,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).order("issued_at",{ascending:false}).limit(30),
    supabase.from("workforce_benefits").select("id,employee_id,benefit_name,benefit_name_ar,employee_contribution_subunits,currency,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id",tenantId).eq("status","active").order("created_at",{ascending:false}).limit(30),
    supabase.from("workforce_payroll_country_rules").select("id,country_code,name,effective_from,effective_to,tax_enabled,social_security_enabled,employee_rate,employer_rate,currency,status,source_url").is("tenant_id",null).eq("status","active").order("country_code")
  ]);
  const es=employees.data??[], ps=periods.data??[], ens=entries.data??[], ads=advances.data??[], ds=deductionsQ.data??[], ers=earningsQ.data??[], ins=installments.data??[], slips=payslips.data??[], bs=benefits.data??[], rules=countryRules.data??[];
  const employeeSelect=(name="employee_id")=><select name={name} required className="rounded-md border bg-background p-2">{es.map((e:any)=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select>;
  const periodSelect=(name="payroll_period_id")=><select name={name} required className="rounded-md border bg-background p-2">{ps.map((p:any)=><option key={p.id} value={p.id}>{p.period_start} → {p.period_end} · {p.currency} · {p.status}</option>)}</select>;
  async function openPeriod(fd:FormData){"use server";await createPayrollPeriod({period_start:String(fd.get("period_start")),period_end:String(fd.get("period_end")),currency:String(fd.get("currency")||"JOD")});}
  async function generate(fd:FormData){"use server";await createPayrollEntryFromWorkforce({payroll_period_id:String(fd.get("payroll_period_id")),employee_id:String(fd.get("employee_id")),allowances_subunits:0,overtime_subunits:0,bonuses_subunits:0,deductions_subunits:0});}
  async function status(fd:FormData){"use server";await setPayrollPeriodStatus(String(fd.get("period_id")),String(fd.get("status")) as "processing"|"locked"|"paid"|"cancelled");}
  async function earning(fd:FormData){"use server";await createPayrollEarning({employee_id:String(fd.get("employee_id")),payroll_period_id:String(fd.get("payroll_period_id")),earning_type:String(fd.get("earning_type")) as any,amount_subunits:Math.round(Number(fd.get("amount")||0)*100),currency:String(fd.get("currency")||"JOD"),source_type:String(fd.get("source_type")||"manual") as any,reason:String(fd.get("reason")||"")||undefined});}
  async function deduction(fd:FormData){"use server";await createPayrollDeduction({employee_id:String(fd.get("employee_id")),payroll_period_id:String(fd.get("payroll_period_id")),deduction_type:String(fd.get("deduction_type")),amount_subunits:Math.round(Number(fd.get("amount")||0)*100),currency:String(fd.get("currency")||"JOD"),source_type:String(fd.get("source_type")||"manual"),reason:String(fd.get("reason")||"")||undefined});}
  async function advance(fd:FormData){"use server";await createEmployeeAdvance({employee_id:String(fd.get("employee_id")),advance_type:String(fd.get("advance_type")) as any,amount_subunits:Math.round(Number(fd.get("amount")||0)*100),currency:String(fd.get("currency")||"JOD"),disbursed_on:String(fd.get("disbursed_on")),deduction_payroll_period_id:String(fd.get("deduction_period")||"")||undefined,installment_amount_subunits:Math.round(Number(fd.get("installment_amount")||0)*100)||undefined,installment_frequency:"monthly",installment_start_date:String(fd.get("installment_start")||"")||undefined,reason:String(fd.get("reason")||"")||undefined});}
  async function approve(fd:FormData){"use server";await approvePayrollEntry(String(fd.get("entry_id")));}
  async function pay(fd:FormData){"use server";await payPayrollEntry(String(fd.get("entry_id")));}
  async function payslip(fd:FormData){"use server";await issuePayrollPayslip(String(fd.get("entry_id")));}
  async function benefit(fd:FormData){"use server";await setBenefitEmployeeContribution({benefit_id:String(fd.get("benefit_id")),employee_contribution_subunits:Math.round(Number(fd.get("amount")||0)*100)});}
  return <main className="space-y-8" dir={ar?"rtl":"ltr"}><header><h1 className="text-2xl font-bold">{ar?"نواة الرواتب":"Payroll Core"}</h1><p className="text-sm text-muted-foreground">{ar?"التوظيف → الاستحقاقات والخصومات والمزايا والعمولات والسلف → المسير → القسيمة. القواعد القانونية طبقة مستقلة.":"Employment → earnings, deductions, benefits, commissions and advances → payroll → payslip. Country rules remain separate."}</p></header>
    <section className="grid gap-4 md:grid-cols-5">{[[ar?"الموظفون":"Employees",es.length],[ar?"الفترات":"Periods",ps.length],[ar?"المسيرات":"Entries",ens.length],[ar?"السلف":"Advances",ads.length],[ar?"القسائم":"Payslips",slips.length]].map(([l,v])=><div key={String(l)} className="rounded-lg border p-4"><div className="text-sm text-muted-foreground">{l}</div><div className="text-2xl font-semibold">{v}</div></div>)}</section>
    <Section title={ar?"الفترات ودورة المسير":"Payroll periods & lifecycle"}><div className="grid gap-4 lg:grid-cols-2"><form action={openPeriod} className="grid gap-2 md:grid-cols-3"><input name="period_start" type="date" required className="rounded border p-2"/><input name="period_end" type="date" required className="rounded border p-2"/><input name="currency" defaultValue="JOD" className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground md:col-span-3">{ar?"فتح فترة":"Open period"}</button></form><form action={generate} className="grid gap-2 md:grid-cols-2">{employeeSelect()}{periodSelect()}<button className="rounded bg-primary px-4 py-2 text-primary-foreground md:col-span-2">{ar?"إنشاء المسير":"Generate payroll entry"}</button></form></div><div className="space-y-2">{ps.map((p:any)=><div key={p.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-3 text-sm"><span><b>{p.period_start} → {p.period_end}</b> · {p.currency} · {p.status}</span><div className="flex flex-wrap gap-1">{(["processing","locked","paid","cancelled"] as const).map(s=><form key={s} action={status}><input type="hidden" name="period_id" value={p.id}/><input type="hidden" name="status" value={s}/><button disabled={(s==="processing"&&p.status!=="open")||(s==="locked"&&p.status!=="processing")||(s==="paid"&&p.status!=="locked"&&p.status!=="processing")||(s==="cancelled"&&!["open","processing"].includes(p.status))} className="rounded border px-2 py-1 disabled:opacity-40">{s}</button></form>)}</div></div>)}</div><div className="space-y-2">{ens.map((p:any)=><div key={p.id} className="rounded border p-3 text-sm"><div className="flex justify-between gap-2"><span><b>{p.employee?.first_name} {p.employee?.last_name}</b> · {p.status}</span><span>{(p.net_subunits/100).toFixed(2)} net</span></div><div className="mt-2 flex gap-2"><form action={approve}><input type="hidden" name="entry_id" value={p.id}/><button disabled={p.status!=="draft"} className="rounded border px-2 py-1 disabled:opacity-40">{ar?"اعتماد":"Approve"}</button></form><form action={pay}><input type="hidden" name="entry_id" value={p.id}/><button disabled={p.status!=="approved"} className="rounded border px-2 py-1 disabled:opacity-40">{ar?"دفع":"Pay"}</button></form><form action={payslip}><input type="hidden" name="entry_id" value={p.id}/><button disabled={p.status==="draft"} className="rounded border px-2 py-1 disabled:opacity-40">{ar?"قسيمة":"Payslip"}</button></form></div></div>)}</div></Section>
    <Section title={ar?"الاستحقاقات":"Earnings"}><form action={earning} className="grid gap-2 md:grid-cols-5">{employeeSelect()}{periodSelect()}<select name="earning_type" className="rounded border bg-background p-2">{earnings.map(([v,en,arx])=><option key={v} value={v}>{ar?arx:en}</option>)}</select><input name="amount" type="number" min="0.01" step="0.01" required placeholder={ar?"المبلغ":"Amount"} className="rounded border p-2"/><input name="currency" defaultValue="JOD" className="rounded border p-2"/><select name="source_type" className="rounded border bg-background p-2"><option value="manual">{ar?"يدوي":"Manual"}</option><option value="attendance">{ar?"الحضور":"Attendance"}</option><option value="leave">{ar?"الإجازة":"Leave"}</option><option value="bonus">{ar?"مكافأة":"Bonus"}</option></select><input name="reason" placeholder={ar?"السبب / المرجع":"Reason / reference"} className="rounded border p-2 md:col-span-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground md:col-span-5">{ar?"تسجيل الاستحقاق":"Record earning"}</button></form><List rows={ers} render={(x:any)=><><span>{x.employee?.first_name} {x.employee?.last_name} · {x.earning_type}</span><span>{(x.amount_subunits/100).toFixed(2)} {x.currency} · {x.status}</span></>} /></Section>
    <Section title={ar?"الخصومات":"Deductions"}><form action={deduction} className="grid gap-2 md:grid-cols-5">{employeeSelect()}{periodSelect()}<select name="deduction_type" className="rounded border bg-background p-2">{deductions.map(([v,en,arx])=><option key={v} value={v}>{ar?arx:en}</option>)}</select><input name="amount" type="number" min="0.01" step="0.01" required placeholder={ar?"المبلغ":"Amount"} className="rounded border p-2"/><input name="currency" defaultValue="JOD" className="rounded border p-2"/><select name="source_type" className="rounded border bg-background p-2"><option value="manual">{ar?"يدوي":"Manual"}</option><option value="attendance">{ar?"الحضور":"Attendance"}</option><option value="leave">{ar?"الإجازة":"Leave"}</option><option value="benefit">{ar?"منفعة":"Benefit"}</option><option value="employee_advance">{ar?"سلفة موظف":"Employee advance"}</option><option value="administrative_action">{ar?"إجراء إداري":"Administrative action"}</option><option value="country_rule">{ar?"قاعدة الدولة":"Country rule"}</option></select><input name="reason" required placeholder={ar?"السبب / المرجع":"Reason / reference"} className="rounded border p-2 md:col-span-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground md:col-span-5">{ar?"تسجيل الخصم":"Record deduction"}</button></form><List rows={ds} render={(x:any)=><><span>{x.employee?.first_name} {x.employee?.last_name} · {x.deduction_type}</span><span>{(x.amount_subunits/100).toFixed(2)} {x.currency} · {x.source_type} · {x.status}</span></>} /></Section>
    <Section title={ar?"السلف":"Advances"}><form action={advance} className="grid gap-2 md:grid-cols-5">{employeeSelect()}<select name="advance_type" className="rounded border bg-background p-2"><option value="short_term">{ar?"قصيرة الأجل":"Short-term"}</option><option value="installment">{ar?"قسط":"Installment"}</option></select><input name="amount" type="number" min="0.01" step="0.01" required placeholder={ar?"المبلغ":"Amount"} className="rounded border p-2"/><input name="currency" defaultValue="JOD" className="rounded border p-2"/><input name="disbursed_on" type="date" required className="rounded border p-2"/><select name="deduction_period" className="rounded border bg-background p-2"><option value="">{ar?"فترة قصيرة الأجل":"Short-term period"}</option>{ps.map((p:any)=><option key={p.id} value={p.id}>{p.period_start} → {p.period_end}</option>)}</select><input name="installment_amount" type="number" min="0.01" step="0.01" placeholder={ar?"قسط":"Installment"} className="rounded border p-2"/><input name="installment_start" type="date" className="rounded border p-2"/><input name="reason" placeholder={ar?"السبب":"Reason"} className="rounded border p-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground md:col-span-5">{ar?"تسجيل السلفة":"Record advance"}</button></form><List rows={ads} render={(x:any)=><><span>{x.employee?.first_name} {x.employee?.last_name} · {x.advance_type}</span><span>{(x.amount_subunits/100).toFixed(2)} {x.currency} · {x.status}</span></>} /><div className="text-sm text-muted-foreground">{ins.map((i:any)=><div key={i.id}>#{i.installment_no} · {i.due_date} · {(i.amount_subunits/100).toFixed(2)} · {i.status}{i.payroll_entry_id?" · allocated":""}</div>)}</div></Section>
    <Section title={ar?"المزايا ومساهمة الموظف":"Benefits & employee contribution"} description={ar?"مساهمة الموظف تتحول تلقائياً إلى خصم مصدره Benefit عند توليد المسير.":"Employee contribution becomes a Benefit-sourced payroll deduction when the payroll entry is generated."}>{bs.length===0?<p className="text-sm text-muted-foreground">{ar?"لا توجد مزايا نشطة.":"No active benefits."}</p>:bs.map((b:any)=><div key={b.id} className="flex flex-wrap justify-between gap-3 rounded border p-3"><span><b>{ar?(b.benefit_name_ar||b.benefit_name):b.benefit_name}</b> · {b.employee?.first_name} {b.employee?.last_name}</span><form action={benefit} className="flex gap-2"><input type="hidden" name="benefit_id" value={b.id}/><input name="amount" type="number" min="0" step="0.01" defaultValue={(b.employee_contribution_subunits/100).toFixed(2)} className="w-28 rounded border p-2"/><button className="rounded border px-3 py-2">{ar?"حفظ":"Save"}</button></form></div>)}</Section>
    <Section title={ar?"قسائم الراتب":"Payslips"}><List rows={slips} render={(x:any)=><><span>{x.employee?.first_name} {x.employee?.last_name} · {x.status}</span><span>{(x.gross_subunits/100).toFixed(2)} − {(x.deductions_subunits/100).toFixed(2)} = <b>{(x.net_subunits/100).toFixed(2)}</b> {x.currency}</span></>} /></Section>
    <Section title={ar?"قواعد البلد":"Country rules"} description={ar?"قواعد قانونية مرجعية مستقلة ولا توجد نسبة عالمية مفروضة داخل Payroll Core.":"Reference layer only; Payroll Core has no universal statutory rate."}><List rows={rules} render={(x:any)=><><span>{x.country_code} · {x.name}</span><span>{x.tax_enabled?"tax":"no tax"} · {x.social_security_enabled?"social":"no social"} · {x.effective_from}</span></>} /></Section>
  </main>;
}
function Section({title,description,children}:{title:string;description?:string;children:React.ReactNode}){return <section className="space-y-4 rounded-lg border p-5"><div><h2 className="font-semibold">{title}</h2>{description&&<p className="text-sm text-muted-foreground">{description}</p>}</div>{children}</section>}
function List({rows,render}:{rows:any[];render:(row:any)=>React.ReactNode}){return <div className="space-y-2">{rows.map((r:any)=><div key={r.id} className="flex flex-wrap justify-between gap-3 rounded border p-3 text-sm">{render(r)}</div>)}</div>}
