import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import { createClient } from "@/infrastructure/supabase/server";
import { resolveTenantId } from "@/core/auth/resolveTenantId";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import { createPayrollEntryFromWorkforce } from "@/domain/workforce/workforce.payroll.actions";
import { createEmployeeAdvance, createPayrollDeduction } from "@/domain/workforce/workforce.payroll.adjustments.actions";
import { createPayrollEarning, issuePayrollPayslip } from "@/domain/workforce/workforce.payroll.core.actions";
import { approvePayrollEntry, payPayrollEntry } from "@/domain/workforce/workforce.payroll.lifecycle.actions";
import { setBenefitEmployeeContribution } from "@/domain/workforce/workforce.payroll.benefits.actions";

const deductionTypes = [["late_arrival","Late arrival","تأخر"],["early_departure","Early departure","انصراف مبكر"],["unpaid_absence","Unpaid absence","غياب غير مدفوع"],["unpaid_leave","Unpaid leave","إجازة غير مدفوعة"],["benefit_contribution","Benefit contribution","مساهمة منفعة"],["salary_advance","Salary advance","سلفة راتب"],["loan_repayment","Loan repayment","سداد قرض"],["disciplinary","Disciplinary deduction","خصم تأديبي"],["administrative_adjustment","Administrative adjustment","تسوية إدارية"],["overpayment_recovery","Overpayment recovery","استرداد راتب زائد"],["manual_adjustment","Manual adjustment","تسوية يدوية"],["statutory_tax","Statutory tax","ضريبة قانونية"],["statutory_social_security","Social security","ضمان اجتماعي"]] as const;
const earningTypes = [["allowance","Allowance","بدل"],["overtime","Overtime","عمل إضافي"],["bonus","Bonus","مكافأة"],["other_earning","Other earning","استحقاق آخر"]] as const;

export default async function WorkforcePayrollPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const tenantId = await resolveTenantId(user.id);
  if (!tenantId) redirect("/login");
  const permissions = await getEffectivePermissions(user.id, tenantId);
  if (!permissions.includes("workforce:payroll" as never) && !permissions.includes("workforce:manage" as never)) redirect("/workforce");
  const ar = (await cookies()).get("core-system-locale")?.value === "ar";
  const [employees, periods, entries, advances, deductions, earnings, installments, payslips, benefits, countryRules] = await Promise.all([
    supabase.from("workforce_employees").select("id,first_name,last_name").eq("tenant_id", tenantId).eq("status", "active").order("first_name"),
    supabase.from("workforce_payroll_periods").select("id,period_start,period_end,status,currency").eq("tenant_id", tenantId).order("period_start", { ascending: false }).limit(12),
    supabase.from("workforce_payroll_entries").select("id,employee_id,payroll_period_id,base_salary_subunits,allowances_subunits,overtime_subunits,bonuses_subunits,commissions_subunits,deductions_subunits,net_subunits,status,approved_at,paid_at,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(30),
    supabase.from("workforce_employee_advances").select("id,employee_id,advance_type,amount_subunits,currency,disbursed_on,status,installment_amount_subunits,installment_start_date,reason,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(30),
    supabase.from("workforce_payroll_deductions").select("id,employee_id,payroll_period_id,deduction_type,amount_subunits,currency,source_type,reason,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(30),
    supabase.from("workforce_payroll_earnings").select("id,employee_id,payroll_period_id,earning_type,amount_subunits,currency,source_type,reason,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(30),
    supabase.from("workforce_advance_installments").select("id,advance_id,installment_no,due_date,amount_subunits,status,payroll_entry_id").eq("tenant_id", tenantId).order("due_date").limit(50),
    supabase.from("workforce_payslips").select("id,payroll_entry_id,employee_id,payroll_period_id,currency,gross_subunits,deductions_subunits,net_subunits,status,issued_at,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).order("issued_at", { ascending: false }).limit(30),
    supabase.from("workforce_benefits").select("id,employee_id,benefit_name,benefit_name_ar,value_subunits,employee_contribution_subunits,currency,status,starts_on,ends_on,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).eq("status", "active").order("created_at", { ascending: false }).limit(30),
    supabase.from("workforce_payroll_country_rules").select("id,country_code,name,effective_from,effective_to,tax_enabled,social_security_enabled,employee_rate,employer_rate,currency,status,source_url").is("tenant_id", null).eq("status", "active").order("country_code")
  ]);
  const employeeRows = employees.data ?? [], periodRows = periods.data ?? [], entryRows = entries.data ?? [], advanceRows = advances.data ?? [], deductionRows = deductions.data ?? [], earningRows = earnings.data ?? [], installmentRows = installments.data ?? [], payslipRows = payslips.data ?? [], benefitRows = benefits.data ?? [], countryRuleRows = countryRules.data ?? [];
  const empSelect = (name = "employee_id") => <select name={name} required className="rounded-md border bg-background p-2">{employeeRows.map((e: any) => <option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select>;
  const periodSelect = (name = "payroll_period_id") => <select name={name} required className="rounded-md border bg-background p-2">{periodRows.map((p: any) => <option key={p.id} value={p.id}>{p.period_start} → {p.period_end} · {p.currency} · {p.status}</option>)}</select>;
  async function submitPeriod(fd: FormData) { "use server"; const { createPayrollPeriod } = await import("@/domain/workforce/workforce.actions"); await createPayrollPeriod({ period_start: String(fd.get("period_start")), period_end: String(fd.get("period_end")), currency: String(fd.get("currency") || "JOD") }); }
  async function submitPayroll(fd: FormData) { "use server"; await createPayrollEntryFromWorkforce({ payroll_period_id: String(fd.get("payroll_period_id")), employee_id: String(fd.get("employee_id")), allowances_subunits: 0, overtime_subunits: 0, bonuses_subunits: 0, deductions_subunits: 0 }); }
  async function submitEarning(fd: FormData) { "use server"; await createPayrollEarning({ employee_id: String(fd.get("employee_id")), payroll_period_id: String(fd.get("payroll_period_id")), earning_type: String(fd.get("earning_type")) as "allowance" | "overtime" | "bonus" | "other_earning", amount_subunits: Math.round(Number(fd.get("amount") || 0) * 100), currency: String(fd.get("currency") || "JOD"), source_type: String(fd.get("source_type") || "manual") as "attendance" | "leave" | "bonus" | "manual", reason: String(fd.get("reason") || "") || undefined }); }
  async function submitAdvance(fd: FormData) { "use server"; await createEmployeeAdvance({ employee_id: String(fd.get("employee_id")), advance_type: String(fd.get("advance_type")) as "short_term" | "installment", amount_subunits: Math.round(Number(fd.get("amount") || 0) * 100), currency: String(fd.get("currency") || "JOD"), disbursed_on: String(fd.get("disbursed_on")), deduction_payroll_period_id: String(fd.get("deduction_payroll_period_id") || "") || undefined, installment_amount_subunits: Math.round(Number(fd.get("installment_amount") || 0) * 100) || undefined, installment_frequency: "monthly", installment_start_date: String(fd.get("installment_start_date") || "") || undefined, reason: String(fd.get("reason") || "") || undefined }); }
  async function submitDeduction(fd: FormData) { "use server"; await createPayrollDeduction({ employee_id: String(fd.get("employee_id")), payroll_period_id: String(fd.get("payroll_period_id")), deduction_type: String(fd.get("deduction_type")), amount_subunits: Math.round(Number(fd.get("amount") || 0) * 100), currency: String(fd.get("currency") || "JOD"), source_type: String(fd.get("source_type") || "manual"), reason: String(fd.get("reason") || "") || undefined }); }
  async function approve(fd: FormData) { "use server"; await approvePayrollEntry(String(fd.get("entry_id"))); }
  async function pay(fd: FormData) { "use server"; await payPayrollEntry(String(fd.get("entry_id"))); }
  async function payslip(fd: FormData) { "use server"; await issuePayrollPayslip(String(fd.get("entry_id"))); }
  async function benefitContribution(fd: FormData) { "use server"; await setBenefitEmployeeContribution({ benefit_id: String(fd.get("benefit_id")), employee_contribution_subunits: Math.round(Number(fd.get("amount") || 0) * 100) }); }
  return <main className="space-y-8" dir={ar ? "rtl" : "ltr"}>
    <header><h1 className="text-2xl font-bold">{ar ? "نواة الرواتب" : "Payroll Core"}</h1><p className="mt-1 text-sm text-muted-foreground">{ar ? "التوظيف الفعال ← الاستحقاقات والخصومات والمزايا والعمولات والسلف ← المسير ← قسيمة الراتب. القواعد القانونية طبقة منفصلة." : "Effective employment → earnings, deductions, benefits, commissions and advances → payroll → payslip. Legal rules remain a separate layer."}</p></header>

    <section className="grid gap-4 md:grid-cols-5">{[[ar?"الموظفون":"Employees",employeeRows.length],[ar?"الفترات":"Periods",periodRows.length],[ar?"المسيرات":"Entries",entryRows.length],[ar?"السلف":"Advances",advanceRows.length],[ar?"قسائم الراتب":"Payslips",payslipRows.length]].map(([l,v])=><div key={String(l)} className="rounded-lg border p-4"><div className="text-sm text-muted-foreground">{l}</div><div className="mt-1 text-2xl font-semibold">{v}</div></div>)}</section>

    <Section title={ar ? "الفترات ودورة المسير" : "Payroll periods & run"} description={ar ? "افتح الفترة، أنشئ مسير الموظف من سجل التوظيف الفعال، ثم اعتماد ← دفع. لا يمكن الدفع قبل الاعتماد." : "Open a period, generate from the effective employment record, then approve → pay. Payment is blocked until approval."}>
      <div className="grid gap-6 lg:grid-cols-2"><form action={submitPeriod} className="grid gap-2 md:grid-cols-3"><input name="period_start" type="date" required className="rounded-md border p-2"/><input name="period_end" type="date" required className="rounded-md border p-2"/><input name="currency" defaultValue="JOD" className="rounded-md border p-2"/><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground md:col-span-3">{ar?"فتح فترة":"Open period"}</button></form><form action={submitPayroll} className="grid gap-2 md:grid-cols-2">{empSelect()}{periodSelect()}<button className="rounded-md bg-primary px-4 py-2 text-primary-foreground md:col-span-2">{ar?"إنشاء المسير":"Generate payroll entry"}</button></form></div>
      <div className="space-y-2">{entryRows.map((p:any)=><div key={p.id} className="rounded border p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><span><b>{p.employee?.first_name} {p.employee?.last_name}</b> · {p.status}</span><span>{(p.net_subunits/100).toFixed(2)} net</span></div><div className="mt-2 flex flex-wrap gap-2"><form action={approve}><input type="hidden" name="entry_id" value={p.id}/><button disabled={p.status!=="draft"} className="rounded border px-2 py-1 disabled:opacity-40">{ar?"اعتماد":"Approve"}</button></form><form action={pay}><input type="hidden" name="entry_id" value={p.id}/><button disabled={p.status!=="approved"} className="rounded border px-2 py-1 disabled:opacity-40">{ar?"دفع":"Mark paid"}</button></form><form action={payslip}><input type="hidden" name="entry_id" value={p.id}/><button disabled={p.status==="draft"} className="rounded border px-2 py-1 disabled:opacity-40">{ar?"إصدار قسيمة":"Issue payslip"}</button></form></div></div>)}</div>
    </Section>

    <Section title={ar ? "الاستحقاقات" : "Earnings"} description={ar ? "بدلات، عمل إضافي، مكافآت واستحقاقات أخرى محفوظة كسجلات مستقلة، ثم تُجمع داخل المسير." : "Allowances, overtime, bonuses and other earnings are normalized records and then aggregated into payroll."}>
      <form action={submitEarning} className="grid gap-2 md:grid-cols-5">{empSelect()}{periodSelect()}<select name="earning_type" className="rounded-md border bg-background p-2">{earningTypes.map(([v,en,arLabel])=><option key={v} value={v}>{ar?arLabel:en}</option>)}</select><input name="amount" type="number" min="0.01" step="0.01" required placeholder={ar?"المبلغ":"Amount"} className="rounded-md border p-2"/><input name="currency" defaultValue="JOD" className="rounded-md border p-2"/><select name="source_type" className="rounded-md border bg-background p-2"><option value="manual">{ar?"يدوي":"Manual"}</option><option value="attendance">{ar?"الحضور":"Attendance"}</option><option value="leave">{ar?"الإجازة":"Leave"}</option><option value="bonus">{ar?"مكافأة":"Bonus"}</option></select><input name="reason" placeholder={ar?"السبب / المرجع":"Reason / reference"} className="rounded-md border p-2 md:col-span-2"/><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground md:col-span-5">{ar?"تسجيل الاستحقاق":"Record earning"}</button></form><List rows={earningRows} render={(e:any)=><><span>{e.employee?.first_name} {e.employee?.last_name} · {e.earning_type}</span><span>{(e.amount_subunits/100).toFixed(2)} {e.currency} · {e.status}</span></>} />
    </Section>

    <Section title={ar ? "الخصومات" : "Deductions"} description={ar ? "يشمل الخصم التأخر والانصراف المبكر والغياب والإجازة غير المدفوعة والمزايا والسلف والقروض والتأديبي والتسويات والاسترداد والخصومات القانونية." : "Includes lateness, early departure, unpaid absence/leave, benefits, advances, loans, disciplinary/admin adjustments, recovery and statutory deductions."}>
      <form action={submitDeduction} className="grid gap-2 md:grid-cols-5">{empSelect()}{periodSelect()}<select name="deduction_type" required className="rounded-md border bg-background p-2">{deductionTypes.map(([v,en,arLabel])=><option key={v} value={v}>{ar?arLabel:en}</option>)}</select><input name="amount" type="number" min="0.01" step="0.01" required placeholder={ar?"المبلغ":"Amount"} className="rounded-md border p-2"/><input name="currency" defaultValue="JOD" className="rounded-md border p-2"/><select name="source_type" className="rounded-md border bg-background p-2"><option value="manual">{ar?"يدوي":"Manual"}</option><option value="attendance">{ar?"الحضور":"Attendance"}</option><option value="leave">{ar?"الإجازة":"Leave"}</option><option value="benefit">{ar?"المزايا":"Benefit"}</option><option value="employee_advance">{ar?"سلفة موظف":"Employee advance"}</option><option value="administrative_action">{ar?"إجراء إداري":"Administrative action"}</option><option value="country_rule">{ar?"قاعدة بلد":"Country rule"}</option></select><input name="reason" required placeholder={ar?"السبب / المرجع":"Reason / reference"} className="rounded-md border p-2 md:col-span-2"/><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground md:col-span-5">{ar?"تسجيل الخصم":"Record deduction"}</button></form><List rows={deductionRows} render={(d:any)=><><span>{d.employee?.first_name} {d.employee?.last_name} · {d.deduction_type}</span><span>{(d.amount_subunits/100).toFixed(2)} {d.currency} · {d.source_type} · {d.status}</span></>} />
    </Section>

    <Section title={ar ? "السلف" : "Employee advances"} description={ar ? "كيان واحد بسلوكين: قصيرة الأجل تخصم كاملة في فترة محددة، أو تقسيط شهري مع تخفيض القسط الأخير تلقائياً." : "One entity with two behaviors: short-term full deduction in a selected period, or monthly installments with the final installment reduced to the remaining balance."}>
      <form action={submitAdvance} className="grid gap-2 md:grid-cols-5">{empSelect()}<select name="advance_type" className="rounded-md border bg-background p-2"><option value="short_term">{ar?"قصيرة الأجل":"Short-term"}</option><option value="installment">{ar?"تقسيط":"Installment"}</option></select><input name="amount" type="number" min="0.01" step="0.01" required placeholder={ar?"المبلغ":"Amount"} className="rounded-md border p-2"/><input name="currency" defaultValue="JOD" className="rounded-md border p-2"/><input name="disbursed_on" type="date" required className="rounded-md border p-2"/><select name="deduction_payroll_period_id" className="rounded-md border bg-background p-2"><option value="">{ar?"فترة السلفة القصيرة":"Short-term payroll period"}</option>{periodRows.map((p:any)=><option key={p.id} value={p.id}>{p.period_start} → {p.period_end}</option>)}</select><input name="installment_amount" type="number" min="0.01" step="0.01" placeholder={ar?"قيمة القسط":"Installment amount"} className="rounded-md border p-2"/><input name="installment_start_date" type="date" className="rounded-md border p-2"/><input name="reason" placeholder={ar?"السبب":"Reason"} className="rounded-md border p-2"/><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground md:col-span-5">{ar?"تسجيل السلفة":"Record advance"}</button></form><List rows={advanceRows} render={(a:any)=><><span>{a.employee?.first_name} {a.employee?.last_name} · {a.advance_type}</span><span>{(a.amount_subunits/100).toFixed(2)} {a.currency} · {a.status}</span></>} />
    </Section>

    <Section title={ar ? "المزايا ومساهمة الموظف" : "Benefits & employee contribution"} description={ar ? "مساهمة الموظف في الميزة تُسجل على الميزة نفسها، ويحوّلها توليد المسير تلقائياً إلى خصم مصدره Benefit للفترة." : "Employee contribution is stored on the benefit and payroll generation automatically creates the period deduction with Benefit as its source."}>
      {benefitRows.length===0?<p className="text-sm text-muted-foreground">{ar?"لا توجد مزايا نشطة حالياً.":"No active benefits currently."}</p>:benefitRows.map((b:any)=><div key={b.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3"><span><b>{ar?(b.benefit_name_ar||b.benefit_name):b.benefit_name}</b> · {b.employee?.first_name} {b.employee?.last_name}</span><form action={benefitContribution} className="flex gap-2"><input type="hidden" name="benefit_id" value={b.id}/><input name="amount" type="number" min="0" step="0.01" defaultValue={(b.employee_contribution_subunits/100).toFixed(2)} className="w-28 rounded border p-2"/><button className="rounded border px-3 py-2">{ar?"حفظ مساهمة الموظف":"Save employee cost"}</button></form></div>)}
    </Section>

    <Section title={ar ? "الأقساط" : "Advance installments"}>{installmentRows.length===0?<p className="text-sm text-muted-foreground">{ar?"لا توجد أقساط.":"No installments."}</p>:installmentRows.map((i:any)=><div key={i.id} className="text-sm">#{i.installment_no} · {i.due_date} · {(i.amount_subunits/100).toFixed(2)} · {i.status}{i.payroll_entry_id?" · allocated":""}</div>)}</Section>

    <Section title={ar ? "قسائم الراتب" : "Payslips"}>{payslipRows.length===0?<p className="text-sm text-muted-foreground">{ar?"لم تصدر قسائم بعد.":"No payslips issued yet."}</p>:<List rows={payslipRows} render={(p:any)=><><span>{p.employee?.first_name} {p.employee?.last_name} · {p.status}</span><span>{(p.gross_subunits/100).toFixed(2)} gross − {(p.deductions_subunits/100).toFixed(2)} = <b>{(p.net_subunits/100).toFixed(2)}</b> {p.currency}</span></>} />}</Section>

    <Section title={ar ? "قواعد البلد" : "Country rules"} description={ar ? "طبقة مرجعية عالمية مستقلة. لا تُفرض نسبة ضريبية عالمية على Payroll Core." : "Global reference layer kept separate from the country-neutral payroll core. No universal tax rate is hard-coded."}>{countryRuleRows.length===0?<p className="text-sm text-muted-foreground">{ar?"لا توجد قواعد عامة نشطة.":"No active global rules."}</p>:<List rows={countryRuleRows} render={(r:any)=><><span>{r.country_code} · {r.name}</span><span>{r.tax_enabled?"tax":"no tax"} · {r.social_security_enabled?"social security":"no social security"} · {r.effective_from}{r.effective_to?` → ${r.effective_to}`:""}</span></>} />}</Section>
  </main>;
}

function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="space-y-4 rounded-lg border p-5"><div><h2 className="font-semibold">{title}</h2>{description&&<p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{children}</section>; }
function List({ rows, render }: { rows: any[]; render: (row: any) => React.ReactNode }) { return <div className="space-y-2">{rows.map((row:any)=><div key={row.id} className="flex flex-wrap justify-between gap-3 rounded border p-3 text-sm">{render(row)}</div>)}</div>; }
