import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import { createClient } from "@/infrastructure/supabase/server";
import { resolveTenantId } from "@/core/auth/resolveTenantId";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import { createPayrollEntryFromWorkforce } from "@/domain/workforce/workforce.payroll.actions";
import { createEmployeeAdvance, createPayrollDeduction } from "@/domain/workforce/workforce.payroll.adjustments.actions";

const deductionTypes = [["late_arrival","Late arrival","تأخر"],["early_departure","Early departure","انصراف مبكر"],["unpaid_absence","Unpaid absence","غياب غير مدفوع"],["unpaid_leave","Unpaid leave","إجازة غير مدفوعة"],["benefit_contribution","Benefit contribution","مساهمة منفعة"],["disciplinary","Disciplinary deduction","خصم تأديبي"],["administrative_adjustment","Administrative adjustment","تسوية إدارية"],["overpayment_recovery","Overpayment recovery","استرداد راتب زائد"],["manual_adjustment","Manual adjustment","تسوية يدوية"],["statutory_tax","Statutory tax","ضريبة قانونية"],["statutory_social_security","Social security","ضمان اجتماعي"]] as const;

export default async function WorkforcePayrollPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const tenantId = await resolveTenantId(user.id);
  if (!tenantId) redirect("/login");
  const permissions = await getEffectivePermissions(user.id, tenantId);
  if (!permissions.includes("workforce:payroll" as never) && !permissions.includes("workforce:manage" as never)) redirect("/workforce");
  const ar = (await cookies()).get("core-system-locale")?.value === "ar";
  const [employees, periods, entries, advances, deductions, installments] = await Promise.all([
    supabase.from("workforce_employees").select("id,first_name,last_name").eq("tenant_id", tenantId).eq("status", "active").order("first_name"),
    supabase.from("workforce_payroll_periods").select("id,period_start,period_end,status,currency").eq("tenant_id", tenantId).order("period_start", { ascending: false }).limit(12),
    supabase.from("workforce_payroll_entries").select("id,employee_id,payroll_period_id,base_salary_subunits,allowances_subunits,overtime_subunits,bonuses_subunits,commissions_subunits,deductions_subunits,net_subunits,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(30),
    supabase.from("workforce_employee_advances").select("id,employee_id,advance_type,amount_subunits,currency,disbursed_on,status,installment_amount_subunits,installment_start_date,reason,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(30),
    supabase.from("workforce_payroll_deductions").select("id,employee_id,payroll_period_id,deduction_type,amount_subunits,currency,source_type,reason,status,employee:workforce_employees(first_name,last_name)").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(30),
    supabase.from("workforce_advance_installments").select("id,advance_id,installment_no,due_date,amount_subunits,status").eq("tenant_id", tenantId).order("due_date").limit(50),
  ]);
  const employeeRows = employees.data ?? [], periodRows = periods.data ?? [], entryRows = entries.data ?? [], advanceRows = advances.data ?? [], deductionRows = deductions.data ?? [], installmentRows = installments.data ?? [];
  const empSelect = (name = "employee_id") => <select name={name} required className="rounded-md border bg-background p-2">{employeeRows.map((e: any) => <option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select>;
  async function submitPayroll(fd: FormData) { "use server"; await createPayrollEntryFromWorkforce({ payroll_period_id: String(fd.get("payroll_period_id")), employee_id: String(fd.get("employee_id")), allowances_subunits: Math.round(Number(fd.get("allowances") || 0) * 100), overtime_subunits: Math.round(Number(fd.get("overtime") || 0) * 100), bonuses_subunits: Math.round(Number(fd.get("bonuses") || 0) * 100), deductions_subunits: 0 }); }
  async function submitAdvance(fd: FormData) { "use server"; await createEmployeeAdvance({ employee_id: String(fd.get("employee_id")), advance_type: String(fd.get("advance_type")) as "short_term" | "installment", amount_subunits: Math.round(Number(fd.get("amount") || 0) * 100), currency: String(fd.get("currency") || "JOD"), disbursed_on: String(fd.get("disbursed_on")), deduction_payroll_period_id: String(fd.get("deduction_payroll_period_id") || "") || undefined, installment_amount_subunits: Math.round(Number(fd.get("installment_amount") || 0) * 100) || undefined, installment_frequency: "monthly", installment_start_date: String(fd.get("installment_start_date" || "")) || undefined, reason: String(fd.get("reason") || "") || undefined }); }
  async function submitDeduction(fd: FormData) { "use server"; await createPayrollDeduction({ employee_id: String(fd.get("employee_id")), payroll_period_id: String(fd.get("payroll_period_id")), deduction_type: String(fd.get("deduction_type")), amount_subunits: Math.round(Number(fd.get("amount") || 0) * 100), currency: String(fd.get("currency") || "JOD"), source_type: String(fd.get("source_type") || "manual"), reason: String(fd.get("reason") || "") || undefined }); }
  return <main className="space-y-8" dir={ar ? "rtl" : "ltr"}>
    <header><h1 className="text-2xl font-bold">{ar ? "الرواتب والسلف والخصومات" : "Payroll, Advances & Deductions"}</h1><p className="mt-1 text-sm text-muted-foreground">{ar ? "نواة الرواتب العملية: الاستحقاقات، العمولات، السلف، الخصومات وسجل قابل للتتبع." : "Practical payroll core: earnings, commissions, advances, deductions and traceable payroll inputs."}</p></header>
    <section className="rounded-lg border p-5 space-y-4"><h2 className="font-semibold">{ar ? "إنشاء مسير" : "Generate payroll"}</h2><p className="text-sm text-muted-foreground">{ar ? "الراتب الأساسي والعمولات المعتمدة والخصومات المسجلة والسلف المستحقة تُحسب من بيانات النظام. لا تدخل الخصومات يدويًا هنا." : "Base salary, approved commissions, recorded deductions and due advance installments are derived from Workforce data. Do not enter deductions manually here."}</p><form action={submitPayroll} className="grid gap-2 md:grid-cols-5">{empSelect()}<select name="payroll_period_id" required className="rounded-md border bg-background p-2">{periodRows.map((p: any) => <option key={p.id} value={p.id}>{p.period_start} → {p.period_end} · {p.currency}</option>)}</select><input name="allowances" type="number" min="0" step="0.01" placeholder={ar ? "بدلات" : "Allowances"} className="rounded-md border p-2"/><input name="overtime" type="number" min="0" step="0.01" placeholder={ar ? "إضافي" : "Overtime"} className="rounded-md border p-2"/><input name="bonuses" type="number" min="0" step="0.01" placeholder={ar ? "مكافآت" : "Bonuses"} className="rounded-md border p-2"/><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground md:col-span-5">{ar ? "إنشاء المسير" : "Generate payroll entry"}</button></form></section>
    <section className="rounded-lg border p-5 space-y-4"><h2 className="font-semibold">{ar ? "السلف" : "Employee advances"}</h2><p className="text-sm text-muted-foreground">{ar ? "نوع واحد للكيان، بسلوكين: سلفة قصيرة الأجل تخصم كاملة من راتب الفترة المحددة، أو سلفة بالتقسيط تُنشئ جدول أقساط شهري." : "One advance entity with two behaviors: short-term is deducted in full from the selected payroll period; installment creates a monthly repayment schedule."}</p><form action={submitAdvance} className="grid gap-2 md:grid-cols-4">{empSelect()}<select name="advance_type" className="rounded-md border bg-background p-2"><option value="short_term">{ar ? "سلفة قصيرة الأجل" : "Short-term advance"}</option><option value="installment">{ar ? "سلفة بالتقسيط" : "Installment advance"}</option></select><input name="amount" type="number" min="0.01" step="0.01" required placeholder={ar ? "المبلغ" : "Amount"} className="rounded-md border p-2"/><input name="currency" defaultValue="JOD" className="rounded-md border p-2"/><input name="disbursed_on" type="date" required className="rounded-md border p-2"/><select name="deduction_payroll_period_id" className="rounded-md border bg-background p-2"><option value="">{ar ? "فترة الخصم للسلفة القصيرة" : "Short-term deduction period"}</option>{periodRows.map((p: any) => <option key={p.id} value={p.id}>{p.period_start} → {p.period_end}</option>)}</select><input name="installment_amount" type="number" min="0.01" step="0.01" placeholder={ar ? "قيمة القسط (للتقسيط)" : "Installment amount"} className="rounded-md border p-2"/><input name="installment_start_date" type="date" placeholder={ar ? "بداية الأقساط" : "Installment start"} className="rounded-md border p-2"/><input name="reason" placeholder={ar ? "السبب" : "Reason"} className="rounded-md border p-2 md:col-span-2"/><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground md:col-span-4">{ar ? "تسجيل السلفة" : "Record advance"}</button></form><div className="space-y-2">{advanceRows.map((a: any) => <div key={a.id} className="rounded border p-3 text-sm"><b>{a.employee?.first_name} {a.employee?.last_name}</b> · {a.advance_type === "short_term" ? (ar ? "قصيرة الأجل" : "Short-term") : (ar ? "تقسيط" : "Installment")} · {(a.amount_subunits / 100).toFixed(2)} {a.currency} · {a.status}{a.advance_type === "installment" ? ` · ${(a.installment_amount_subunits / 100).toFixed(2)} / month` : ""}</div>)}</div></section>
    <section className="rounded-lg border p-5 space-y-4"><h2 className="font-semibold">{ar ? "الخصومات" : "Payroll deductions"}</h2><p className="text-sm text-muted-foreground">{ar ? "كل خصم له نوع ومصدر وسبب وفترة راتب. لا توجد خصومات صامتة." : "Every deduction has a type, source, reason and payroll period. No silent deductions."}</p><form action={submitDeduction} className="grid gap-2 md:grid-cols-4">{empSelect()}<select name="payroll_period_id" required className="rounded-md border bg-background p-2">{periodRows.map((p: any) => <option key={p.id} value={p.id}>{p.period_start} → {p.period_end}</option>)}</select><select name="deduction_type" required className="rounded-md border bg-background p-2">{deductionTypes.map(([v,en,arLabel]) => <option key={v} value={v}>{ar ? arLabel : en}</option>)}</select><input name="amount" type="number" min="0.01" step="0.01" required placeholder={ar ? "المبلغ" : "Amount"} className="rounded-md border p-2"/><select name="source_type" className="rounded-md border bg-background p-2"><option value="manual">{ar ? "تعديل يدوي" : "Manual"}</option><option value="attendance">{ar ? "الحضور" : "Attendance"}</option><option value="leave">{ar ? "الإجازة" : "Leave"}</option><option value="benefit">{ar ? "المزايا" : "Benefit"}</option><option value="administrative_action">{ar ? "إجراء إداري" : "Administrative action"}</option><option value="country_rule">{ar ? "قاعدة بلد" : "Country rule"}</option></select><input name="currency" defaultValue="JOD" className="rounded-md border p-2"/><input name="reason" required placeholder={ar ? "السبب / المرجع" : "Reason / reference"} className="rounded-md border p-2 md:col-span-2"/><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground md:col-span-4">{ar ? "تسجيل الخصم" : "Record deduction"}</button></form><div className="space-y-2">{deductionRows.map((d: any) => <div key={d.id} className="rounded border p-3 text-sm"><b>{d.employee?.first_name} {d.employee?.last_name}</b> · {d.deduction_type} · {(d.amount_subunits / 100).toFixed(2)} {d.currency} · {d.source_type} · {d.status}{d.reason ? ` · ${d.reason}` : ""}</div>)}</div></section>
    <section className="rounded-lg border p-5 space-y-3"><h2 className="font-semibold">{ar ? "الأقساط القادمة" : "Upcoming installments"}</h2>{installmentRows.length === 0 ? <p className="text-sm text-muted-foreground">{ar ? "لا توجد أقساط حالية." : "No installments currently scheduled."}</p> : installmentRows.map((i: any) => <div key={i.id} className="text-sm">#{i.installment_no} · {i.due_date} · {(i.amount_subunits / 100).toFixed(2)} · {i.status}</div>)}</section>
    <section className="rounded-lg border p-5 space-y-2"><h2 className="font-semibold">{ar ? "سجل الرواتب" : "Payroll entries"}</h2>{entryRows.map((p: any) => <div key={p.id} className="flex justify-between border-b py-2 text-sm"><span>{p.employee?.first_name} {p.employee?.last_name}</span><span>{(p.base_salary_subunits / 100).toFixed(2)} + {(p.commissions_subunits / 100).toFixed(2)} commission − {(p.deductions_subunits / 100).toFixed(2)} deductions = <b>{(p.net_subunits / 100).toFixed(2)}</b> · {p.status}</span></div>)}</section>
  </main>;
}
