"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Button } from "@/shared/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Input } from "@/shared/components/ui/input";
import { Label } from "@/shared/components/ui/label";
import { Badge } from "@/shared/components/ui/badge";
import { createFinancialPlan, createInsuranceProfile, createPurchaseOrder, createSupplier } from "@/domain/financial-resources/financial-resources.actions";
import { recordPayment } from "@/domain/invoicing/invoicing.actions";
import type { PaymentMethod } from "@/domain/invoicing/invoicing.types";
import { getFinancialResourcesMessages } from "@/core/i18n/financialResourcesMessages";
import type { Permission } from "@/core/permissions/types";

export type PatientSummary = { id: string; first_name: string; last_name: string; phone_primary: string };
export type SupplierSummary = { id: string; name: string; phone: string | null; email: string | null };
export type PurchaseOrderSummary = { id: string; order_number: string | null; order_date: string; status: string; total_subunits: number; supplier: { id: string; name: string } | null };
export type InventoryItemSummary = { id: string; name: string; current_stock: number; unit: string };
export type FinancialPlanSummary = { id: string; patient_id: string; total_amount_subunits: number; patient_responsibility_subunits: number; insurance_covered_subunits: number; status: string; installments: { id: string; installment_no: number; due_date: string; amount_subunits: number; amount_paid_subunits: number; status: string }[] };
export type InsuranceSummary = { id: string; patient_id: string; payer_name: string; policy_number: string | null; member_number: string | null; claim_ready: boolean; status: string; reconciliation_status: string };
export type InvoiceSummary = { id: string; invoice_number: string | null; invoice_date: string; invoice_status: string; patient_id: string; total_subunits: number; amount_paid_subunits: number; amount_due_subunits: number | null };
interface Props { locale: "ar" | "en"; patients: PatientSummary[]; plans: FinancialPlanSummary[]; insurance: InsuranceSummary[]; suppliers: SupplierSummary[]; purchaseOrders: PurchaseOrderSummary[]; inventoryItems: InventoryItemSummary[]; invoices: InvoiceSummary[]; permissions: Permission[]; currency: string; activeSection?: string; }

export function FinancialResourcesCenter({ locale, patients, plans, insurance, suppliers, purchaseOrders, inventoryItems, invoices, permissions, currency, activeSection }: Props) {
  const t = getFinancialResourcesMessages(locale); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [patientId, setPatientId] = useState(patients[0]?.id ?? ""); const [total, setTotal] = useState(""); const [insuranceCovered, setInsuranceCovered] = useState("0"); const [installmentCount, setInstallmentCount] = useState("1"); const [payerName, setPayerName] = useState(""); const [policyNumber, setPolicyNumber] = useState(""); const [memberNumber, setMemberNumber] = useState(""); const [supplierName, setSupplierName] = useState(""); const [supplierPhone, setSupplierPhone] = useState(""); const [supplierEmail, setSupplierEmail] = useState(""); const [supplierId, setSupplierId] = useState(suppliers[0]?.id ?? ""); const [inventoryItemId, setInventoryItemId] = useState(inventoryItems[0]?.id ?? ""); const [purchaseQuantity, setPurchaseQuantity] = useState("1"); const [unitCost, setUnitCost] = useState(""); const [paymentInvoiceId, setPaymentInvoiceId] = useState(invoices[0]?.id ?? ""); const [paymentAmount, setPaymentAmount] = useState(""); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>("cash"); const [paymentReference, setPaymentReference] = useState("");
  const patientName = useMemo(() => Object.fromEntries(patients.map((p) => [p.id, `${p.first_name} ${p.last_name}`.trim()])), [patients]); const canPlan = permissions.includes("invoices:update"); const canInsurance = permissions.includes("insurance:manage"); const canPurchasing = permissions.includes("purchasing:manage"); const canPayment = permissions.includes("invoices:payment");
  function money(v: number) { return new Intl.NumberFormat(locale === "ar" ? "ar" : "en", { style: "currency", currency, maximumFractionDigits: 2 }).format(v / 100); }
  const show = (name: string) => !activeSection || activeSection === name;
  async function submitPlan(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(null); const totalSubunits = Math.round(Number(total) * 100); const insuranceSubunits = Math.round(Number(insuranceCovered) * 100); const count = Math.max(1, Number.parseInt(installmentCount, 10) || 1); const responsibility = totalSubunits - insuranceSubunits; const today = new Date(); const per = Math.floor(responsibility / count); const remainder = responsibility - per * count; const installments = Array.from({ length: count }, (_, index) => { const date = new Date(today); date.setMonth(date.getMonth() + index); return { installment_no: index + 1, due_date: date.toISOString().slice(0, 10), amount_subunits: per + (index === count - 1 ? remainder : 0) }; }); const result = await createFinancialPlan({ patient_id: patientId, total_amount_subunits: totalSubunits, insurance_covered_subunits: insuranceSubunits, patient_responsibility_subunits: responsibility, currency, installments }); setBusy(false); setMessage(result.success ? t.success : result.error); if (result.success) window.location.reload(); }
  async function submitInsurance(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(null); const result = await createInsuranceProfile({ patient_id: patientId, payer_name: payerName, policy_number: policyNumber || null, member_number: memberNumber || null, claim_ready: false }); setBusy(false); setMessage(result.success ? t.success : result.error); if (result.success) window.location.reload(); }
  async function submitSupplier(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(null); const result = await createSupplier({ name: supplierName, phone: supplierPhone || null, email: supplierEmail || null }); setBusy(false); setMessage(result.success ? t.success : result.error); if (result.success) window.location.reload(); }
  async function submitPurchaseOrder(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(null); const result = await createPurchaseOrder({ supplier_id: supplierId, items: [{ inventory_item_id: inventoryItemId, quantity_ordered: Number.parseInt(purchaseQuantity, 10) || 1, unit_cost_subunits: Math.round(Number(unitCost) * 100) }] }); setBusy(false); setMessage(result.success ? t.success : result.error); if (result.success) window.location.reload(); }
  async function submitPayment(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(null); const result = await recordPayment({ invoice_id: paymentInvoiceId, amount_subunits: Math.round(Number(paymentAmount) * 100), payment_method: paymentMethod, reference_number: paymentReference || null }); setBusy(false); setMessage(result.success ? t.success : result.error); if (result.success) window.location.reload(); }
  const section = (title: string, children: React.ReactNode) => <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-4">{children}</CardContent></Card>;
  return <div className="space-y-6" dir={locale === "ar" ? "rtl" : "ltr"}>
    {message && <div className="rounded-md border bg-white p-3 text-sm">{message}</div>}
    {!activeSection && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card><CardHeader><CardTitle>{t.financialPlans}</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{plans.length}</div><p className="text-sm text-muted-foreground">{t.installments}: {plans.reduce((n, p) => n + p.installments.length, 0)}</p></CardContent></Card><Card><CardHeader><CardTitle>{t.insurance}</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{insurance.length}</div></CardContent></Card><Card><CardHeader><CardTitle>{t.suppliers}</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{suppliers.length}</div></CardContent></Card><Card><CardHeader><CardTitle>{t.purchasing}</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{purchaseOrders.length}</div></CardContent></Card></div>}
    {show("payments") && section(t.payments, <>{canPayment && invoices.length > 0 ? <form onSubmit={submitPayment} className="grid gap-3"><div><Label>{t.invoice}</Label><select className="mt-1 w-full rounded-md border p-2" value={paymentInvoiceId} onChange={(e) => setPaymentInvoiceId(e.target.value)}>{invoices.map((i) => <option key={i.id} value={i.id}>{i.invoice_number || i.id.slice(0, 8)} · {patientName[i.patient_id] || t.patient} · {money(i.amount_due_subunits ?? Math.max(i.total_subunits - i.amount_paid_subunits, 0))}</option>)}</select></div><div className="grid gap-3 sm:grid-cols-3"><Input type="number" min="0.01" step="0.01" value={paymentAmount} onChange={(e) => setPaymentAmount(e.target.value)} placeholder={t.amount} required /><select className="rounded-md border p-2" value={paymentMethod} onChange={(e) => setPaymentMethod(e.target.value as PaymentMethod)}><option value="cash">{t.cash}</option><option value="card">{t.card}</option><option value="bank_transfer">{t.bankTransfer}</option><option value="insurance">{t.insurance}</option><option value="online">{t.online}</option><option value="other">{t.other}</option></select><Input value={paymentReference} onChange={(e) => setPaymentReference(e.target.value)} placeholder={t.reference} /></div><Button disabled={busy}>{busy ? t.loading : t.recordPayment}</Button></form> : <p className="text-sm text-muted-foreground">{invoices.length === 0 ? t.noInvoices : t.permissionDenied}</p>}{invoices.slice(0, 20).map((i) => <div key={i.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{i.invoice_number || t.invoice}</p><p className="text-sm text-muted-foreground">{patientName[i.patient_id] || t.patient} · {i.invoice_date}</p></div><span className="text-sm">{money(i.amount_paid_subunits)} / {money(i.total_subunits)}</span></div>)}</>)}
    {show("financial-plans") && section(t.newPlan, <form onSubmit={submitPlan} className="grid gap-4">{canPlan ? <><div><Label>{t.patient}</Label><select className="mt-1 w-full rounded-md border p-2" value={patientId} onChange={(e) => setPatientId(e.target.value)} required>{patients.map((p) => <option key={p.id} value={p.id}>{patientName[p.id] || t.choosePatient}</option>)}</select></div><div className="grid gap-3 sm:grid-cols-3"><div><Label>{t.total}</Label><Input type="number" min="0" step="0.01" value={total} onChange={(e) => setTotal(e.target.value)} required /></div><div><Label>{t.insuranceCovered}</Label><Input type="number" min="0" step="0.01" value={insuranceCovered} onChange={(e) => setInsuranceCovered(e.target.value)} /></div><div><Label>{t.installmentsCount}</Label><Input type="number" min="1" max="24" value={installmentCount} onChange={(e) => setInstallmentCount(e.target.value)} /></div></div><Button disabled={busy}>{busy ? t.loading : t.create}</Button></> : <p className="text-sm text-muted-foreground">{t.permissionDenied}</p>}</form>)}
    {show("installments") && section(t.installments, plans.length === 0 ? <p className="text-sm text-muted-foreground">{t.noPlans}</p> : plans.flatMap((p) => p.installments.map((i) => <div key={i.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{patientName[p.patient_id] || t.patient} · {t.installments} #{i.installment_no}</p><p className="text-sm text-muted-foreground">{i.due_date} · {i.status}</p></div><span>{money(i.amount_paid_subunits)} / {money(i.amount_subunits)}</span></div>)))}
    {show("insurance") && section(t.insurance, <>{canInsurance && patients.length > 0 && <form onSubmit={submitInsurance} className="grid gap-3"><select className="rounded-md border p-2" value={patientId} onChange={(e) => setPatientId(e.target.value)}><option value="">{t.choosePatient}</option>{patients.map((p) => <option key={p.id} value={p.id}>{patientName[p.id]}</option>)}</select><Input placeholder={t.payerName} value={payerName} onChange={(e) => setPayerName(e.target.value)} required /><Input placeholder={t.policyNumber} value={policyNumber} onChange={(e) => setPolicyNumber(e.target.value)} /><Input placeholder={t.memberNumber} value={memberNumber} onChange={(e) => setMemberNumber(e.target.value)} /><Button disabled={busy}>{busy ? t.loading : t.create}</Button></form>}{insurance.length === 0 ? <p className="text-sm text-muted-foreground">{t.noInsurance}</p> : insurance.slice(0, 20).map((x) => <div key={x.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{patientName[x.patient_id] || t.patient}</p><p className="text-sm text-muted-foreground">{x.payer_name}{x.policy_number ? ` · ${x.policy_number}` : ""}</p></div><Badge>{x.claim_ready ? t.claimReady : x.reconciliation_status}</Badge></div>)}</>)}
    {show("suppliers") && section(t.suppliers, <>{canPurchasing && <form onSubmit={submitSupplier} className="grid gap-3"><Input placeholder={t.supplierName} value={supplierName} onChange={(e) => setSupplierName(e.target.value)} required /><Input placeholder={t.phone} value={supplierPhone} onChange={(e) => setSupplierPhone(e.target.value)} /><Input placeholder={t.email} value={supplierEmail} onChange={(e) => setSupplierEmail(e.target.value)} type="email" /><Button disabled={busy}>{busy ? t.loading : t.create}</Button></form>}{suppliers.length === 0 ? <p className="text-sm text-muted-foreground">{t.noSuppliers}</p> : suppliers.slice(0, 20).map((s) => <div key={s.id} className="rounded-lg border p-3"><p className="font-medium">{s.name}</p><p className="text-sm text-muted-foreground">{s.phone ?? ""}{s.email ? ` · ${s.email}` : ""}</p></div>)}</>)}
    {show("purchasing") && section(t.purchasing, <>{canPurchasing && suppliers.length > 0 && inventoryItems.length > 0 ? <form onSubmit={submitPurchaseOrder} className="grid gap-3"><select className="rounded-md border p-2" value={supplierId} onChange={(e) => setSupplierId(e.target.value)}>{suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="rounded-md border p-2" value={inventoryItemId} onChange={(e) => setInventoryItemId(e.target.value)}>{inventoryItems.map((i) => <option key={i.id} value={i.id}>{i.name} ({i.current_stock} {i.unit})</option>)}</select><div className="grid grid-cols-2 gap-3"><Input type="number" min="1" value={purchaseQuantity} onChange={(e) => setPurchaseQuantity(e.target.value)} placeholder={t.quantity} /><Input type="number" min="0" step="0.01" value={unitCost} onChange={(e) => setUnitCost(e.target.value)} placeholder={t.unitCost} required /></div><Button disabled={busy}>{busy ? t.loading : t.create}</Button></form> : <p className="text-sm text-muted-foreground">{suppliers.length === 0 ? t.noSuppliers : inventoryItems.length === 0 ? t.noInventoryItems : t.permissionDenied}</p>}{purchaseOrders.slice(0, 20).map((o) => <div key={o.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{o.order_number ?? t.purchasing} {o.supplier?.name ? `· ${o.supplier.name}` : ""}</p><p className="text-sm text-muted-foreground">{o.order_date}</p></div><span>{money(o.total_subunits)} · {o.status}</span></div>)}</>)}
    {show("receiving") && section(t.receiving, <div className="space-y-3"><p className="text-sm text-muted-foreground">{t.receivingDescription}</p>{purchaseOrders.length === 0 ? <p className="text-sm text-muted-foreground">{t.noOrders}</p> : purchaseOrders.map((o) => <div key={o.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{o.order_number ?? t.purchasing} · {o.supplier?.name ?? ""}</p><p className="text-sm text-muted-foreground">{o.order_date} · {o.status}</p></div><Badge>{t.receiveFromInventory}</Badge></div>)}</div>)}
    {!activeSection && <div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href="/invoices">{t.viewInvoices}</Link></Button><Button asChild variant="outline"><Link href="/inventory">{t.viewInventory}</Link></Button></div>}
  </div>;
}
