import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { createClient } from "@/infrastructure/supabase/server";
import { resolveTenantId } from "@/core/auth/resolveTenantId";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import { FinancialResourceTable, type FinancialResourceColumn } from "./financial-resource-table";
import type { Locale } from "@/core/i18n/messages";

type Resource="payments"|"financial-plans"|"installments"|"insurance"|"insurance-claims"|"consumption"|"suppliers"|"purchasing"|"receiving";
type Localized={ar:string;en:string};type Field={name:string;label:Localized;type:"text"|"number"|"date"|"datetime-local";required?:boolean};type ResourceConfig={title:Localized;permission:string;table:string;orderBy:string;select:string;columns:Array<FinancialResourceColumn&{labelAr:string}>;fields:Field[]};
const f=(name:string,en:string,ar:string,type:Field["type"]="text",required=false):Field=>({name,label:{en,ar},type,required});
const config:Record<Resource,ResourceConfig>={
 payments:{title:{ar:"المدفوعات",en:"Payments"},permission:"invoices:read",table:"invoice_payments",orderBy:"payment_date",select:"id,invoice_id,amount_subunits,payment_method,payment_date,payment_reference,transaction_id,notes",columns:[{key:"amount",label:"Amount",labelAr:"المبلغ"},{key:"payment_method",label:"Method",labelAr:"طريقة الدفع"},{key:"payment_date",label:"Date",labelAr:"التاريخ"},{key:"payment_reference",label:"Reference",labelAr:"المرجع"},{key:"transaction_id",label:"Transaction",labelAr:"المعاملة"},{key:"notes",label:"Notes",labelAr:"ملاحظات"}],fields:[f("invoice_id","Invoice ID","رقم الفاتورة", "text",true),f("amount","Amount","المبلغ","number",true),f("payment_method","Payment method","طريقة الدفع", "text",true),f("payment_reference","Reference","المرجع"),f("transaction_id","Transaction","المعاملة"),f("notes","Notes","ملاحظات")]},
 "financial-plans":{title:{ar:"الخطط المالية",en:"Financial Plans"},permission:"invoices:read",table:"financial_plans",orderBy:"created_at",select:"id,patient_id,treatment_plan_id,total_amount_subunits,insurance_covered_subunits,patient_responsibility_subunits,currency,status,notes,created_at",columns:[{key:"total_amount",label:"Total",labelAr:"الإجمالي"},{key:"insurance_covered",label:"Insurance covered",labelAr:"التغطية التأمينية"},{key:"patient_responsibility",label:"Patient responsibility",labelAr:"مسؤولية المريض"},{key:"currency",label:"Currency",labelAr:"العملة"},{key:"status",label:"Status",labelAr:"الحالة"},{key:"notes",label:"Notes",labelAr:"ملاحظات"}],fields:[f("patient_id","Patient ID","معرف المريض", "text",true),f("treatment_plan_id","Treatment plan ID","معرف الخطة العلاجية"),f("total_amount","Total","الإجمالي","number",true),f("insurance_covered","Insurance covered","التغطية التأمينية","number"),f("patient_responsibility","Patient responsibility","مسؤولية المريض","number",true),f("currency","Currency","العملة"),f("notes","Notes","ملاحظات")]},
 installments:{title:{ar:"الأقساط",en:"Installments"},permission:"invoices:read",table:"financial_installments",orderBy:"due_date",select:"id,financial_plan_id,installment_no,due_date,amount_subunits,amount_paid_subunits,status,invoice_id,notes,created_at",columns:[{key:"installment_no",label:"#",labelAr:"رقم القسط"},{key:"due_date",label:"Due date",labelAr:"تاريخ الاستحقاق"},{key:"amount",label:"Amount",labelAr:"المبلغ"},{key:"amount_paid",label:"Paid",labelAr:"المدفوع"},{key:"status",label:"Status",labelAr:"الحالة"},{key:"notes",label:"Notes",labelAr:"ملاحظات"}],fields:[f("financial_plan_id","Financial plan ID","معرف الخطة المالية","text",true),f("installment_no","Installment #","رقم القسط","number",true),f("due_date","Due date","تاريخ الاستحقاق","date",true),f("amount","Amount","المبلغ","number",true),f("notes","Notes","ملاحظات")]},
 insurance:{title:{ar:"التأمين",en:"Insurance"},permission:"insurance:read",table:"patient_insurance_profiles",orderBy:"created_at",select:"id,patient_id,payer_name,policy_number,member_number,coverage_summary,patient_responsibility_subunits,status,claim_ready,reconciliation_status,effective_from,effective_to,notes,created_at",columns:[{key:"payer_name",label:"Payer",labelAr:"شركة التأمين"},{key:"policy_number",label:"Policy",labelAr:"رقم الوثيقة"},{key:"member_number",label:"Member",labelAr:"رقم العضوية"},{key:"coverage_summary",label:"Coverage",labelAr:"التغطية"},{key:"patient_responsibility",label:"Patient responsibility",labelAr:"مسؤولية المريض"},{key:"status",label:"Status",labelAr:"الحالة"},{key:"claim_ready",label:"Claim ready",labelAr:"جاهز للمطالبة"},{key:"reconciliation_status",label:"Reconciliation",labelAr:"التسوية"}],fields:[f("patient_id","Patient ID","معرف المريض","text",true),f("payer_name","Payer","شركة التأمين","text",true),f("policy_number","Policy number","رقم الوثيقة"),f("member_number","Member number","رقم العضوية"),f("coverage_summary","Coverage","التغطية"),f("patient_responsibility","Patient responsibility","مسؤولية المريض","number"),f("effective_from","Effective from","ساري من","date"),f("effective_to","Effective to","ساري حتى","date"),f("notes","Notes","ملاحظات")]},
 "insurance-claims":{title:{ar:"مطالبات التأمين",en:"Insurance Claims"},permission:"insurance:read",table:"insurance_claims",orderBy:"created_at",select:"id,patient_id,insurance_profile_id,invoice_id,claim_reference,amount_claimed_subunits,amount_reconciled_subunits,status,prepared_at,reconciled_at,notes,created_at",columns:[{key:"claim_reference",label:"Claim reference",labelAr:"مرجع المطالبة"},{key:"amount_claimed",label:"Claimed",labelAr:"المطالب به"},{key:"amount_reconciled",label:"Reconciled",labelAr:"تمت تسويته"},{key:"status",label:"Status",labelAr:"الحالة"},{key:"prepared_at",label:"Prepared",labelAr:"تاريخ الإعداد"}],fields:[f("patient_id","Patient ID","معرف المريض","text",true),f("insurance_profile_id","Insurance profile ID","معرف التأمين","text",true),f("invoice_id","Invoice ID","معرف الفاتورة"),f("claim_reference","Claim reference","مرجع المطالبة"),f("amount_claimed","Claimed amount","المبلغ المطالب به","number",true),f("notes","Notes","ملاحظات")]},
 consumption:{title:{ar:"الاستهلاك",en:"Consumption"},permission:"inventory:read",table:"inventory_ledger",orderBy:"created_at",select:"id,item_id,material_name,quantity_consumed,consumption_type,procedure_id,session_id,notes,created_at",columns:[{key:"material_name",label:"Material",labelAr:"المادة"},{key:"quantity_consumed",label:"Quantity",labelAr:"الكمية"},{key:"consumption_type",label:"Type",labelAr:"النوع"},{key:"notes",label:"Notes",labelAr:"ملاحظات"}],fields:[f("material_name","Material","المادة","text",true),f("quantity","Quantity","الكمية","number",true),f("consumption_type","Type","النوع","text",true),f("procedure_id","Procedure ID","معرف الإجراء"),f("session_id","Session ID","معرف الجلسة"),f("notes","Notes","ملاحظات")]},
 suppliers:{title:{ar:"الموردون",en:"Suppliers"},permission:"purchasing:read",table:"suppliers",orderBy:"created_at",select:"id,name,name_ar,contact_name,phone,email,address,tax_identifier,status,notes,created_at",columns:[{key:"name",label:"Supplier",labelAr:"المورد"},{key:"contact_name",label:"Contact",labelAr:"جهة الاتصال"},{key:"phone",label:"Phone",labelAr:"الهاتف"},{key:"email",label:"Email",labelAr:"البريد الإلكتروني"},{key:"status",label:"Status",labelAr:"الحالة"}],fields:[f("name","Supplier","المورد","text",true),f("name_ar","Arabic name","الاسم العربي"),f("contact_name","Contact","جهة الاتصال"),f("phone","Phone","الهاتف"),f("email","Email","البريد الإلكتروني"),f("address","Address","العنوان"),f("tax_identifier","Tax identifier","الرقم الضريبي"),f("notes","Notes","ملاحظات")]},
 purchasing:{title:{ar:"المشتريات",en:"Purchasing"},permission:"purchasing:read",table:"purchase_orders",orderBy:"order_date",select:"id,order_number,supplier_id,order_date,expected_date,subtotal_subunits,tax_subunits,total_subunits,status,notes,created_at",columns:[{key:"order_number",label:"PO number",labelAr:"رقم أمر الشراء"},{key:"order_date",label:"Order date",labelAr:"تاريخ الطلب"},{key:"expected_date",label:"Expected",labelAr:"التاريخ المتوقع"},{key:"total",label:"Total",labelAr:"الإجمالي"},{key:"status",label:"Status",labelAr:"الحالة"}],fields:[f("supplier_id","Supplier ID","معرف المورد","text",true),f("order_number","PO number","رقم أمر الشراء"),f("order_date","Order date","تاريخ الطلب","date",true),f("expected_date","Expected date","التاريخ المتوقع","date"),f("subtotal","Subtotal","المجموع الفرعي","number",true),f("tax","Tax","الضريبة","number"),f("total","Total","الإجمالي","number",true),f("notes","Notes","ملاحظات")]},
 receiving:{title:{ar:"الاستلام",en:"Receiving"},permission:"purchasing:read",table:"purchase_receipts",orderBy:"received_at",select:"id,purchase_order_id,receipt_number,received_at,received_by,notes,created_at",columns:[{key:"receipt_number",label:"Receipt",labelAr:"رقم الاستلام"},{key:"received_at",label:"Received at",labelAr:"تاريخ الاستلام"},{key:"notes",label:"Notes",labelAr:"ملاحظات"}],fields:[f("purchase_order_id","Purchase order ID","معرف أمر الشراء","text",true),f("receipt_number","Receipt number","رقم الاستلام"),f("received_at","Received at","تاريخ الاستلام","datetime-local"),f("notes","Notes","ملاحظات")]}
};

export async function FinancialResourceListPage({resource}:{resource:Resource}){const item=config[resource];const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const tenantId=await resolveTenantId(user.id);if(!tenantId)redirect("/login");const permissions=await getEffectivePermissions(user.id,tenantId);if(!permissions.includes(item.permission as never))redirect("/financial-resources");const localeCookie=(await cookies()).get("core-system-locale")?.value;const locale:Locale=localeCookie==="ar"?"ar":"en";
 async function createResource(fd:FormData){"use server";const db=await createClient();const{data:{u}}=await db.auth.getUser();if(!u)return;const tid=await resolveTenantId(u.id);if(!tid)return;const perms=await getEffectivePermissions(u.id,tid);const writePermission=item.permission.replace(":read",":write");if(!perms.includes(writePermission as never))return;const row:Record<string,unknown>={tenant_id:tid,created_by:u.id};for(const field of item.fields){const value=String(fd.get(field.name)||"");if(!value)continue;if(field.name.endsWith("_amount")||["amount","total","subtotal","tax","insurance_covered","patient_responsibility","amount_claimed"].includes(field.name))row[`${field.name}_subunits`]=Math.round(Number(value)*100);else if(field.name==="quantity")row.quantity_consumed=Number(value);else row[field.name]=value;}if(resource==="payments")row.payment_date=new Date().toISOString();if(resource==="payments")row.payment_method=row.payment_method||"cash";if(resource==="financial-plans"){row.status="active";row.currency=row.currency||"JOD";}if(resource==="installments"){row.amount_paid_subunits=0;row.status="pending";}if(resource==="insurance"){row.status="active";row.claim_ready=false;row.reconciliation_status="pending";}if(resource==="insurance-claims"){row.amount_reconciled_subunits=0;row.status="draft";}if(resource==="suppliers")row.status="active";if(resource==="purchasing"){row.status="draft";row.order_date=row.order_date||new Date().toISOString().slice(0,10);row.subtotal_subunits=row.subtotal_subunits||0;row.tax_subunits=row.tax_subunits||0;row.total_subunits=row.total_subunits||0;}if(resource==="receiving")row.received_at=row.received_at||new Date().toISOString();await db.from(item.table).insert(row);}
 const[{data,error},{data:tenant}]=await Promise.all([supabase.from(item.table).select(item.select).eq("tenant_id",tenantId).order(item.orderBy,{ascending:false}).limit(200),supabase.from("master_tenants").select("currency").eq("id",tenantId).maybeSingle()]);if(error)throw error;const currency=tenant?.currency??"USD";const formatMoney=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat(locale==="ar"?"ar":"en",{style:"currency",currency,minimumFractionDigits:2}).format(n/100):"—"};const formatDate=(v:unknown)=>v?new Intl.DateTimeFormat(locale==="ar"?"ar":"en",{dateStyle:"medium"}).format(new Date(String(v))):"—";const columns=item.columns.map(({key,label,labelAr})=>({key,label:locale==="ar"?labelAr:label}));const rows:Record<string,string|number|null>[] = Array.isArray(data)?data.map(row=>{const source=row as unknown as Record<string,unknown>;const display:Record<string,string|number|null>={};for(const[key,value]of Object.entries(source)){if(["id","tenant_id","patient_id","treatment_plan_id","invoice_id","financial_plan_id","insurance_profile_id","item_id","procedure_id","session_id","supplier_id","purchase_order_id","received_by","created_by"].includes(key))continue;if(key.endsWith("_subunits"))display[key.replace(/_subunits$/,"")]=formatMoney(value);else if(["created_at","payment_date","order_date","expected_date","received_at","due_date","prepared_at","reconciled_at","effective_from","effective_to"].includes(key))display[key]=formatDate(value);else display[key]=value==null?null:String(value);}return display}):[];return <div className="space-y-4" dir={locale==="ar"?"rtl":"ltr"}><div><h1 className="text-2xl font-bold">{item.title[locale]}</h1><p className="text-sm text-muted-foreground">{locale==="ar"?"المالية والموارد":"Financial & Resources"}</p></div><form action={createResource} className="grid gap-3 rounded-lg border bg-card p-4 md:grid-cols-3">{item.fields.map(field=><label key={field.name} className="space-y-1 text-sm"><span>{field.label[locale]}</span><input name={field.name} type={field.type} required={field.required} className="w-full rounded border p-2" /></label>)}<button className="rounded bg-primary px-4 py-2 text-primary-foreground md:col-span-3">{locale==="ar"?"حفظ":"Save"}</button></form><FinancialResourceTable title={item.title[locale]} columns={columns} rows={rows}/></div>;
}
