"use client";
import { useState } from "react";
import { adjustInventory, saveInventoryItem } from "@/domain/financial-resources/financial-workflow.actions";
type Item={id:string;name:string;name_ar:string|null;unit:string;current_stock:number;reorder_threshold:number};
type Props={locale:"ar"|"en";items:Item[];canManage:boolean};
export function InventoryOperations({locale,items,canManage}:Props){
 const ar=locale==="ar"; const [mode,setMode]=useState<"add"|"issue"|"adjust">("add"); const[busy,setBusy]=useState(false); const[msg,setMsg]=useState("");
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);let r;
  if(mode==="add"){r=await saveInventoryItem({name:String(f.get("name")),unit:String(f.get("unit")||"unit"),reorder_threshold:Number(f.get("threshold")||0),is_procedure_material:false,is_operating_consumable:true,requires_batch_tracking:false,requires_expiry_tracking:false});}
  else {const quantity=Math.trunc(Number(f.get("quantity")));r=await adjustInventory({item_id:String(f.get("item")),delta:mode==="issue"?-quantity:quantity,reason:String(f.get("reason")||"")});}
  setBusy(false);setMsg(r.success?(ar?"تم حفظ العملية":"Operation saved"):(r.error??(ar?"تعذر الحفظ":"Could not save")));if(r.success)location.reload();
 };
 return <div className="space-y-5" dir={ar?"rtl":"ltr"}><div><h1 className="text-xl font-semibold">{ar?"الأصناف والمخزون":"Items & Inventory"}</h1><p className="text-sm text-muted-foreground">{ar?"كل عملية مخزون واضحة: إضافة، صرف، استهلاك في إجراء، أو تسوية.":"Clear stock operations: add stock, issue stock, procedure consumption, or reconciliation."}</p></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><button onClick={()=>setMode("add")} className={`rounded-lg border p-4 text-start ${mode==="add"?"ring-2 ring-primary":""}`}><b>{ar?"إضافة صنف / إضافة مخزون":"Add Item / Stock"}</b><p className="mt-1 text-sm text-muted-foreground">{ar?"إنشاء صنف جديد ثم إدخال رصيده":"Create an item and establish its stock"}</p></button><button onClick={()=>setMode("issue")} className={`rounded-lg border p-4 text-start ${mode==="issue"?"ring-2 ring-primary":""}`}><b>{ar?"صرف / إزالة من المخزون":"Issue / Remove Stock"}</b><p className="mt-1 text-sm text-muted-foreground">{ar?"إخراج كمية للاستخدام غير المرتبط بإجراء":"Remove stock for non-procedure use"}</p></button><button onClick={()=>setMode("adjust")} className={`rounded-lg border p-4 text-start ${mode==="adjust"?"ring-2 ring-primary":""}`}><b>{ar?"تسوية المخزون":"Stock Reconciliation"}</b><p className="mt-1 text-sm text-muted-foreground">{ar?"تصحيح الرصيد الفعلي مع سبب واضح":"Correct physical count with a reason"}</p></button><a href="/patient-flow/clinical" className="rounded-lg border p-4 text-start"><b>{ar?"استهلاك في إجراء":"Consume in Procedure"}</b><p className="mt-1 text-sm text-muted-foreground">{ar?"يرتبط بالإجراء والزيارة الطبية":"Links consumption to the clinical procedure"}</p></a></div>
  {canManage&&<form onSubmit={submit} className="grid gap-3 rounded-lg border p-5 md:grid-cols-2">{mode==="add"?<><label className="grid gap-1 text-sm"><span className="font-medium">{ar?"اسم الصنف":"Item name"}</span><input name="name" required className="rounded-md border bg-background px-3 py-2"/></label><label className="grid gap-1 text-sm"><span className="font-medium">{ar?"وحدة القياس":"Unit"}</span><input name="unit" defaultValue={ar?"وحدة":"unit"} required className="rounded-md border bg-background px-3 py-2"/></label><label className="grid gap-1 text-sm"><span className="font-medium">{ar?"حد إعادة الطلب":"Reorder threshold"}</span><input name="threshold" type="number" min="0" defaultValue="0" className="rounded-md border bg-background px-3 py-2"/></label></>:<><label className="grid gap-1 text-sm md:col-span-2"><span className="font-medium">{ar?"الصنف":"Item"}</span><select name="item" required className="rounded-md border bg-background px-3 py-2">{items.map(i=><option key={i.id} value={i.id}>{ar&&i.name_ar?i.name_ar:i.name} · {i.current_stock} {i.unit}</option>)}</select></label><label className="grid gap-1 text-sm"><span className="font-medium">{ar?"الكمية":"Quantity"}</span><input name="quantity" type="number" min="1" step="1" required className="rounded-md border bg-background px-3 py-2"/></label><label className="grid gap-1 text-sm"><span className="font-medium">{ar?"السبب":"Reason"}</span><input name="reason" required className="rounded-md border bg-background px-3 py-2"/></label></>}<button disabled={busy} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground md:col-span-2">{mode==="add"?(ar?"إنشاء الصنف":"Create item"):mode==="issue"?(ar?"تسجيل الصرف":"Record issue"):(ar?"حفظ التسوية":"Save reconciliation")}</button></form>}
  {msg&&<div className="rounded-md border p-3 text-sm">{msg}</div>}
  <div className="overflow-auto rounded-lg border"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-start">{ar?"الصنف":"Item"}</th><th className="p-3 text-start">{ar?"الرصيد":"Stock"}</th><th className="p-3 text-start">{ar?"حد إعادة الطلب":"Reorder"}</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-t"><td className="p-3">{ar&&i.name_ar?i.name_ar:i.name}</td><td className="p-3">{i.current_stock} {i.unit}</td><td className="p-3">{i.reorder_threshold}</td></tr>)}</tbody></table></div>
 </div>
}
