import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import { createClient } from "@/infrastructure/supabase/server";
import { resolveTenantId } from "@/core/auth/resolveTenantId";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import { createWorkItem, updateWorkItem, assignWorkItem, handoffWorkItem, escalateWorkItem } from "@/domain/journey-coordination/work.actions";

export default async function WorkCenterPage() {
  const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login"); const tenantId=await resolveTenantId(user.id); if(!tenantId)redirect("/login"); const permissions=await getEffectivePermissions(user.id,tenantId); if(!permissions.includes("work:read" as never))redirect("/"); const ar=(await cookies()).get("core-system-locale")?.value==="ar"; const canManage=permissions.includes("work:manage" as never);
  const [{data:work},{data:users},{data:patients}] = await Promise.all([
    supabase.from("operational_work_items").select("id,kind,title,details,status,priority,due_at,assignee_clinic_user_id,patient_id,created_at,outcome").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(80),
    supabase.from("clinic_users").select("id,full_name,email").eq("tenant_id",tenantId).eq("is_active",true).is("deleted_at",null).order("full_name"),
    supabase.from("clinic_patients").select("id,first_name,last_name").eq("tenant_id",tenantId).is("deleted_at",null).order("first_name").limit(200),
  ]);
  async function addWork(fd:FormData){"use server";await createWorkItem({kind:String(fd.get("kind")||"task") as any,title:String(fd.get("title")||""),details:String(fd.get("details")||"")||undefined,assigneeId:String(fd.get("assignee")||"")||null,patientId:String(fd.get("patient")||"")||null,priority:String(fd.get("priority")||"normal") as any,dueAt:String(fd.get("due_at")||"")||null});}
  async function status(fd:FormData){"use server";await updateWorkItem({id:String(fd.get("id")),status:String(fd.get("status")) as any,outcome:String(fd.get("outcome")||"")||null});}
  async function assign(fd:FormData){"use server";await assignWorkItem({id:String(fd.get("id")),assigneeId:String(fd.get("assignee")||"")||null,note:String(fd.get("note")||"")||null});}
  async function handoff(fd:FormData){"use server";await handoffWorkItem({id:String(fd.get("id")),destinationUserId:String(fd.get("destination")),reason:String(fd.get("reason")||"")||null});}
  async function escalate(fd:FormData){"use server";await escalateWorkItem({id:String(fd.get("id")),reason:String(fd.get("reason")||""),priority:String(fd.get("priority")||"urgent") as "high"|"urgent"});}
  const rows=work??[]; const userName=Object.fromEntries((users??[]).map((u:any)=>[u.id,u.full_name||u.email])); const patientName=Object.fromEntries((patients??[]).map((p:any)=>[p.id,`${p.first_name} ${p.last_name}`]));
  return <div className="space-y-8" dir={ar?"rtl":"ltr"}>
    <header><h1 className="text-2xl font-bold">{ar?"مركز العمل":"My Work / Work Center"}</h1><p className="mt-1 text-sm text-muted-foreground">{ar?"المهام والطلبات والتسليمات والإجراءات التالية والتصعيدات، مع سجل مسؤولية واضح.":"Tasks, requests, handoffs, next actions and escalations with explicit ownership and history."}</p></header>
    <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"إنشاء عمل":"Create work"}</h2><form action={addWork} className="grid gap-2 md:grid-cols-4"><select name="kind" className="rounded border p-2"><option value="task">Task</option><option value="request">Request</option><option value="handoff">Handoff</option><option value="next_action">Next action</option><option value="escalation">Escalation</option></select><input name="title" required placeholder={ar?"العنوان":"Title"} className="rounded border p-2"/><select name="assignee" className="rounded border p-2"><option value="">{ar?"غير معين":"Unassigned"}</option>{(users??[]).map((u:any)=><option key={u.id} value={u.id}>{u.full_name||u.email}</option>)}</select><select name="priority" className="rounded border p-2"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="urgent">Urgent</option></select><select name="patient" className="rounded border p-2"><option value="">{ar?"مريض مرتبط":"Related patient"}</option>{(patients??[]).map((p:any)=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select><input name="due_at" type="datetime-local" className="rounded border p-2"/><textarea name="details" rows={2} placeholder={ar?"التفاصيل":"Details"} className="rounded border p-2 md:col-span-2"/><button className="rounded bg-primary px-4 py-2 text-primary-foreground">{ar?"إنشاء":"Create"}</button></form></section>
    <section className="grid gap-4 md:grid-cols-4"><Metric label={ar?"اليوم":"Due today"} value={rows.filter((w:any)=>w.due_at&&new Date(w.due_at).toDateString()===new Date().toDateString()&&w.status!=="completed").length}/><Metric label={ar?"متأخر":"Overdue"} value={rows.filter((w:any)=>w.due_at&&new Date(w.due_at)<new Date()&&w.status!=="completed").length}/><Metric label={ar?"غير معين":"Unassigned"} value={rows.filter((w:any)=>!w.assignee_clinic_user_id&&w.status!=="completed").length}/><Metric label={ar?"مصعد":"Escalated"} value={rows.filter((w:any)=>w.kind==="escalation").length}/></section>
    <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"العمل المفتوح":"Work queue"}</h2><div className="space-y-3">{rows.map((w:any)=><article key={w.id} className="rounded-lg border p-4"><div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between"><div><div className="font-medium">{w.title}</div><div className="text-sm text-muted-foreground">{w.kind} · {w.status} · {w.priority}{w.patient_id?` · ${patientName[w.patient_id]||"Patient"}`:""}{w.assignee_clinic_user_id?` · ${userName[w.assignee_clinic_user_id]||"Assigned"}`:" · Unassigned"}</div>{w.details&&<p className="mt-1 text-sm">{w.details}</p>}{w.outcome&&<p className="mt-1 text-sm text-muted-foreground">Outcome: {w.outcome}</p>}</div><div className="text-xs text-muted-foreground">{w.due_at?new Date(w.due_at).toLocaleString():"No due date"}</div></div>
      <div className="mt-3 grid gap-2 md:grid-cols-4"><form action={status} className="flex gap-1"><input type="hidden" name="id" value={w.id}/><select name="status" defaultValue={w.status} className="min-w-0 flex-1 rounded border p-2 text-sm"><option value="accepted">Accepted</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option></select><button className="rounded border px-2 text-sm">Update</button></form>{canManage&&<form action={assign} className="flex gap-1"><input type="hidden" name="id" value={w.id}/><select name="assignee" className="min-w-0 flex-1 rounded border p-2 text-sm"><option value="">Unassigned</option>{(users??[]).map((u:any)=><option key={u.id} value={u.id}>{u.full_name||u.email}</option>)}</select><button className="rounded border px-2 text-sm">Assign</button></form>}{canManage&&<form action={handoff} className="flex gap-1"><input type="hidden" name="id" value={w.id}/><select name="destination" required className="min-w-0 flex-1 rounded border p-2 text-sm"><option value="">Handoff to</option>{(users??[]).map((u:any)=><option key={u.id} value={u.id}>{u.full_name||u.email}</option>)}</select><button className="rounded border px-2 text-sm">Handoff</button></form>}{canManage&&<form action={escalate} className="flex gap-1"><input type="hidden" name="id" value={w.id}/><input name="reason" required placeholder="Escalation reason" className="min-w-0 flex-1 rounded border p-2 text-sm"/><select name="priority" className="rounded border p-2 text-sm"><option value="urgent">Urgent</option><option value="high">High</option></select><button className="rounded border border-red-300 px-2 text-sm text-red-700">Escalate</button></form>}</div></article>)}{rows.length===0&&<p className="text-sm text-muted-foreground">{ar?"لا يوجد عمل مسجل بعد.":"No work recorded yet."}</p>}</div></section>
  </div>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-lg border bg-card p-4"><div className="text-sm text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>}
