"use client";

import { useState } from "react";
import { usePermissions } from "@/core/permissions/usePermissions";
import { useTenantId } from "@/core/auth/useTenantId";
import { useI18n } from "@/core/i18n/I18nProvider";
import { useSubscriptionInfo, applyActivationCode, TEMPORARY_CONTACT } from "@/domain/subscriptions";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import { Input } from "@/shared/components/ui/input";
import { Badge } from "@/shared/components/ui/badge";
import { Loader2, CheckCircle, AlertCircle, CreditCard, Calendar, Clock, Users, Building2, HardDrive, KeyRound, Phone, Mail, MessageCircle } from "lucide-react";
import { toast } from "sonner";

export function SubscriptionCenter() {
  const { locale, admin: a } = useI18n(); const { hasPermission } = usePermissions(); const { tenantId, isLoading: tenantLoading } = useTenantId();
  const { data: subscription, isLoading: subLoading, error: subError } = useSubscriptionInfo(tenantId);
  const [code, setCode] = useState(""); const [codeState, setCodeState] = useState<"idle" | "loading" | "success" | "error">("idle"); const [codeMessage, setCodeMessage] = useState<string | null>(null);
  const dateLocale = locale === "ar" ? "ar-SA" : "en-US";
  if (!hasPermission("subscription:read")) return <Empty title={a.subscription.accessDenied} icon={<AlertCircle className="h-12 w-12" />} />;
  if (tenantLoading || subLoading) return <div className="flex items-center justify-center py-12"><Loader2 className="h-6 w-6 animate-spin text-primary" /><span className="ms-3 text-muted-foreground">{a.subscription.loading}</span></div>;
  if (subError || !subscription) return <Empty title={a.subscription.loadFailed} icon={<AlertCircle className="h-12 w-12 text-destructive" />} />;
  const statusLabel = subscription.subscriptionStatus === "active" ? a.subscription.active : subscription.subscriptionStatus === "trial" ? (locale === "ar" ? "فترة تجريبية" : "Trial") : a.subscription.inactive;
  const applyCode = async () => { if (!code.trim()) return; setCodeState("loading"); setCodeMessage(null); const result = await applyActivationCode(code.trim()); const message = result.error || a.subscription.notImplemented; if (result.success) { setCodeState("success"); setCodeMessage(a.subscription.apply); toast.success(a.subscription.apply); } else { setCodeState("error"); setCodeMessage(message); toast.error(message); } };
  return <div className="space-y-6" dir={locale === "ar" ? "rtl" : "ltr"}>
    <div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">{a.subscription.title}</h2><p className="text-sm text-muted-foreground">{a.subscription.description}</p></div><Badge>{statusLabel}</Badge></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><CreditCard className="h-5 w-5" />{a.subscription.currentPlan}</CardTitle></CardHeader><CardContent className="grid grid-cols-1 gap-4 md:grid-cols-2"><Info label={locale === "ar" ? "العيادة" : "Clinic"} value={subscription.clinicNameAr ?? subscription.clinicName} /><Info label="Tenant ID" value={subscription.tenantId} mono /><Info label={a.subscription.plan} value={subscription.planNameAr ?? subscription.planName ?? subscription.subscriptionTier} mono={false} /><Info label={locale === "ar" ? "مفتاح الترخيص" : "License key"} value={subscription.licenseKey ?? "—"} mono />{subscription.subscriptionStart && <Info label={locale === "ar" ? "تاريخ البدء" : "Start date"} value={new Date(subscription.subscriptionStart).toLocaleDateString(dateLocale)} icon={<Calendar className="h-4 w-4" />} />}{subscription.subscriptionEnd && <Info label={locale === "ar" ? "تاريخ الانتهاء" : "End date"} value={new Date(subscription.subscriptionEnd).toLocaleDateString(dateLocale)} icon={<Calendar className="h-4 w-4" />} />}{subscription.daysRemaining !== null && <Info label={locale === "ar" ? "المدة المتبقية" : "Days remaining"} value={String(subscription.daysRemaining)} icon={<Clock className="h-4 w-4" />} />}</CardContent></Card>
    <Card><CardHeader><CardTitle>{locale === "ar" ? "حدود الخطة" : "Plan limits"}</CardTitle><CardDescription>{locale === "ar" ? "الموارد المتاحة في اشتراكك الحالي" : "Resources included in your current subscription"}</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-4 md:grid-cols-4"><Limit icon={<Users className="h-4 w-4" />} label={a.users.count} value={subscription.maxUsers} /><Limit icon={<Building2 className="h-4 w-4" />} label={locale === "ar" ? "الفروع" : "Branches"} value={subscription.maxBranches} /><Limit icon={<HardDrive className="h-4 w-4" />} label="GB" value={subscription.storageGb} /><Limit icon={<CreditCard className="h-4 w-4" />} label={locale === "ar" ? "الأجهزة" : "Devices"} value={subscription.maxDevices} /></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5" />{a.subscription.activationCode}</CardTitle><CardDescription>{locale === "ar" ? "أدخل رمز التفعيل الذي تلقيته من إدارة المنصة" : "Enter the activation code provided by platform administration."}</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row"><Input placeholder={locale === "ar" ? "أدخل رمز التفعيل..." : "Enter activation code..."} value={code} onChange={e => { setCode(e.target.value); setCodeState("idle"); }} disabled={codeState === "loading"} /><Button onClick={() => void applyCode()} disabled={!code.trim() || codeState === "loading"}>{codeState === "loading" && <Loader2 className="me-2 h-4 w-4 animate-spin" />}{a.subscription.apply}</Button></div>{codeMessage && <div className={`flex items-center gap-2 text-sm ${codeState === "success" ? "text-green-600" : "text-destructive"}`}>{codeState === "success" ? <CheckCircle className="h-4 w-4" /> : <AlertCircle className="h-4 w-4" />}{codeMessage}</div>}<div className="rounded-lg border p-3 text-sm"><p className="font-medium">{locale === "ar" ? "ملاحظة" : "Note"}</p><p className="text-muted-foreground">{a.subscription.notImplemented}</p></div></CardContent></Card>
    <Card><CardHeader><CardTitle>{locale === "ar" ? "معلومات التواصل" : "Contact information"}</CardTitle></CardHeader><CardContent className="space-y-2"><a href={`tel:${TEMPORARY_CONTACT.phone}`} className="flex items-center gap-3 rounded-lg p-3 hover:bg-muted"><Phone className="h-5 w-5" />{TEMPORARY_CONTACT.phone}</a><a href={`https://wa.me/${TEMPORARY_CONTACT.whatsapp.replace(/^\+/, "")}`} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 rounded-lg p-3 hover:bg-muted"><MessageCircle className="h-5 w-5" />{TEMPORARY_CONTACT.whatsapp}</a><a href={`mailto:${TEMPORARY_CONTACT.email}`} className="flex items-center gap-3 rounded-lg p-3 hover:bg-muted"><Mail className="h-5 w-5" />{TEMPORARY_CONTACT.email}</a></CardContent></Card>
  </div>;
}
function Empty({ title, icon }: { title: string; icon: React.ReactNode }) { return <div className="flex flex-col items-center justify-center py-12 text-center"><div className="mb-4 text-muted-foreground">{icon}</div><h3 className="text-lg font-semibold">{title}</h3></div>; }
function Info({ label, value, icon, mono }: { label: string; value: string | null | undefined; icon?: React.ReactNode; mono?: boolean }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className={`flex items-center gap-2 text-sm font-medium ${mono ? "font-mono" : ""}`}>{icon}{value || "—"}</p></div>; }
function Limit({ icon, label, value }: { icon: React.ReactNode; label: string; value: number | null | undefined }) { return <div className="rounded-lg border p-3"><div className="mb-1 flex items-center gap-2 text-muted-foreground">{icon}<span className="text-xs">{label}</span></div><p className="text-lg font-semibold">{value ?? "—"}</p></div>; }
