export type FinancialPlanStatus = "draft" | "active" | "completed" | "cancelled";
export type InstallmentStatus = "scheduled" | "due" | "partial" | "paid" | "overdue" | "cancelled";
export type InsuranceStatus = "active" | "inactive" | "expired" | "pending";
export type InsuranceReconciliationStatus = "not_started" | "ready" | "in_progress" | "reconciled" | "exception";
export type PurchaseOrderStatus = "draft" | "ordered" | "partially_received" | "received" | "cancelled";

export interface FinancialPlan { id: string; tenant_id: string; patient_id: string; treatment_plan_id: string | null; total_amount_subunits: number; insurance_covered_subunits: number; patient_responsibility_subunits: number; currency: string | null; status: FinancialPlanStatus; notes: string | null; created_by: string | null; created_at: string; updated_at: string; }
export interface FinancialInstallment { id: string; tenant_id: string; financial_plan_id: string; installment_no: number; due_date: string; amount_subunits: number; amount_paid_subunits: number; status: InstallmentStatus; invoice_id: string | null; notes: string | null; created_at: string; updated_at: string; }
export interface PatientInsuranceProfile { id: string; tenant_id: string; patient_id: string; payer_name: string; policy_number: string | null; member_number: string | null; coverage_summary: string | null; patient_responsibility_subunits: number | null; status: InsuranceStatus; claim_ready: boolean; reconciliation_status: InsuranceReconciliationStatus; effective_from: string | null; effective_to: string | null; notes: string | null; created_by: string | null; created_at: string; updated_at: string; }
export interface InsuranceClaim { id: string; tenant_id: string; patient_id: string; insurance_profile_id: string; invoice_id: string | null; claim_reference: string | null; amount_claimed_subunits: number; amount_reconciled_subunits: number; status: "prepared" | "submitted" | "paid" | "rejected" | "reconciled" | "exception"; prepared_at: string | null; reconciled_at: string | null; notes: string | null; created_by: string | null; created_at: string; updated_at: string; }
export interface Supplier { id: string; tenant_id: string; name: string; name_ar: string | null; contact_name: string | null; phone: string | null; email: string | null; address: string | null; tax_identifier: string | null; status: "active" | "inactive"; notes: string | null; created_by: string | null; created_at: string; updated_at: string; }
export interface PurchaseOrder { id: string; tenant_id: string; supplier_id: string; order_number: string | null; status: PurchaseOrderStatus; order_date: string; expected_date: string | null; subtotal_subunits: number; tax_subunits: number; total_subunits: number; notes: string | null; created_by: string | null; created_at: string; updated_at: string; }
export interface PurchaseOrderItem { id: string; tenant_id: string; purchase_order_id: string; inventory_item_id: string; quantity_ordered: number; quantity_received: number; unit_cost_subunits: number; line_total_subunits: number; created_at: string; updated_at: string; }
