"use client";

import { useState, useTransition } from "react";
import { useAuth } from "@/core/auth/AuthContext";
import { usePermissions } from "@/core/permissions/usePermissions";
import { useClinicProfile } from "@/domain/settings/settings.queries";
import { updateClinicProfile } from "@/domain/settings/settings.actions";
import { useI18n } from "@/core/i18n/I18nProvider";
import { Button } from "@/shared/components/ui/button";
import { Input } from "@/shared/components/ui/input";
import { Label } from "@/shared/components/ui/label";
import { Textarea } from "@/shared/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Save, Loader2, Building2, Palette, Phone, MapPin, Globe, Landmark } from "lucide-react";

const TIMEZONES = [["UTC", "utc"], ["Asia/Riyadh", "riyadh"], ["Asia/Dubai", "dubai"], ["Asia/Kuwait", "kuwait"], ["Asia/Qatar", "qatar"], ["Asia/Bahrain", "bahrain"], ["Asia/Muscat", "muscat"], ["Asia/Amman", "amman"], ["Asia/Beirut", "beirut"], ["Africa/Cairo", "cairo"], ["Europe/Istanbul", "istanbul"]] as const;
const CURRENCIES = [["SAR", "sar"], ["AED", "aed"], ["KWD", "kwd"], ["QAR", "qar"], ["BHD", "bhd"], ["OMR", "omr"], ["JOD", "jod"], ["USD", "usd"], ["EUR", "eur"], ["GBP", "gbp"], ["EGP", "egp"]] as const;

export function ClinicProfileForm() {
  const { tenantId } = useAuth();
  const { hasPermission, isLoading: permsLoading } = usePermissions();
  const { messages, locale } = useI18n();
  const t = messages.clinicProfile;
  const canUpdate = hasPermission("settings:update");
  const { data: profile, isLoading, error: queryError } = useClinicProfile(tenantId);
  const [isPending, startTransition] = useTransition();
  const [serverError, setServerError] = useState<string | null>(null);
  const [serverSuccess, setServerSuccess] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const tenant = profile?.tenant;
  const defaultBranch = profile?.defaultBranch;
  const [formData, setFormData] = useState({ clinic_name: tenant?.clinic_name ?? "", clinic_name_ar: tenant?.clinic_name_ar ?? "", primary_phone: tenant?.primary_phone ?? "", whatsapp_number: tenant?.whatsapp_number ?? "", address: tenant?.address ?? "", timezone: tenant?.timezone ?? "", currency: tenant?.currency ?? "", logo_url: tenant?.logo_url ?? "", primary_color: tenant?.primary_color ?? "", country_code: tenant?.country_code ?? "" });
  const [syncedTenant, setSyncedTenant] = useState(tenant);
  if (tenant && tenant !== syncedTenant) { setSyncedTenant(tenant); setFormData({ clinic_name: tenant.clinic_name ?? "", clinic_name_ar: tenant.clinic_name_ar ?? "", primary_phone: tenant.primary_phone ?? "", whatsapp_number: tenant.whatsapp_number ?? "", address: tenant.address ?? "", timezone: tenant.timezone ?? "", currency: tenant.currency ?? "", logo_url: tenant.logo_url ?? "", primary_color: tenant.primary_color ?? "", country_code: tenant.country_code ?? "" }); }
  const update = (field: keyof typeof formData, value: string) => { setFormData((p) => ({ ...p, [field]: value })); setServerError(null); setServerSuccess(false); if (errors[field]) setErrors((p) => { const n = { ...p }; delete n[field]; return n; }); };
  const validate = () => { const next: Record<string, string> = {}; if (!formData.clinic_name.trim() || formData.clinic_name.trim().length < 2) next.clinic_name = t.requiredClinicName; setErrors(next); return Object.keys(next).length === 0; };
  const submit = (event: React.FormEvent) => { event.preventDefault(); setServerError(null); setServerSuccess(false); if (!validate()) return; if (!canUpdate) { setServerError(t.accessDenied); return; } const fd = new FormData(); Object.entries(formData).forEach(([key, value]) => fd.append(key, value)); startTransition(async () => { try { const result = await updateClinicProfile(fd); if (result.success) setServerSuccess(true); else setServerError(result.error ?? t.unexpected); } catch { setServerError(t.unexpected); } }); };
  const dir = locale === "ar" ? "rtl" : "ltr";
  if (isLoading || permsLoading) return <div className="flex items-center justify-center py-12" dir={dir}><Loader2 className="me-3 h-6 w-6 animate-spin text-primary" /><span className="text-muted-foreground">{t.loading}</span></div>;
  if (queryError) return <div className="rounded-md bg-destructive/10 p-4 text-center text-destructive" dir={dir}><p className="font-medium">{t.loadError}</p><p className="text-sm">{queryError.message}</p></div>;
  if (!tenant) return <div className="rounded-md border border-muted bg-muted/30 p-8 text-center text-muted-foreground" dir={dir}><Building2 className="mx-auto mb-3 h-10 w-10 opacity-50" /><p>{t.noData}</p></div>;
  return <form onSubmit={submit} className="space-y-6" dir={dir}>
    {serverSuccess && <div className="rounded-md border border-green-200 bg-green-50 p-4 text-green-800">✓ {t.saveSuccess}</div>}
    {serverError && <div className="rounded-md bg-destructive/10 p-4 text-destructive"><p className="font-medium">{t.saveError}</p><p className="text-sm">{serverError}</p></div>}
    <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Building2 className="h-4 w-4" />{t.identity}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="clinic_name">{t.clinicNameEn} <span className="text-destructive">*</span></Label><Input id="clinic_name" value={formData.clinic_name} onChange={(e) => update("clinic_name", e.target.value)} disabled={!canUpdate} placeholder="Zada Dental Clinic" dir="ltr" className={errors.clinic_name ? "border-destructive" : ""} />{errors.clinic_name && <p className="text-xs text-destructive">{errors.clinic_name}</p>}</div><div className="space-y-2"><Label htmlFor="clinic_name_ar">{t.clinicNameAr}</Label><Input id="clinic_name_ar" value={formData.clinic_name_ar} onChange={(e) => update("clinic_name_ar", e.target.value)} disabled={!canUpdate} placeholder="عيادة زادا" dir="rtl" /></div></div></CardContent></Card>
    <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Palette className="h-4 w-4" />{t.visualIdentity}</CardTitle></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="logo_url">{t.logoUrl}</Label><Input id="logo_url" type="url" value={formData.logo_url} onChange={(e) => update("logo_url", e.target.value)} disabled={!canUpdate} placeholder="https://..." dir="ltr" /><p className="text-xs text-muted-foreground">{t.logoUrlHelp}</p></div><div className="space-y-2"><Label htmlFor="primary_color">{t.primaryColor}</Label><div className="flex items-center gap-3"><input id="primary_color" type="color" value={formData.primary_color || "#3b82f6"} onChange={(e) => update("primary_color", e.target.value)} disabled={!canUpdate} className="h-10 w-16 cursor-pointer rounded border border-input" /><Input value={formData.primary_color} onChange={(e) => update("primary_color", e.target.value)} disabled={!canUpdate} placeholder="#3b82f6" dir="ltr" /></div></div></div></CardContent></Card>
    <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Phone className="h-4 w-4" />{t.contact}</CardTitle></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="primary_phone">{t.primaryPhone}</Label><Input id="primary_phone" type="tel" value={formData.primary_phone} onChange={(e) => update("primary_phone", e.target.value)} disabled={!canUpdate} dir="ltr" /></div><div className="space-y-2"><Label htmlFor="whatsapp_number">{t.whatsapp}</Label><Input id="whatsapp_number" type="tel" value={formData.whatsapp_number} onChange={(e) => update("whatsapp_number", e.target.value)} disabled={!canUpdate} dir="ltr" /></div></div></CardContent></Card>
    <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><MapPin className="h-4 w-4" />{t.addressSection}</CardTitle></CardHeader><CardContent><div className="space-y-4"><div className="space-y-2"><Label htmlFor="address">{t.address}</Label><Textarea id="address" value={formData.address} onChange={(e) => update("address", e.target.value)} disabled={!canUpdate} placeholder={t.addressPlaceholder} rows={3} /></div><div className="space-y-2 max-w-xs"><Label htmlFor="country_code">{t.countryCode}</Label><Input id="country_code" value={formData.country_code} onChange={(e) => update("country_code", e.target.value)} disabled={!canUpdate} maxLength={2} dir="ltr" /></div></div></CardContent></Card>
    <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Globe className="h-4 w-4" />{t.regionalFinancial}</CardTitle></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="timezone">{t.timezone}</Label><Select value={formData.timezone || undefined} onValueChange={(v) => update("timezone", v)} disabled={!canUpdate}><SelectTrigger id="timezone"><SelectValue placeholder={t.chooseTimezone} /></SelectTrigger><SelectContent>{TIMEZONES.map(([value, key]) => <SelectItem key={value} value={value}>{t.timezoneOptions[key]}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="currency">{t.currency}</Label><Select value={formData.currency || undefined} onValueChange={(v) => update("currency", v)} disabled={!canUpdate}><SelectTrigger id="currency"><SelectValue placeholder={t.chooseCurrency} /></SelectTrigger><SelectContent>{CURRENCIES.map(([value, key]) => <SelectItem key={value} value={value}>{t.currencies[key]}</SelectItem>)}</SelectContent></Select></div></div></CardContent></Card>
    {defaultBranch && <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Landmark className="h-4 w-4" />{t.defaultBranch}</CardTitle></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2 text-sm"><div><span className="text-muted-foreground">{t.branchName}</span><p className="font-medium">{defaultBranch.branch_name}</p></div>{defaultBranch.branch_name_ar && <div><span className="text-muted-foreground">{t.branchNameAr}</span><p className="font-medium">{defaultBranch.branch_name_ar}</p></div>}{defaultBranch.phone && <div><span className="text-muted-foreground">{t.phone}</span><p className="font-medium" dir="ltr">{defaultBranch.phone}</p></div>}{defaultBranch.address && <div><span className="text-muted-foreground">{t.address}</span><p className="font-medium">{defaultBranch.address}</p></div>}</div></CardContent></Card>}
    {canUpdate ? <div className="flex justify-end pt-2"><Button type="submit" disabled={isPending} className="gap-2">{isPending ? <><Loader2 className="h-4 w-4 animate-spin" />{messages.common.saving}</> : <><Save className="h-4 w-4" />{messages.common.save}</>}</Button></div> : <div className="rounded-md border border-yellow-200 bg-yellow-50 p-4 text-yellow-800 text-sm">{t.accessDenied}</div>}
  </form>;
}
