"use client";
import {useState,useTransition} from "react";
import {useAuth} from "@/core/auth/AuthContext";
import {Button} from "@/shared/components/ui/button"; import {Input} from "@/shared/components/ui/input"; import {Label} from "@/shared/components/ui/label"; import {Textarea} from "@/shared/components/ui/textarea";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/shared/components/ui/dialog"; import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/shared/components/ui/select"; import {Save,Loader2} from "lucide-react";
import {createPatient,updatePatient} from "@/domain/patients/patients.actions"; import type {Patient} from "@/domain/patients/patients.types"; import {useI18n} from "@/core/i18n/I18nProvider";
interface PatientFormProps{patient?:Patient|null;isOpen:boolean;onClose:()=>void;onSuccess?:()=>void;}
export function PatientForm({patient,isOpen,onClose,onSuccess}:PatientFormProps){
 const {tenantId}=useAuth(); const [isPending,startTransition]=useTransition(); const [errors,setErrors]=useState<Record<string,string>>({}); const [serverError,setServerError]=useState<string|null>(null); const {messages}=useI18n(); const t=messages.patients;
 const [formData,setFormData]=useState({first_name:patient?.first_name||"",last_name:patient?.last_name||"",first_name_ar:patient?.first_name_ar||"",last_name_ar:patient?.last_name_ar||"",phone_primary:patient?.phone_primary||"",phone_secondary:patient?.phone_secondary||"",email:patient?.email||"",date_of_birth:patient?.date_of_birth||"",gender:patient?.gender||"",preferred_channel:patient?.preferred_channel||"whatsapp",referral_source:patient?.referral_source||"",patient_status:patient?.patient_status||"active",notes:patient?.notes||""});
 const validate=()=>{const e:Record<string,string>={};if(!formData.first_name.trim())e.first_name=t.requiredFirst;if(!formData.last_name.trim())e.last_name=t.requiredLast;if(!formData.phone_primary.trim())e.phone_primary=t.requiredPhone;setErrors(e);return !Object.keys(e).length;};
 const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setServerError(null);if(!validate())return;if(!tenantId){setServerError(t.clinicNotFound);return;}const form=new FormData();Object.entries({...formData,tenant_id:tenantId,...(patient?{id:patient.id}:{})}).forEach(([k,v])=>form.append(k,v));startTransition(async()=>{try{const result=patient?await updatePatient(form):await createPatient(form);if(result.error)setServerError(result.error);else{onSuccess?.();onClose();}}catch{setServerError(t.unexpected);}});};
 const handleChange=(field:string,value:string)=>{setFormData(p=>({...p,[field]:value}));if(errors[field])setErrors(p=>{const n={...p};delete n[field];return n;});};
 return <Dialog open={isOpen} onOpenChange={o=>!o&&onClose()}><DialogContent className="w-[calc(100vw-1rem)] max-w-2xl max-h-[90dvh] overflow-y-auto p-3 sm:w-[calc(100vw-2rem)] sm:p-6"><DialogHeader><DialogTitle>{patient?t.editTitle:t.newTitle}</DialogTitle><DialogDescription>{patient?t.editDescription:t.newDescription}</DialogDescription></DialogHeader><form onSubmit={handleSubmit} className="space-y-4">
 {serverError&&<div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive text-center">{serverError}</div>}
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field id="first_name" label={t.firstName} required value={formData.first_name} error={errors.first_name} onChange={v=>handleChange("first_name",v)}/><Field id="last_name" label={t.lastName} required value={formData.last_name} error={errors.last_name} onChange={v=>handleChange("last_name",v)}/></div>
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field id="first_name_ar" label={t.firstNameAr} value={formData.first_name_ar} onChange={v=>handleChange("first_name_ar",v)}/><Field id="last_name_ar" label={t.lastNameAr} value={formData.last_name_ar} onChange={v=>handleChange("last_name_ar",v)}/></div>
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field id="phone_primary" label={t.primaryPhone} required value={formData.phone_primary} error={errors.phone_primary} onChange={v=>handleChange("phone_primary",v)} type="tel"/><Field id="phone_secondary" label={t.secondaryPhone} value={formData.phone_secondary} onChange={v=>handleChange("phone_secondary",v)} type="tel"/></div>
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field id="email" label={t.email} value={formData.email} onChange={v=>handleChange("email",v)} type="email"/><Field id="date_of_birth" label={t.dob} value={formData.date_of_birth} onChange={v=>handleChange("date_of_birth",v)} type="date"/></div>
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><SelectField label={t.gender} placeholder={t.chooseGender} value={formData.gender} onChange={v=>handleChange("gender",v)} items={[["male",t.male],["female",t.female],["other",t.other]]}/><SelectField label={t.preferredChannel} placeholder={t.chooseChannel} value={formData.preferred_channel} onChange={v=>handleChange("preferred_channel",v)} items={[["whatsapp",t.whatsapp],["sms",t.sms],["email",t.emailChannel],["phone",t.phoneChannel]]}/></div>
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field id="referral_source" label={t.referralSource} value={formData.referral_source} onChange={v=>handleChange("referral_source",v)} placeholder={t.referralPlaceholder}/><SelectField label={t.status} placeholder={t.chooseStatus} value={formData.patient_status} onChange={v=>handleChange("patient_status",v)} items={[["active",t.active],["inactive",t.inactive],["archived",t.archived],["blocked",t.blocked]]}/></div>
 <div className="space-y-2"><Label htmlFor="notes">{t.notes}</Label><Textarea id="notes" value={formData.notes} onChange={e=>handleChange("notes",e.target.value)} placeholder={t.notesPlaceholder} rows={3}/></div>
 <div className="flex flex-col-reverse sm:flex-row justify-end gap-2 pt-4"><Button variant="outline" onClick={onClose} type="button" disabled={isPending}>{t.cancel}</Button><Button type="submit" disabled={isPending}>{isPending?<><Loader2 className="w-4 h-4 ml-2 animate-spin"/>{t.saving}</>:<><Save className="w-4 h-4 ml-2"/>{t.save}</>}</Button></div>
 </form></DialogContent></Dialog>;
}
function Field({id,label,required,value,error,onChange,type="text",placeholder}:{id:string;label:string;required?:boolean;value:string;error?:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <div className="space-y-2"><Label htmlFor={id}>{label}{required?" *":""}</Label><Input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={error?"border-destructive":""}/>{error&&<p className="text-sm text-destructive">{error}</p>}</div>}
function SelectField({label,placeholder,value,onChange,items}:{label:string;placeholder:string;value:string;onChange:(v:string)=>void;items:[string,string][]}){return <div className="space-y-2"><Label>{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{items.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>}
