"use client";

import { useState } from "react";
import { usePatientById, usePatientHistory } from "@/domain/patients/patients.queries";
import { usePermissions } from "@/core/permissions/usePermissions";
import { Button } from "@/shared/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Badge } from "@/shared/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/shared/components/ui/dialog";
import { User, Phone, Mail, Calendar, MapPin, FileText, ArrowLeft, Edit, History, TrendingUp, AlertTriangle, LogIn } from "lucide-react";
import { checkInPatient } from "@/domain/queue/queue.actions";
import { PatientForm } from "./patient-form";
import { MedicalFilesPanel } from "@/features/medical-files/ui/MedicalFilesPanel";

interface PatientDetailProps { patientId: string | null; isOpen: boolean; onClose: () => void; onBookAppointment?: (patientId: string) => void; }

export function PatientDetail({ patientId, isOpen, onClose, onBookAppointment }: PatientDetailProps) {
  const { data: patient, isLoading: patientLoading } = usePatientById(patientId); const { data: history, isLoading: historyLoading } = usePatientHistory(patientId); const { hasPermission, isLoading: permsLoading } = usePermissions(); const [showEditForm, setShowEditForm] = useState(false); const [isCheckingIn, setIsCheckingIn] = useState(false); const [checkInError, setCheckInError] = useState("");
  const getStatusBadge = (status: string) => { const variants: Record<string, "default" | "secondary" | "destructive" | "outline"> = { active: "default", inactive: "secondary", archived: "outline", blocked: "destructive" }; const labels: Record<string, string> = { active: "نشط", inactive: "غير نشط", archived: "مؤرشف", blocked: "محظور" }; return <Badge variant={variants[status] || "default"}>{labels[status] || status}</Badge>; };
  const getGenderLabel = (gender?: string) => ({ male: "ذكر", female: "أنثى", other: "آخر" } as Record<string, string>)[gender || ""] || "—";
  const getChannelLabel = (channel?: string) => ({ whatsapp: "واتساب", sms: "رسائل نصية", email: "بريد", phone: "هاتف" } as Record<string, string>)[channel || ""] || "—";
  const formatDate = (dateStr?: string) => { if (!dateStr) return "—"; try { return new Date(dateStr).toLocaleDateString("ar-SA"); } catch { return dateStr; } };
  async function handleCheckIn() { if (!patient) return; setIsCheckingIn(true); setCheckInError(""); try { await checkInPatient({ patient_id: patient.id }); onClose(); } catch (err: any) { setCheckInError(err.message || "فشل تسجيل الحضور"); } finally { setIsCheckingIn(false); } }
  function handleBookAppointment() { if (!patient || !onBookAppointment) return; onBookAppointment(patient.id); onClose(); }
  if (showEditForm && patient) return <PatientForm patient={patient} isOpen={showEditForm} onClose={() => setShowEditForm(false)} onSuccess={() => setShowEditForm(false)} />;
  return <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
    <DialogContent className="w-[calc(100vw-1rem)] max-w-5xl max-h-[92dvh] overflow-x-hidden overflow-y-auto p-3 sm:w-[calc(100vw-2rem)] sm:p-6">
      <DialogHeader className="min-w-0 pr-7"><DialogTitle className="flex min-w-0 items-center gap-2 text-base sm:text-lg"><Button variant="ghost" size="icon" onClick={onClose} className="h-8 w-8 shrink-0"><ArrowLeft className="h-4 w-4" /></Button><span className="truncate">تفاصيل المريض</span></DialogTitle><DialogDescription className="text-xs sm:text-sm">عرض بيانات المريض وتاريخه وملفاته الطبية</DialogDescription></DialogHeader>
      {patientLoading ? <div className="py-8 text-center text-muted-foreground">جاري التحميل...</div> : !patient ? <div className="py-8 text-center text-muted-foreground">لم يتم العثور على المريض</div> : <div className="min-w-0 space-y-4 sm:space-y-6">
        <Card className="min-w-0"><CardContent className="pt-5 sm:pt-6"><div className="flex min-w-0 flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex min-w-0 items-center gap-3 sm:gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-primary/10 sm:h-16 sm:w-16"><span className="text-lg font-bold text-primary sm:text-xl">{patient.first_name[0]}{patient.last_name[0]}</span></div><div className="min-w-0"><h3 className="truncate text-lg font-semibold sm:text-xl">{patient.first_name} {patient.last_name}</h3>{patient.first_name_ar && patient.last_name_ar && <p className="truncate text-sm text-muted-foreground">{patient.first_name_ar} {patient.last_name_ar}</p>}<div className="mt-2">{getStatusBadge(patient.patient_status)}</div></div></div><div className="flex w-full flex-wrap gap-2 lg:w-auto">{!permsLoading && hasPermission("agenda:create") && onBookAppointment && <Button className="min-h-10 flex-1 lg:flex-none" variant="outline" size="sm" onClick={handleBookAppointment}><Calendar className="ml-2 h-4 w-4" />حجز موعد</Button>}{!permsLoading && hasPermission("sessions:create") && <Button className="min-h-10 flex-1 lg:flex-none" variant="default" size="sm" onClick={handleCheckIn} disabled={isCheckingIn}><LogIn className="ml-2 h-4 w-4" />{isCheckingIn ? "جاري..." : "تسجيل في الطابور"}</Button>}{!permsLoading && hasPermission("patients:update") && <Button className="min-h-10 flex-1 lg:flex-none" variant="outline" size="sm" onClick={() => setShowEditForm(true)}><Edit className="ml-2 h-4 w-4" />تعديل</Button>}</div></div></CardContent></Card>
        {checkInError && <div className="break-words rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{checkInError}</div>}
        <Card className="min-w-0"><CardHeader className="px-4 py-4 sm:px-6"><CardTitle className="flex items-center gap-2 text-sm sm:text-base"><Phone className="h-4 w-4 shrink-0" />معلومات التواصل</CardTitle></CardHeader><CardContent className="space-y-3 px-4 pb-4 sm:px-6 sm:pb-6"><div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2"><div className="flex min-w-0 items-center gap-2"><Phone className="h-4 w-4 shrink-0 text-muted-foreground" /><span className="shrink-0 text-xs text-muted-foreground sm:text-sm">الهاتف:</span><span className="min-w-0 break-all text-sm font-medium">{patient.phone_primary}</span></div>{patient.phone_secondary && <div className="flex min-w-0 items-center gap-2"><Phone className="h-4 w-4 shrink-0 text-muted-foreground" /><span className="shrink-0 text-xs text-muted-foreground sm:text-sm">الثانوي:</span><span className="min-w-0 break-all text-sm font-medium">{patient.phone_secondary}</span></div>}{patient.email && <div className="flex min-w-0 items-center gap-2"><Mail className="h-4 w-4 shrink-0 text-muted-foreground" /><span className="shrink-0 text-xs text-muted-foreground sm:text-sm">البريد:</span><span className="min-w-0 break-all text-sm font-medium">{patient.email}</span></div>}<div className="flex min-w-0 items-center gap-2"><User className="h-4 w-4 shrink-0 text-muted-foreground" /><span className="shrink-0 text-xs text-muted-foreground sm:text-sm">القناة:</span><span className="min-w-0 truncate text-sm font-medium">{getChannelLabel(patient.preferred_channel)}</span></div></div></CardContent></Card>
        <Card className="min-w-0"><CardHeader className="px-4 py-4 sm:px-6"><CardTitle className="flex items-center gap-2 text-sm sm:text-base"><FileText className="h-4 w-4 shrink-0" />البيانات الشخصية</CardTitle></CardHeader><CardContent className="space-y-3 px-4 pb-4 sm:px-6 sm:pb-6"><div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2"><div className="flex min-w-0 items-center gap-2"><Calendar className="h-4 w-4 shrink-0 text-muted-foreground" /><span className="shrink-0 text-xs text-muted-foreground sm:text-sm">الميلاد:</span><span className="min-w-0 text-sm font-medium">{formatDate(patient.date_of_birth)}</span></div><div className="flex min-w-0 items-center gap-2"><User className="h-4 w-4 shrink-0 text-muted-foreground" /><span className="shrink-0 text-xs text-muted-foreground sm:text-sm">الجنس:</span><span className="min-w-0 text-sm font-medium">{getGenderLabel(patient.gender)}</span></div>{patient.referral_source && <div className="flex min-w-0 items-center gap-2"><MapPin className="h-4 w-4 shrink-0 text-muted-foreground" /><span className="shrink-0 text-xs text-muted-foreground sm:text-sm">الإحالة:</span><span className="min-w-0 truncate text-sm font-medium">{patient.referral_source}</span></div>}<div className="flex min-w-0 items-center gap-2"><Calendar className="h-4 w-4 shrink-0 text-muted-foreground" /><span className="shrink-0 text-xs text-muted-foreground sm:text-sm">التسجيل:</span><span className="min-w-0 text-sm font-medium">{formatDate(patient.created_at)}</span></div></div></CardContent></Card>
        {patient.notes && <Card className="min-w-0"><CardHeader className="px-4 py-4 sm:px-6"><CardTitle className="flex items-center gap-2 text-sm sm:text-base"><FileText className="h-4 w-4" />ملاحظات</CardTitle></CardHeader><CardContent className="px-4 pb-4 sm:px-6 sm:pb-6"><p className="break-words whitespace-pre-wrap text-sm">{patient.notes}</p></CardContent></Card>}
        <Card className="min-w-0"><CardHeader className="px-4 py-4 sm:px-6"><CardTitle className="flex items-center gap-2 text-sm sm:text-base"><History className="h-4 w-4" />تاريخ المريض</CardTitle></CardHeader><CardContent className="px-4 pb-4 sm:px-6 sm:pb-6">{historyLoading ? <div className="py-4 text-center text-muted-foreground">جاري التحميل...</div> : !history ? <div className="py-4 text-center text-muted-foreground">لا يوجد تاريخ مسجل</div> : <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-4"><div className="rounded-lg bg-muted p-3 text-center"><TrendingUp className="mx-auto mb-1 h-5 w-5 text-primary" /><div className="text-base font-bold sm:text-lg">{history.total_visits || 0}</div><div className="text-xs text-muted-foreground">عدد الزيارات</div></div><div className="rounded-lg bg-muted p-3 text-center"><Calendar className="mx-auto mb-1 h-5 w-5 text-primary" /><div className="truncate text-base font-bold sm:text-lg">{formatDate(history.last_visit_date)}</div><div className="text-xs text-muted-foreground">آخر زيارة</div></div><div className="rounded-lg bg-muted p-3 text-center"><FileText className="mx-auto mb-1 h-5 w-5 text-primary" /><div className="truncate text-base font-bold sm:text-lg">{history.preferred_procedure || "—"}</div><div className="text-xs text-muted-foreground">الإجراء المفضل</div></div><div className="rounded-lg bg-muted p-3 text-center"><AlertTriangle className="mx-auto mb-1 h-5 w-5 text-primary" /><div className="truncate text-base font-bold sm:text-lg">{history.retention_risk || "—"}</div><div className="text-xs text-muted-foreground">مخاطر الاحتفاظ</div></div></div>}</CardContent></Card>
        <MedicalFilesPanel patientId={patient.id} />
      </div>}
    </DialogContent>
  </Dialog>;
}
