"use client";
import { useState } from "react";
import { usePatientById, usePatientHistory } from "@/domain/patients/patients.queries";
import { usePermissions } from "@/core/permissions/usePermissions";
import { useI18n } from "@/core/i18n/I18nProvider";
import { Button } from "@/shared/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Badge } from "@/shared/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/shared/components/ui/dialog";
import { User, Phone, Mail, Calendar, MapPin, FileText, ArrowLeft, Edit, History, TrendingUp, AlertTriangle, LogIn } from "lucide-react";
import { checkInPatient } from "@/domain/queue/queue.actions";
import { PatientForm } from "./patient-form";
import { MedicalFilesPanel } from "@/features/medical-files/ui/MedicalFilesPanel";
interface PatientDetailProps { patientId: string | null; isOpen: boolean; onClose: () => void; onBookAppointment?: (patientId: string) => void; }
export function PatientDetail({ patientId, isOpen, onClose, onBookAppointment }: PatientDetailProps) {
  const { locale, messages } = useI18n(); const t = messages.patients; const { data: patient, isLoading: patientLoading } = usePatientById(patientId); const { data: history, isLoading: historyLoading } = usePatientHistory(patientId); const { hasPermission, isLoading: permsLoading } = usePermissions(); const [showEditForm, setShowEditForm] = useState(false); const [isCheckingIn, setIsCheckingIn] = useState(false); const [checkInError, setCheckInError] = useState(""); const dateLocale = locale === "ar" ? "ar-SA" : "en-US";
  const getStatusBadge = (status: string) => { const variants: Record<string, "default" | "secondary" | "destructive" | "outline"> = { active: "default", inactive: "secondary", archived: "outline", blocked: "destructive" }; const labels: Record<string, string> = { active: t.active, inactive: t.inactive, archived: t.archived, blocked: t.blocked }; return <Badge variant={variants[status] || "default"}>{labels[status] || status}</Badge>; };
  const getGenderLabel = (gender?: string) => ({ male: t.male, female: t.female, other: t.other } as Record<string, string>)[gender || ""] || "—"; const getChannelLabel = (channel?: string) => ({ whatsapp: t.whatsapp, sms: t.sms, email: t.emailChannel, phone: t.phoneChannel } as Record<string, string>)[channel || ""] || "—";
  const formatDate = (dateStr?: string) => { if (!dateStr) return "—"; try { return new Date(dateStr).toLocaleDateString(dateLocale); } catch { return dateStr; } };
  async function handleCheckIn() { if (!patient) return; setIsCheckingIn(true); setCheckInError(""); try { await checkInPatient({ patient_id: patient.id }); onClose(); } catch (err) { setCheckInError(err instanceof Error ? err.message : t.checkInFailed); } finally { setIsCheckingIn(false); } }
  if (showEditForm && patient) return <PatientForm patient={patient} isOpen={showEditForm} onClose={() => setShowEditForm(false)} onSuccess={() => setShowEditForm(false)} />;
  return <Dialog open={isOpen} onOpenChange={open => !open && onClose()}><DialogContent className="w-[calc(100vw-1rem)] max-w-5xl max-h-[92dvh] overflow-x-hidden overflow-y-auto p-3 sm:w-[calc(100vw-2rem)] sm:p-6" dir={locale === "ar" ? "rtl" : "ltr"}><DialogHeader className="min-w-0"><DialogTitle className="flex min-w-0 items-center gap-2 text-base sm:text-lg"><Button variant="ghost" size="icon" onClick={onClose} className="h-8 w-8 shrink-0" aria-label={t.cancel}><ArrowLeft className="h-4 w-4" /></Button><span className="truncate">{t.details}</span></DialogTitle><DialogDescription className="text-xs sm:text-sm">{t.description}</DialogDescription></DialogHeader>{patientLoading ? <div className="py-8 text-center text-muted-foreground">{t.loading}</div> : !patient ? <div className="py-8 text-center text-muted-foreground">{t.notFound}</div> : <div className="min-w-0 space-y-4 sm:space-y-6">
    <Card><CardContent className="pt-5 sm:pt-6"><div className="flex min-w-0 flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex min-w-0 items-center gap-3 sm:gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-primary/10 sm:h-16 sm:w-16"><span className="text-lg font-bold text-primary sm:text-xl">{patient.first_name[0]}{patient.last_name[0]}</span></div><div className="min-w-0"><h3 className="truncate text-lg font-semibold sm:text-xl">{patient.first_name} {patient.last_name}</h3>{patient.first_name_ar && patient.last_name_ar && <p className="truncate text-sm text-muted-foreground">{patient.first_name_ar} {patient.last_name_ar}</p>}<div className="mt-2">{getStatusBadge(patient.patient_status)}</div></div></div><div className="flex w-full flex-wrap gap-2 lg:w-auto">{!permsLoading && hasPermission("agenda:create") && onBookAppointment && <Button className="min-h-10 flex-1 lg:flex-none" variant="outline" size="sm" onClick={() => { onBookAppointment(patient.id); onClose(); }}><Calendar className="me-2 h-4 w-4" />{t.appointment}</Button>}{!permsLoading && hasPermission("sessions:create") && <Button className="min-h-10 flex-1 lg:flex-none" size="sm" onClick={() => void handleCheckIn()} disabled={isCheckingIn}><LogIn className="me-2 h-4 w-4" />{isCheckingIn ? t.checkingIn : t.queue}</Button>}{!permsLoading && hasPermission("patients:update") && <Button className="min-h-10 flex-1 lg:flex-none" variant="outline" size="sm" onClick={() => setShowEditForm(true)}><Edit className="me-2 h-4 w-4" />{t.edit}</Button>}</div></div></CardContent></Card>
    {checkInError && <div className="break-words rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{checkInError}</div>}
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm sm:text-base"><Phone className="h-4 w-4" />{t.contact}</CardTitle></CardHeader><CardContent><div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2"><div className="flex gap-2"><Phone className="h-4 w-4 shrink-0 text-muted-foreground" /><span>{t.phone}</span><span className="break-all font-medium">{patient.phone_primary}</span></div>{patient.phone_secondary && <div className="flex gap-2"><Phone className="h-4 w-4 shrink-0 text-muted-foreground" /><span>{t.secondary}</span><span className="break-all font-medium">{patient.phone_secondary}</span></div>}{patient.email && <div className="flex gap-2"><Mail className="h-4 w-4 shrink-0 text-muted-foreground" /><span>{t.email}</span><span className="break-all font-medium">{patient.email}</span></div>}<div className="flex gap-2"><User className="h-4 w-4 shrink-0 text-muted-foreground" /><span>{t.channel}</span><span className="truncate font-medium">{getChannelLabel(patient.preferred_channel)}</span></div></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm sm:text-base"><FileText className="h-4 w-4" />{t.personal}</CardTitle></CardHeader><CardContent><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><div className="flex gap-2"><Calendar className="h-4 w-4 shrink-0 text-muted-foreground" /><span>{t.birth}</span><span className="font-medium">{formatDate(patient.date_of_birth)}</span></div><div className="flex gap-2"><User className="h-4 w-4 shrink-0 text-muted-foreground" /><span>{t.gender}</span><span className="font-medium">{getGenderLabel(patient.gender)}</span></div>{patient.referral_source && <div className="flex gap-2"><MapPin className="h-4 w-4 shrink-0 text-muted-foreground" /><span>{t.referral}</span><span className="truncate font-medium">{patient.referral_source}</span></div>}<div className="flex gap-2"><Calendar className="h-4 w-4 shrink-0 text-muted-foreground" /><span>{t.registered}</span><span className="font-medium">{formatDate(patient.created_at)}</span></div></div></CardContent></Card>
    {patient.notes && <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm sm:text-base"><FileText className="h-4 w-4" />{t.notes}</CardTitle></CardHeader><CardContent><p className="break-words whitespace-pre-wrap text-sm">{patient.notes}</p></CardContent></Card>}
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm sm:text-base"><History className="h-4 w-4" />{t.history}</CardTitle></CardHeader><CardContent>{historyLoading ? <div className="py-4 text-center text-muted-foreground">{t.loading}</div> : !history ? <div className="py-4 text-center text-muted-foreground">{t.noHistory}</div> : <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-lg bg-muted p-3 text-center"><TrendingUp className="mx-auto mb-1 h-5 w-5" /><div className="text-base font-bold">{history.total_visits || 0}</div><div className="text-xs text-muted-foreground">{t.visits}</div></div><div className="rounded-lg bg-muted p-3 text-center"><Calendar className="mx-auto mb-1 h-5 w-5" /><div className="truncate text-base font-bold">{formatDate(history.last_visit_date)}</div><div className="text-xs text-muted-foreground">{t.lastVisit}</div></div><div className="rounded-lg bg-muted p-3 text-center"><FileText className="mx-auto mb-1 h-5 w-5" /><div className="truncate text-base font-bold">{history.preferred_procedure || "—"}</div><div className="text-xs text-muted-foreground">{t.preferredProcedure}</div></div><div className="rounded-lg bg-muted p-3 text-center"><AlertTriangle className="mx-auto mb-1 h-5 w-5" /><div className="truncate text-base font-bold">{history.retention_risk || "—"}</div><div className="text-xs text-muted-foreground">{t.retentionRisk}</div></div></div>}</CardContent></Card><MedicalFilesPanel patientId={patient.id} /></div>}</DialogContent></Dialog>;
}
