import type { Locale } from "./messages";

export const adminMessages = {
  ar: {
    users: { title: "إدارة المستخدمين", count: "مستخدمون", newUser: "مستخدم جديد", user: "المستخدم", role: "الدور", status: "الحالة", createdAt: "تاريخ الإنشاء", actions: "الإجراءات", noUsers: "لا يوجد مستخدمون مسجلون", pendingAuth: "بانتظار إنشاء الحساب", active: "نشط", inactive: "معطل", loading: "جاري التحميل...", loadFailed: "فشل تحميل المستخدمين", createDescription: "إنشاء مستخدم جديد للعيادة. سيتم إنشاء حساب المصادقة لاحقاً.", fullName: "الاسم الكامل", email: "البريد الإلكتروني", phone: "رقم الهاتف", chooseRole: "اختر الدور", cancel: "إلغاء", create: "إنشاء المستخدم", creating: "جاري الإنشاء...", editTitle: "تعديل المستخدم", save: "حفظ التعديلات", saving: "جاري الحفظ...", placeholderName: "الاسم الكامل", placeholderPhone: "05xxxxxxxx", noRole: "لا يوجد دور", actionFailed: "تعذر تنفيذ العملية" },
    overrides: { title: "تجاوزات الصلاحيات", description: "تخصيص الصلاحيات الفعلية للمستخدمين داخل العيادة.", user: "المستخدم", permission: "الصلاحية", grant: "منح", revoke: "سحب", inherited: "موروثة", override: "تجاوز", save: "حفظ التغييرات", saving: "جاري الحفظ...", loading: "جاري التحميل...", loadFailed: "فشل تحميل تجاوزات الصلاحيات", saveFailed: "فشل حفظ تجاوز الصلاحية", noUsers: "لا يوجد مستخدمون", noPermissions: "لا توجد صلاحيات", accessDenied: "ليس لديك صلاحية إدارة تجاوزات الصلاحيات.", close: "إغلاق", defaultFromRole: "افتراضي (من الدور)", additionalGrant: "منح إضافي", permissionRevoke: "سحب صلاحية", saved: "تم الحفظ بنجاح", saveError: "تعذر حفظ التغييرات", groupDescriptions: { patients: "إدارة سجلات المرضى", sessions: "إدارة الجلسات والزيارات", agenda: "المواعيد والتقويم", invoices: "الفوترة والمدفوعات", inventory: "إدارة المخزون والمستلزمات", analytics: "التقارير التحليلية", users: "إدارة مستخدمي العيادة", settings: "إعدادات العيادة", audit: "سجل النشاط والتدقيق", reports: "التقارير التشغيلية", followup: "متابعة ما بعد الزيارة", roles: "إدارة الأدوار والصلاحيات", templates: "قوالب الصلاحيات", overrides: "تجاوزات الصلاحيات الفردية", subscription: "معلومات الاشتراك", notifications: "إعدادات التنبيهات", procedures: "إدارة كتالوج الخدمات والإجراءات" }, groups: { patients: "المرضى", sessions: "الجلسات", agenda: "الأجندة", invoices: "الفواتير", inventory: "المخزون", analytics: "التحليلات", users: "المستخدمون", settings: "الإعدادات", audit: "السجل", reports: "التقارير", followup: "المتابعة", roles: "الأدوار", templates: "القوالب", overrides: "التجاوزات", subscription: "الاشتراك", notifications: "التنبيهات", procedures: "الخدمات الطبية" }, actions: { read: "عرض", create: "إنشاء", update: "تعديل", delete: "حذف", manage: "إدارة" } },
    agenda: { previous: "السابق", next: "التالي", today: "اليوم", time: "الوقت", unknownPatient: "غير معروف", doctorPrefix: "د.", scheduled: "مجدول", confirmed: "مؤكد", arrived: "حضر", inSession: "في الجلسة", completed: "مكتمل", noShow: "لم يحضر", cancelled: "ملغى", rescheduled: "أعيدت جدولته" },
    subscription: { title: "الاشتراك", description: "إدارة خطة الاشتراك وحالة الخدمات المتاحة للعيادة.", currentPlan: "الخطة الحالية", status: "الحالة", active: "نشط", inactive: "غير نشط", plan: "الخطة", renewal: "التجديد", activationCode: "رمز التفعيل", apply: "تطبيق", applying: "جاري التطبيق...", notImplemented: "تفعيل رمز الاشتراك غير متاح بعد.", loading: "جاري تحميل الاشتراك...", loadFailed: "فشل تحميل بيانات الاشتراك", accessDenied: "ليس لديك صلاحية عرض بيانات الاشتراك." },
    audit: { title: "سجل النشاط", description: "مراجعة نشاط العيادة والأحداث المسجلة.", timestamp: "الوقت", actor: "المستخدم", role: "الدور", action: "الإجراء", resource: "المورد", noEntries: "لا توجد أحداث مسجلة", loading: "جاري تحميل سجل النشاط...", loadFailed: "فشل تحميل سجل النشاط", accessDenied: "ليس لديك صلاحية عرض سجل النشاط.", unknown: "غير معروف" },
    settings: { title: "الإعدادات", overview: "نظرة عامة", description: "اختر قسماً من الأقسام أعلاه لإدارة إعدادات العيادة.", clinic: "إعدادات العيادة", users: "المستخدمون", roles: "الأدوار والصلاحيات", overrides: "تجاوزات الصلاحيات", templates: "القوالب", preferences: "التفضيلات", notifications: "الإشعارات", subscription: "الاشتراك", audit: "سجل النشاط", procedures: "الخدمات الطبية", save: "حفظ", cancel: "إلغاء" }
  },
  en: {
    users: { title: "User Management", count: "users", newUser: "New User", user: "User", role: "Role", status: "Status", createdAt: "Created", actions: "Actions", noUsers: "No registered users", pendingAuth: "Awaiting account creation", active: "Active", inactive: "Disabled", loading: "Loading...", loadFailed: "Failed to load users", createDescription: "Create a new clinic user. The authentication account will be provisioned separately.", fullName: "Full name", email: "Email", phone: "Phone number", chooseRole: "Choose role", cancel: "Cancel", create: "Create user", creating: "Creating...", editTitle: "Edit user", save: "Save changes", saving: "Saving...", placeholderName: "Full name", placeholderPhone: "05xxxxxxxx", noRole: "No role", actionFailed: "Unable to complete the operation" },
    overrides: { title: "Permission Overrides", description: "Customize effective permissions for users in the clinic.", user: "User", permission: "Permission", grant: "Grant", revoke: "Revoke", inherited: "Inherited", override: "Override", save: "Save changes", saving: "Saving...", loading: "Loading...", loadFailed: "Failed to load permission overrides", saveFailed: "Failed to save permission override", noUsers: "No users found", noPermissions: "No permissions found", accessDenied: "You do not have permission to manage permission overrides.", close: "Close", defaultFromRole: "Default (from role)", additionalGrant: "Additional grant", permissionRevoke: "Permission revoke", saved: "Changes saved successfully", saveError: "Unable to save changes", groupDescriptions: { patients: "Manage patient records", sessions: "Manage sessions and visits", agenda: "Appointments and calendar", invoices: "Billing and payments", inventory: "Inventory and supplies", analytics: "Analytics and reporting", users: "Manage clinic users", settings: "Clinic settings", audit: "Activity and audit log", reports: "Operational reports", followup: "Post-visit follow-up", roles: "Manage roles and permissions", templates: "Permission templates", overrides: "Individual permission overrides", subscription: "Subscription information", notifications: "Notification settings", procedures: "Manage service and procedure catalog" }, groups: { patients: "Patients", sessions: "Sessions", agenda: "Agenda", invoices: "Invoices", inventory: "Inventory", analytics: "Analytics", users: "Users", settings: "Settings", audit: "Audit", reports: "Reports", followup: "Follow-up", roles: "Roles", templates: "Templates", overrides: "Overrides", subscription: "Subscription", notifications: "Notifications", procedures: "Medical Services" }, actions: { read: "View", create: "Create", update: "Edit", delete: "Delete", manage: "Manage" } },
    agenda: { previous: "Previous", next: "Next", today: "Today", time: "Time", unknownPatient: "Unknown", doctorPrefix: "Dr.", scheduled: "Scheduled", confirmed: "Confirmed", arrived: "Arrived", inSession: "In session", completed: "Completed", noShow: "No show", cancelled: "Cancelled", rescheduled: "Rescheduled" },
    subscription: { title: "Subscription", description: "Manage the clinic subscription plan and available services.", currentPlan: "Current plan", status: "Status", active: "Active", inactive: "Inactive", plan: "Plan", renewal: "Renewal", activationCode: "Activation code", apply: "Apply", applying: "Applying...", notImplemented: "Subscription code activation is not available yet.", loading: "Loading subscription...", loadFailed: "Failed to load subscription data", accessDenied: "You do not have permission to view subscription data." },
    audit: { title: "Activity Log", description: "Review clinic activity and recorded events.", timestamp: "Time", actor: "User", role: "Role", action: "Action", resource: "Resource", noEntries: "No activity recorded", loading: "Loading activity log...", loadFailed: "Failed to load activity log", accessDenied: "You do not have permission to view the activity log.", unknown: "Unknown" },
    settings: { title: "Settings", overview: "Overview", description: "Choose a section above to manage clinic settings.", clinic: "Clinic Settings", users: "Users", roles: "Roles & Permissions", overrides: "Permission Overrides", templates: "Templates", preferences: "Preferences", notifications: "Notifications", subscription: "Subscription", audit: "Activity Log", procedures: "Medical Services", save: "Save", cancel: "Cancel" }
  }
} as const satisfies Record<Locale, unknown>;

export function getAdminMessages(locale: Locale) { return adminMessages[locale]; }
