import type { Locale } from "@/core/i18n/messages";

export const financialResourcesMessages = {
  ar: {
    title: "المالية والموارد", description: "الأساس المالي والموارد المرتبط برحلة المريض وتشغيل العيادة.", financialPlans: "الخطط المالية", installments: "الأقساط", insurance: "التأمين والمطالبات", suppliers: "الموردون", purchasing: "المشتريات والاستلام", receiving: "الاستلام", payments: "المدفوعات", invoices: "الفواتير", inventory: "المخزون", newPlan: "خطة مالية جديدة", newInsurance: "إضافة ملف تأمين", newSupplier: "إضافة مورد", newPurchaseOrder: "أمر شراء جديد", patient: "المريض", choosePatient: "اختر المريض", invoice: "الفاتورة", total: "الإجمالي", insuranceCovered: "التغطية التأمينية", patientResponsibility: "مسؤولية المريض", currency: "العملة", installmentsCount: "عدد الأقساط", dueDate: "تاريخ الاستحقاق", amount: "المبلغ", create: "إنشاء", payerName: "اسم شركة التأمين", policyNumber: "رقم الوثيقة", memberNumber: "رقم العضوية", claimReady: "جاهز للمطالبة", supplierName: "اسم المورد", phone: "الهاتف", email: "البريد الإلكتروني", supplier: "المورد", orderNumber: "رقم أمر الشراء", orderDate: "تاريخ الطلب", expectedDate: "التاريخ المتوقع", inventoryItem: "صنف المخزون", quantity: "الكمية", unitCost: "تكلفة الوحدة", reference: "المرجع", cash: "نقدي", card: "بطاقة", bankTransfer: "تحويل بنكي", online: "دفع إلكتروني", other: "أخرى", recordPayment: "تسجيل الدفع", noInvoices: "لا توجد فواتير متاحة للتسجيل عليها.", permissionDenied: "ليس لديك الصلاحية اللازمة لهذه العملية.", noPlans: "لا توجد خطط مالية لهذا الحساب.", noInsurance: "لا توجد ملفات تأمين مسجلة.", noSuppliers: "لا يوجد موردون نشطون.", noOrders: "لا توجد أوامر شراء.", noInventoryItems: "لا توجد أصناف مخزون نشطة يمكن الشراء منها.", receivingDescription: "استلام المشتريات يحدّث حالة الاستلام ويربطها بالمخزون من خلال مسار الاستلام المعتمد.", receiveFromInventory: "متابعة الاستلام", accessDenied: "ليس لديك الصلاحية اللازمة لهذه العملية.", success: "تمت العملية بنجاح.", error: "تعذر تنفيذ العملية.", loading: "جاري التحميل...", save: "حفظ", close: "إغلاق", openPatient: "فتح ملف المريض", viewInvoices: "عرض الفواتير", viewInventory: "عرض المخزون", back: "رجوع",
  },
  en: {
    title: "Financial & Resources", description: "The financial and resource backbone connected to patient journey and clinic operations.", financialPlans: "Financial Plans", installments: "Installments", insurance: "Insurance & Claims", suppliers: "Suppliers", purchasing: "Purchasing & Receiving", receiving: "Receiving", payments: "Payments", invoices: "Invoices", inventory: "Inventory", newPlan: "New Financial Plan", newInsurance: "Add Insurance Profile", newSupplier: "Add Supplier", newPurchaseOrder: "New Purchase Order", patient: "Patient", choosePatient: "Choose patient", invoice: "Invoice", total: "Total", insuranceCovered: "Insurance covered", patientResponsibility: "Patient responsibility", currency: "Currency", installmentsCount: "Installment count", dueDate: "Due date", amount: "Amount", create: "Create", payerName: "Payer name", policyNumber: "Policy number", memberNumber: "Member number", claimReady: "Claim ready", supplierName: "Supplier name", phone: "Phone", email: "Email", supplier: "Supplier", orderNumber: "Order number", orderDate: "Order date", expectedDate: "Expected date", inventoryItem: "Inventory item", quantity: "Quantity", unitCost: "Unit cost", reference: "Reference", cash: "Cash", card: "Card", bankTransfer: "Bank transfer", online: "Online", other: "Other", recordPayment: "Record payment", noInvoices: "No invoices are available for payment.", permissionDenied: "You do not have permission for this operation.", noPlans: "No financial plans exist for this account.", noInsurance: "No insurance profiles are recorded.", noSuppliers: "No active suppliers are recorded.", noOrders: "No purchase orders are recorded.", noInventoryItems: "No active inventory items are available for purchasing.", receivingDescription: "Receiving records the receipt and connects it to the canonical inventory flow.", receiveFromInventory: "Continue receiving", accessDenied: "You do not have permission for this operation.", success: "Operation completed successfully.", error: "The operation could not be completed.", loading: "Loading...", save: "Save", close: "Close", openPatient: "Open patient", viewInvoices: "View invoices", viewInventory: "View inventory", back: "Back",
  },
} as const;

export function getFinancialResourcesMessages(locale: Locale) { return financialResourcesMessages[locale]; }
