export const legacyArabicToEnglish: Record<string, string> = {
  "إدارة المواعيد والجدولة": "Appointment and scheduling management", "موعد جديد": "New Appointment", "تشخيص النظام": "System Diagnostics", "غير موجود": "Not found", "غير موجودة": "Not found", "نعم": "Yes", "لا": "No", "مجدول": "Scheduled", "مؤكد": "Confirmed", "في الجلسة": "In session", "مكتمل": "Completed", "التقويم الأسبوعي": "Weekly Calendar", "عدد المرضى:": "Patient count:", "عدد الأطباء:": "Doctor count:", "عدد الغرف:": "Room count:", "عدد الإجراءات:": "Procedure count:", "خطأ المرضى:": "Patient error:", "خطأ المواعيد:": "Appointment error:", "عدد المواعيد:": "Appointment count:",
  "جاري التحميل...": "Loading...", "حفظ التغييرات": "Save changes", "حفظ الإعدادات": "Save settings", "إعدادات العيادة": "Clinic Settings", "الأدوار والصلاحيات": "Roles & Permissions", "المستخدمون": "Users", "التفضيلات": "Preferences", "الإشعارات": "Notifications", "الاشتراك": "Subscription", "سجل النشاط": "Activity Log", "إضافة مستخدم": "Add User", "تعديل المستخدم": "Edit User", "إضافة دور": "Add Role", "تعديل الدور": "Edit Role", "حذف الدور": "Delete Role", "الصلاحيات": "Permissions", "صلاحيات المستخدم": "User Permissions",
  "حفظ": "Save", "إلغاء": "Cancel", "تعديل": "Edit", "حذف": "Delete", "إضافة": "Add", "عرض": "View", "فتح": "Open", "إغلاق": "Close", "بحث": "Search", "تحديث": "Refresh", "تأكيد": "Confirm", "رجوع": "Back", "التالي": "Next", "السابق": "Previous", "الحالة": "Status", "التفاصيل": "Details", "ملاحظات": "Notes", "التاريخ": "Date", "الوقت": "Time", "الاسم": "Name", "الهاتف": "Phone", "البريد الإلكتروني": "Email", "الإجراءات": "Actions", "لا توجد بيانات": "No data", "لا توجد نتائج": "No results", "مطلوب": "Required", "خطأ": "Error", "تم بنجاح": "Success", "حدث خطأ غير متوقع": "An unexpected error occurred", "جاري الحفظ...": "Saving...", "جاري...": "Processing...", "جاري المعالجة...": "Processing...", "لا يوجد": "None", "لا يوجد شيء": "Nothing found", "لم يتم العثور على النتائج": "No results found", "لم يتم العثور على المريض": "Patient not found", "لا يوجد مرضى": "No patients", "لا يوجد مرضى في الطابور": "No patients in the queue", "لا توجد ملفات": "No files",
  "الملفات الطبية": "Medical Files", "إضافة ملفات": "Add Files", "رفع ملف": "Upload File", "رفع الملفات": "Upload Files", "تحميل": "Download", "تصغير": "Zoom out", "تكبير": "Zoom in", "تدوير": "Rotate", "تدوير لليمين": "Rotate right", "إعادة ضبط": "Reset", "ربط بالمريض": "Assign to Patient", "المريض": "Patient", "الزيارة": "Visit", "الطبيب": "Doctor", "الغرفة": "Room", "الإجراء": "Procedure", "الموعد": "Appointment", "الطابور": "Queue", "الفاتورة": "Invoice", "الإجمالي": "Total", "مدفوع": "Paid", "غير مدفوع": "Unpaid", "مسودة": "Draft", "المخزون": "Inventory", "الكمية": "Quantity", "الوحدة": "Unit", "مخزون منخفض": "Low stock", "نفد المخزون": "Out of stock",
  "التقارير": "Reports", "إنشاء التقرير": "Generate Report", "تصدير": "Export", "لا توجد تقارير": "No reports", "المتابعة": "Follow-up", "لا توجد عناصر متابعة": "No follow-up items", "إضافة متابعة": "Add follow-up", "لوحة التحكم": "Dashboard", "نظرة عامة": "Overview", "مرحباً": "Welcome", "خطط العلاج": "Treatment Plans", "إضافة خطة علاج": "Add Treatment Plan", "لا توجد خطط علاج": "No treatment plans",
  "تسجيل الدخول": "Login", "التسجيل": "Register", "كلمة المرور": "Password", "نسيت كلمة المرور؟": "Forgot password?", "دخول": "Sign in", "إنشاء حساب": "Create account", "بيانات الدخول غير صحيحة": "Invalid credentials", "تسجيل الخروج": "Sign out", "اللغة": "Language", "العربية": "Arabic", "الإنجليزية": "English",
  "المساحة الطبية": "Clinical Workspace", "مساحة العمل": "Workspace", "مساحة التشغيل": "Operation Workspace", "الأجندة": "Agenda", "المرضى": "Patients", "الفواتير": "Invoices", "التحليلات": "Analytics", "الإعدادات": "Settings", "المستخدمين": "Users", "الأدوار": "Roles", "العيادة": "Clinic", "المستأجر": "Tenant", "النشاط": "Activity", "الملف الطبي": "Medical Record", "السجل الطبي": "Medical Record", "معلومات التواصل": "Contact Information", "البيانات الشخصية": "Personal Information", "تاريخ المريض": "Patient History", "عدد الزيارات": "Visits", "آخر زيارة": "Last visit", "الجنس": "Gender", "ذكر": "Male", "أنثى": "Female", "آخر": "Other", "واتساب": "WhatsApp", "رسائل نصية": "SMS", "مصدر الإحالة": "Referral source", "اختر الجنس": "Select gender", "اختر القناة": "Select channel", "اختر الحالة": "Select status", "أي ملاحظات إضافية...": "Any additional notes...",
  "الاسم الأول": "First name", "الاسم الأخير": "Last name", "الهاتف الرئيسي": "Primary phone", "الهاتف الثانوي": "Secondary phone", "تاريخ الميلاد": "Date of birth", "تاريخ الميلاد:": "Date of birth:", "الحالة:": "Status:", "الهاتف:": "Phone:", "البريد:": "Email:", "القناة:": "Channel:", "الجنس:": "Gender:", "الإحالة:": "Referral:", "التسجيل:": "Registered:", "إضافة مريض": "Add Patient", "مريض جديد": "New Patient", "تعديل مريض": "Edit Patient", "تفاصيل المريض": "Patient Details", "حجز موعد": "Book Appointment", "تسجيل في الطابور": "Check in to Queue", "تسجيل حضور": "Check in"
};
