export type Locale = "ar" | "en";

export const messages = {
  ar: {
    nav: { dashboard: "لوحة التحكم", operation: "مساحة التشغيل", clinical: "المساحة الطبية", treatmentPlans: "خطط العلاج", patients: "المرضى", agenda: "الأجندة", queue: "الطابور", invoices: "الفواتير", inventory: "المخزون", reports: "التقارير", analytics: "التحليلات", followUp: "المتابعة", settings: "الإعدادات" },
    shell: { workspace: "مساحة العمل", signOut: "تسجيل الخروج", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة" },
    language: { label: "اللغة", arabic: "العربية", english: "English" },
    common: { add: "إضافة", edit: "تعديل", delete: "حذف", view: "عرض", open: "فتح", close: "إغلاق", save: "حفظ", cancel: "إلغاء", search: "بحث", refresh: "تحديث", loading: "جاري التحميل...", saving: "جاري الحفظ...", submit: "إرسال", confirm: "تأكيد", back: "رجوع", next: "التالي", previous: "السابق", yes: "نعم", no: "لا", active: "نشط", inactive: "غير نشط", status: "الحالة", details: "التفاصيل", notes: "ملاحظات", date: "التاريخ", time: "الوقت", name: "الاسم", phone: "الهاتف", email: "البريد الإلكتروني", actions: "الإجراءات", noData: "لا توجد بيانات", noResults: "لا توجد نتائج", required: "مطلوب", error: "خطأ", success: "تم بنجاح", unexpectedError: "حدث خطأ غير متوقع" },
    patients: { title: "المرضى", add: "إضافة مريض", searchPlaceholder: "ابحث باسم المريض أو رقم الهاتف...", list: "قائمة المرضى", noMatches: "لا يوجد مرضى مطابقين للبحث", loading: "جاري التحميل...", active: "نشط", inactive: "غير نشط", archived: "مؤرشف", blocked: "محظور", checkIn: "تسجيل حضور", view: "عرض", edit: "تعديل", delete: "حذف", confirmDelete: "هل أنت متأكد من حذف هذا المريض؟", details: "تفاصيل المريض", addFiles: "إضافة ملفات", medicalFiles: "الملفات الطبية", notFound: "لم يتم العثور على المريض", description: "عرض بيانات المريض وتاريخه وملفاته الطبية", appointment: "حجز موعد", queue: "تسجيل في الطابور", checkingIn: "جاري...", contact: "معلومات التواصل", phone: "الهاتف:", secondary: "الثانوي:", email: "البريد:", channel: "القناة:", personal: "البيانات الشخصية", birth: "الميلاد:", gender: "الجنس:", referral: "الإحالة:", registered: "التسجيل:", notes: "ملاحظات", history: "تاريخ المريض", noHistory: "لا يوجد تاريخ مسجل", visits: "عدد الزيارات", lastVisit: "آخر زيارة", preferredProcedure: "الإجراء المفضل", retentionRisk: "مخاطر الاحتفاظ", male: "ذكر", female: "أنثى", other: "آخر", whatsapp: "واتساب", sms: "رسائل نصية", emailChannel: "بريد", phoneChannel: "هاتف", checkInFailed: "فشل تسجيل الحضور", editTitle: "تعديل مريض", newTitle: "مريض جديد", editDescription: "تعديل بيانات المريض الحالي", newDescription: "إضافة مريض جديد إلى النظام", firstName: "الاسم الأول", lastName: "الاسم الأخير", firstNameAr: "الاسم الأول (عربي)", lastNameAr: "الاسم الأخير (عربي)", primaryPhone: "الهاتف الرئيسي", secondaryPhone: "الهاتف الثانوي", dob: "تاريخ الميلاد", chooseGender: "اختر الجنس", preferredChannel: "القناة المفضلة", chooseChannel: "اختر القناة", referralSource: "مصدر الإحالة", referralPlaceholder: "مثال: فيسبوك، توصية صديق...", status: "الحالة", chooseStatus: "اختر الحالة", notesPlaceholder: "أي ملاحظات إضافية...", cancel: "إلغاء", save: "حفظ", saving: "جاري الحفظ...", requiredFirst: "الاسم الأول مطلوب", requiredLast: "الاسم الأخير مطلوب", requiredPhone: "الهاتف الرئيسي مطلوب", clinicNotFound: "خطأ: لم يتم التعرف على العيادة", unexpected: "حدث خطأ غير متوقع" },
    agenda: { title: "الأجندة", description: "إدارة المواعيد والجدولة", newAppointment: "موعد جديد", diagnostics: "تشخيص النظام", notFound: "غير موجود", yes: "نعم", no: "لا", scheduled: "مجدول", confirmed: "مؤكد", inSession: "في الجلسة", completed: "مكتمل", weeklyCalendar: "التقويم الأسبوعي", loading: "جاري التحميل...", tenantId: "معرّف المستأجر", userId: "معرّف المستخدم", authLoading: "تحميل المصادقة", patientCount: "عدد المرضى", doctorCount: "عدد الأطباء", roomCount: "عدد الغرف", procedureCount: "عدد الإجراءات", patientError: "خطأ المرضى", appointmentError: "خطأ المواعيد", appointmentCount: "عدد المواعيد" },
    medicalFiles: { title: "الملفات الطبية", currentContext: "سياق المريض / الزيارة الحالي", intakeContext: "الاستقبال الإداري — اربط الملفات بالمريض عند تحديده", refresh: "تحديث", addFiles: "إضافة ملفات", assignTitle: "ربط ملف استقبال بمريض", searchPatient: "ابحث عن المريض بالاسم أو الهاتف", noMatchingPatients: "لا يوجد مرضى مطابقون", close: "إغلاق", zoomOut: "تصغير", zoomIn: "تكبير", rotate: "تدوير", rotateRight: "تدوير لليمين", reset: "إعادة ضبط", noPatientFiles: "لا توجد ملفات طبية لهذا المريض حتى الآن.", noIntakeFiles: "لا توجد ملفات طبية بانتظار الاستقبال.", assignPatient: "ربط بالمريض…", uploadFailed: "فشل الرفع", unableToLoad: "تعذر تحميل الملفات الطبية", unableToLoadPatients: "تعذر تحميل المرضى", unableToAssign: "تعذر ربط الملف بالمريض", unableToOpen: "تعذر فتح الملف" },
    queue: { title: "الطابور", waiting: "بانتظار الدور", inService: "قيد الخدمة", completed: "مكتمل", noPatients: "لا يوجد مرضى في الطابور" },
    inventory: { title: "المخزون", add: "إضافة صنف", search: "ابحث في المخزون", quantity: "الكمية", unit: "الوحدة", lowStock: "مخزون منخفض", outOfStock: "نفد المخزون" },
    invoices: { title: "الفواتير", newInvoice: "فاتورة جديدة", invoice: "الفاتورة", total: "الإجمالي", paid: "مدفوع", unpaid: "غير مدفوع", draft: "مسودة" },
    reports: { title: "التقارير", generate: "إنشاء التقرير", export: "تصدير", noReports: "لا توجد تقارير" },
    followUp: { title: "المتابعة", noItems: "لا توجد عناصر متابعة", add: "إضافة متابعة" },
    settings: { title: "الإعدادات", save: "حفظ الإعدادات", clinic: "إعدادات العيادة", users: "المستخدمون", roles: "الأدوار والصلاحيات", preferences: "التفضيلات", notifications: "الإشعارات", subscription: "الاشتراك", audit: "سجل النشاط" },
    dashboard: { title: "لوحة التحكم", welcome: "مرحباً", overview: "نظرة عامة" },
    treatmentPlans: { title: "خطط العلاج", add: "إضافة خطة علاج", noPlans: "لا توجد خطط علاج" },
    auth: { login: "تسجيل الدخول", register: "التسجيل", email: "البريد الإلكتروني", password: "كلمة المرور", forgotPassword: "نسيت كلمة المرور؟", signIn: "دخول", signUp: "إنشاء حساب", invalidCredentials: "بيانات الدخول غير صحيحة" },
    offline: { syncing: "جاري المزامنة...", disconnected: "أنت غير متصل. سيتم حفظ البيانات محلياً." }
  },
  en: {
    nav: { dashboard: "Dashboard", operation: "Operation Workspace", clinical: "Clinical Workspace", treatmentPlans: "Treatment Plans", patients: "Patients", agenda: "Agenda", queue: "Queue", invoices: "Invoices", inventory: "Inventory", reports: "Reports", analytics: "Analytics", followUp: "Follow-up", settings: "Settings" },
    shell: { workspace: "Workspace", signOut: "Sign out", openMenu: "Open menu", closeMenu: "Close menu" },
    language: { label: "Language", arabic: "العربية", english: "English" },
    common: { add: "Add", edit: "Edit", delete: "Delete", view: "View", open: "Open", close: "Close", save: "Save", cancel: "Cancel", search: "Search", refresh: "Refresh", loading: "Loading...", saving: "Saving...", submit: "Submit", confirm: "Confirm", back: "Back", next: "Next", previous: "Previous", yes: "Yes", no: "No", active: "Active", inactive: "Inactive", status: "Status", details: "Details", notes: "Notes", date: "Date", time: "Time", name: "Name", phone: "Phone", email: "Email", actions: "Actions", noData: "No data", noResults: "No results", required: "Required", error: "Error", success: "Success", unexpectedError: "An unexpected error occurred" },
    patients: { title: "Patients", add: "Add Patient", searchPlaceholder: "Search by patient name or phone number...", list: "Patient List", noMatches: "No patients match your search", loading: "Loading...", active: "Active", inactive: "Inactive", archived: "Archived", blocked: "Blocked", checkIn: "Check in", view: "View", edit: "Edit", delete: "Delete", confirmDelete: "Are you sure you want to delete this patient?", details: "Patient Details", addFiles: "Add Files", medicalFiles: "Medical Files", notFound: "Patient not found", description: "View patient information, history, and medical files", appointment: "Book Appointment", queue: "Check in to Queue", checkingIn: "Checking in...", contact: "Contact Information", phone: "Phone:", secondary: "Secondary:", email: "Email:", channel: "Preferred channel:", personal: "Personal Information", birth: "Date of birth:", gender: "Gender:", referral: "Referral:", registered: "Registered:", notes: "Notes", history: "Patient History", noHistory: "No history recorded", visits: "Visits", lastVisit: "Last visit", preferredProcedure: "Preferred procedure", retentionRisk: "Retention risk", male: "Male", female: "Female", other: "Other", whatsapp: "WhatsApp", sms: "SMS", emailChannel: "Email", phoneChannel: "Phone", checkInFailed: "Check-in failed", editTitle: "Edit Patient", newTitle: "New Patient", editDescription: "Edit the current patient information", newDescription: "Add a new patient to the system", firstName: "First name", lastName: "Last name", firstNameAr: "First name (Arabic)", lastNameAr: "Last name (Arabic)", primaryPhone: "Primary phone", secondaryPhone: "Secondary phone", dob: "Date of birth", chooseGender: "Select gender", preferredChannel: "Preferred channel", chooseChannel: "Select channel", referralSource: "Referral source", referralPlaceholder: "e.g. Facebook, friend referral...", status: "Status", chooseStatus: "Select status", notesPlaceholder: "Any additional notes...", cancel: "Cancel", save: "Save", saving: "Saving...", requiredFirst: "First name is required", requiredLast: "Last name is required", requiredPhone: "Primary phone is required", clinicNotFound: "Error: clinic could not be identified", unexpected: "An unexpected error occurred" },
    agenda: { title: "Agenda", description: "Appointment and scheduling management", newAppointment: "New Appointment", diagnostics: "System Diagnostics", notFound: "Not found", yes: "Yes", no: "No", scheduled: "Scheduled", confirmed: "Confirmed", inSession: "In session", completed: "Completed", weeklyCalendar: "Weekly Calendar", loading: "Loading...", tenantId: "Tenant ID", userId: "User ID", authLoading: "Auth loading", patientCount: "Patient count", doctorCount: "Doctor count", roomCount: "Room count", procedureCount: "Procedure count", patientError: "Patient error", appointmentError: "Appointment error", appointmentCount: "Appointment count" },
    medicalFiles: { title: "Medical Files", currentContext: "Current patient / visit context", intakeContext: "Administrative intake — assign files to a patient when identified", refresh: "Refresh", addFiles: "Add files", assignTitle: "Assign an intake file to a patient", searchPatient: "Search patient by name or phone", noMatchingPatients: "No matching patients.", close: "Close", zoomOut: "Zoom out", zoomIn: "Zoom in", rotate: "Rotate", rotateRight: "Rotate right", reset: "Reset", noPatientFiles: "No medical files for this patient yet.", noIntakeFiles: "No medical files awaiting intake.", assignPatient: "Assign patient…", uploadFailed: "Upload failed", unableToLoad: "Unable to load medical files", unableToLoadPatients: "Unable to load patients", unableToAssign: "Unable to assign file", unableToOpen: "Unable to open file" },
    queue: { title: "Queue", waiting: "Waiting", inService: "In service", completed: "Completed", noPatients: "No patients in the queue" },
    inventory: { title: "Inventory", add: "Add Item", search: "Search inventory", quantity: "Quantity", unit: "Unit", lowStock: "Low stock", outOfStock: "Out of stock" },
    invoices: { title: "Invoices", newInvoice: "New Invoice", invoice: "Invoice", total: "Total", paid: "Paid", unpaid: "Unpaid", draft: "Draft" },
    reports: { title: "Reports", generate: "Generate Report", export: "Export", noReports: "No reports" },
    followUp: { title: "Follow-up", noItems: "No follow-up items", add: "Add follow-up" },
    settings: { title: "Settings", save: "Save settings", clinic: "Clinic Settings", users: "Users", roles: "Roles & Permissions", preferences: "Preferences", notifications: "Notifications", subscription: "Subscription", audit: "Activity Log" },
    dashboard: { title: "Dashboard", welcome: "Welcome", overview: "Overview" },
    treatmentPlans: { title: "Treatment Plans", add: "Add Treatment Plan", noPlans: "No treatment plans" },
    auth: { login: "Login", register: "Register", email: "Email", password: "Password", forgotPassword: "Forgot password?", signIn: "Sign in", signUp: "Create account", invalidCredentials: "Invalid credentials" },
    offline: { syncing: "Syncing...", disconnected: "You are offline. Data will be saved locally." }
  }
} as const;

export function getMessages(locale: Locale) {
  return messages[locale];
}
