export type Locale = "ar" | "en";

export const messages = {
  ar: {
    nav: { dashboard: "لوحة التحكم", operation: "مساحة التشغيل", clinical: "المساحة الطبية", treatmentPlans: "خطط العلاج", patients: "المرضى", agenda: "الأجندة", queue: "الطابور", invoices: "الفواتير", inventory: "المخزون", reports: "التقارير", analytics: "التحليلات", followUp: "المتابعة", settings: "الإعدادات" },
    shell: { workspace: "مساحة العمل", signOut: "تسجيل الخروج", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة" },
    language: { label: "اللغة", arabic: "العربية", english: "English" },
    common: { add: "إضافة", edit: "تعديل", delete: "حذف", view: "عرض", open: "فتح", close: "إغلاق", save: "حفظ", cancel: "إلغاء", search: "بحث", refresh: "تحديث", loading: "جاري التحميل...", saving: "جاري الحفظ...", submit: "إرسال", confirm: "تأكيد", back: "رجوع", next: "التالي", previous: "السابق", yes: "نعم", no: "لا", active: "نشط", inactive: "غير نشط", status: "الحالة", details: "التفاصيل", notes: "ملاحظات", date: "التاريخ", time: "الوقت", name: "الاسم", phone: "الهاتف", email: "البريد الإلكتروني", actions: "الإجراءات", noData: "لا توجد بيانات", noResults: "لا توجد نتائج", required: "مطلوب", error: "خطأ", success: "تم بنجاح", unexpectedError: "حدث خطأ غير متوقع" },
    patients: { title: "المرضى", add: "إضافة مريض", searchPlaceholder: "ابحث باسم المريض أو رقم الهاتف...", list: "قائمة المرضى", noMatches: "لا يوجد مرضى مطابقين للبحث", loading: "جاري التحميل...", active: "نشط", inactive: "غير نشط", archived: "مؤرشف", blocked: "محظور", checkIn: "تسجيل حضور", view: "عرض", edit: "تعديل", delete: "حذف", confirmDelete: "هل أنت متأكد من حذف هذا المريض؟", details: "تفاصيل المريض", addFiles: "إضافة ملفات", medicalFiles: "الملفات الطبية", notFound: "لم يتم العثور على المريض", description: "عرض بيانات المريض وتاريخه وملفاته الطبية", appointment: "حجز موعد", queue: "تسجيل في الطابور", checkingIn: "جاري...", contact: "معلومات التواصل", phone: "الهاتف:", secondary: "الثانوي:", email: "البريد:", channel: "القناة:", personal: "البيانات الشخصية", birth: "الميلاد:", gender: "الجنس:", referral: "الإحالة:", registered: "التسجيل:", notes: "ملاحظات", history: "تاريخ المريض", noHistory: "لا يوجد تاريخ مسجل", visits: "عدد الزيارات", lastVisit: "آخر زيارة", preferredProcedure: "الإجراء المفضل", retentionRisk: "مخاطر الاحتفاظ", male: "ذكر", female: "أنثى", other: "آخر", whatsapp: "واتساب", sms: "رسائل نصية", emailChannel: "بريد", phoneChannel: "هاتف", checkInFailed: "فشل تسجيل الحضور", editTitle: "تعديل مريض", newTitle: "مريض جديد", editDescription: "تعديل بيانات المريض الحالي", newDescription: "إضافة مريض جديد إلى النظام", firstName: "الاسم الأول", lastName: "اسم العائلة", firstNameAr: "الاسم الأول (عربي)", lastNameAr: "اسم العائلة (عربي)", primaryPhone: "الهاتف الرئيسي", secondaryPhone: "الهاتف الثانوي", dob: "تاريخ الميلاد", chooseGender: "اختر الجنس", preferredChannel: "القناة المفضلة", chooseChannel: "اختر القناة", referralSource: "مصدر الإحالة", referralPlaceholder: "مثال: فيسبوك، توصية صديق...", status: "الحالة", chooseStatus: "اختر الحالة", notesPlaceholder: "أي ملاحظات إضافية...", cancel: "إلغاء", save: "حفظ", saving: "جاري الحفظ...", requiredFirst: "الاسم الأول مطلوب", requiredLast: "اسم العائلة مطلوب", requiredPhone: "الهاتف الرئيسي مطلوب", clinicNotFound: "خطأ: لم يتم التعرف على العيادة", unexpected: "حدث خطأ غير متوقع" },
    agenda: { title: "الأجندة", description: "إدارة المواعيد والجدولة", newAppointment: "موعد جديد", diagnostics: "تشخيص النظام", notFound: "غير موجود", yes: "نعم", no: "لا", scheduled: "مجدول", confirmed: "مؤكد", inSession: "في الجلسة", completed: "مكتمل", weeklyCalendar: "التقويم الأسبوعي", loading: "جاري التحميل...", tenantId: "معرّف المستأجر", userId: "معرّف المستخدم", authLoading: "تحميل المصادقة", patientCount: "عدد المرضى", doctorCount: "عدد الأطباء", roomCount: "عدد الغرف", procedureCount: "عدد الإجراءات", patientError: "خطأ المرضى", appointmentError: "خطأ المواعيد", appointmentCount: "عدد المواعيد" },
    medicalFiles: { title: "الملفات الطبية", currentContext: "سياق المريض / الزيارة الحالي", intakeContext: "الاستقبال الإداري — اربط الملفات بالمريض عند تحديده", refresh: "تحديث", addFiles: "إضافة ملفات", assignTitle: "ربط ملف استقبال بمريض", searchPatient: "ابحث عن المريض بالاسم أو الهاتف", noMatchingPatients: "لا يوجد مرضى مطابقون", close: "إغلاق", zoomOut: "تصغير", zoomIn: "تكبير", rotate: "تدوير", rotateRight: "تدوير لليمين", reset: "إعادة ضبط", noPatientFiles: "لا توجد ملفات طبية لهذا المريض حتى الآن.", noIntakeFiles: "لا توجد ملفات طبية بانتظار الاستقبال.", assignPatient: "ربط بالمريض…", uploadFailed: "فشل الرفع", unableToLoad: "تعذر تحميل الملفات الطبية", unableToLoadPatients: "تعذر تحميل المرضى", unableToAssign: "تعذر ربط الملف بالمريض", unableToOpen: "تعذر فتح الملف" },
    viewer: { zoom: "تكبير", measure: "قياس", windowLevel: "النافذة/المستوى", savingAnnotations: "جاري حفظ العلامات...", saveAnnotations: "حفظ العلامات", initializeError: "تعذر تهيئة عارض الصور الطبية", saveError: "تعذر حفظ العلامات" },
    queue: { title: "الطابور", waiting: "بانتظار الدور", inService: "قيد الخدمة", completed: "مكتمل", noPatients: "لا يوجد مرضى في الطابور" },
    doctorQueue: { title: "قائمة الكشف الخاصة بي", waitingCount: "في الانتظار", completedToday: "مكتمل اليوم", currentPatient: "المريض الحالي", inExam: "في الكشف", hold: "تعليق", complete: "إنهاء", noCurrent: "لا يوجد مريض حالياً", callNext: "استدعاء المريض التالي", onHold: "معلق", resume: "استئناف", waitingList: "قائمة الانتظار", noWaiting: "لا يوجد مرضى في الانتظار", call: "استدعاء", unknownPatient: "غير معروف", file: "ملف", minutesShort: "د" },
    inventory: { title: "المخزون", items: "أصناف المخزون", add: "إضافة صنف", search: "البحث في المخزون...", quantity: "الكمية", unit: "الوحدة", stock: "المخزون", minimum: "الحد الأدنى", lowStock: "مخزون منخفض", outOfStock: "نفد المخزون", noMatches: "لا توجد أصناف مطابقة للبحث", confirmDelete: "هل أنت متأكد من حذف هذا الصنف؟", itemName: "اسم الصنف", itemNameEn: "اسم الصنف (EN)", itemNameAr: "اسم الصنف (AR)", threshold: "الحد الأدنى للتنبيه", currentStock: "المخزون الحالي", basicDetails: "البيانات الأساسية", adjustStock: "تعديل المخزون", transactionType: "نوع المعاملة", transactionHint: "يُشتق اتجاه الزيادة أو النقصان تلقائياً من نوع المعاملة", reason: "السبب / الملاحظات", executeAdjustment: "تنفيذ التعديل", adjusting: "جاري التعديل...", addItem: "إضافة الصنف", editItem: "حفظ التعديلات", requiredName: "اسم الصنف مطلوب", quantityPositive: "الكمية يجب أن تكون أكبر من صفر", reasonRequired: "السبب مطلوب", transactions: { purchase: "شراء (+)", purchase_return: "إرجاع مشتريات (-)", doctor_request: "طلب طبيب (-)", unused_return: "إرجاع غير مستخدم (+)", inventory_adjustment_increase: "تسوية زيادة (+)", inventory_adjustment_decrease: "تسوية نقصان (-)" } },
    notifications: { title: "تفضيلات التنبيهات", description: "إدارة القنوات المستخدمة لإرسال التنبيهات داخل العيادة.", loading: "جاري تحميل تفضيلات التنبيهات...", loadFailed: "فشل تحميل تفضيلات التنبيهات", unavailable: "لا توجد قنوات تنبيهات متاحة", accessDenied: "ليس لديك صلاحية تعديل تفضيلات التنبيهات. يمكنك فقط عرض الإعدادات الحالية.", retry: "إعادة المحاولة", saveSuccess: "تم حفظ التفضيلات بنجاح", updatedChannels: "تم تحديث {count} قناة تنبيهات.", saveFailed: "فشل حفظ التفضيلات", savePartial: "تم الحفظ جزئياً", partialResult: "نجح {success}، فشل {failed}.", changeUnsaved: "تغيير غير محفوظ", enabled: "مفعّلة", disabled: "معطّلة", saving: "جاري الحفظ...", saveChanges: "حفظ التغييرات", channels: { whatsapp: { label: "واتساب", description: "إرسال التنبيهات عبر تطبيق واتساب" }, sms: { label: "رسائل نصية", description: "إرسال التنبيهات عبر الرسائل النصية القصيرة" }, email: { label: "بريد إلكتروني", description: "إرسال التنبيهات عبر البريد الإلكتروني" }, in_app: { label: "داخل التطبيق", description: "عرض التنبيهات داخل لوحة التحكم" } } },
    invoices: { title: "الفواتير", newInvoice: "فاتورة جديدة", invoice: "الفاتورة", total: "الإجمالي", paid: "مدفوع", unpaid: "غير مدفوع", draft: "مسودة" },
    reports: { title: "التقارير", generate: "إنشاء التقرير", export: "تصدير", noReports: "لا توجد تقارير" },
    followUp: { title: "المتابعة", noItems: "لا توجد عناصر متابعة", add: "إضافة متابعة" },
    settings: { title: "الإعدادات", save: "حفظ الإعدادات", clinic: "إعدادات العيادة", users: "المستخدمون", roles: "الأدوار والصلاحيات", preferences: "التفضيلات", notifications: "الإشعارات", subscription: "الاشتراك", audit: "سجل النشاط" },
    clinicProfile: { loading: "جاري تحميل بيانات العيادة...", loadError: "خطأ في تحميل البيانات", noData: "لا توجد بيانات عيادة متاحة", saveSuccess: "تم حفظ التغييرات بنجاح", saveError: "خطأ في الحفظ", unexpected: "حدث خطأ غير متوقع", accessDenied: "ليس لديك صلاحية تعديل ملف العيادة. اتصل بمسؤول النظام.", identity: "هوية العيادة", visualIdentity: "الهوية البصرية", contact: "معلومات التواصل", addressSection: "العنوان", regionalFinancial: "الإعدادات الإقليمية والمالية", defaultBranch: "الفرع الافتراضي", clinicNameEn: "اسم العيادة (إنجليزي)", clinicNameAr: "اسم العيادة (عربي)", logoUrl: "رابط الشعار", logoUrlHelp: "أدخل رابط URL للشعار. يجب أن يكون الرابط صالحاً.", primaryColor: "اللون الرئيسي", primaryPhone: "الهاتف الرئيسي", whatsapp: "رقم واتساب", address: "العنوان", addressPlaceholder: "المدينة، الحي، الشارع...", countryCode: "رمز الدولة", timezone: "المنطقة الزمنية", chooseTimezone: "اختر المنطقة الزمنية", currency: "العملة", chooseCurrency: "اختر العملة", branchName: "اسم الفرع", branchNameAr: "الاسم بالعربي", phone: "الهاتف", requiredClinicName: "اسم العيادة مطلوب (2 أحرف على الأقل)", timezoneOptions: { utc: "UTC", riyadh: "الرياض (AST+3)", dubai: "دبي (AST+4)", kuwait: "الكويت (AST+3)", qatar: "قطر (AST+3)", bahrain: "البحرين (AST+3)", muscat: "مسقط (AST+4)", amman: "عمان (EET+2/+3)", beirut: "بيروت (EET+2/+3)", cairo: "القاهرة (EET+2)", istanbul: "إسطنبول (TRT+3)" }, currencies: { sar: "ريال سعودي (SAR)", aed: "درهم إماراتي (AED)", kwd: "دينار كويتي (KWD)", qar: "ريال قطري (QAR)", bhd: "دينار بحريني (BHD)", omr: "ريال عماني (OMR)", jod: "دينار أردني (JOD)", usd: "دولار أمريكي (USD)", eur: "يورو (EUR)", gbp: "جنيه إسترليني (GBP)", egp: "جنيه مصري (EGP)" } },
    roles: { title: "الأدوار والصلاحيات", description: "إدارة أدوار العيادة والصلاحيات المرتبطة بها", newRole: "دور جديد", createRole: "إنشاء الدور", systemRoles: "أدوار النظام", customRoles: "الأدوار المخصصة", systemRolesInfo: "قوالب جاهزة يوفرها CORE SYSTEM. لا يمكن تعديلها، لكن يمكن عرض صلاحياتها.", customRolesInfo: "أدوار تنشئها العيادة وتتحكم في بياناتها وصلاحياتها بالكامل.", noCustomRoles: "لا توجد أدوار مخصصة حالياً.", createFirstCustomRole: "اضغط \"دور جديد\" لإنشاء أول دور مخصص للعيادة.", editPermissions: "تعديل الصلاحيات", editRole: "تعديل الدور", roleName: "اسم الدور", roleNameArabic: "الاسم بالعربية", descriptionLabel: "الوصف", roleKey: "المعرف الفني", roleKeyHint: "حروف إنجليزية صغيرة وأرقام وشرطات سفلية فقط", roleKeyPlaceholder: "مثال: senior_doctor", descriptionPlaceholder: "وصف مختصر للدور", permissions: "الصلاحيات", permissionsCount: "عدد الصلاحيات المُخصصة", permissionsHint: "لتعديل الصلاحيات، استخدم زر \"تعديل الصلاحيات\" في بطاقة الدور.", confirmDeleteTitle: "تأكيد حذف الدور", confirmDeleteMessage: "هل أنت متأكد من حذف هذا الدور؟", irreversible: "لا يمكن التراجع عن هذا الإجراء.", yesDelete: "نعم، احذف الدور", accessDeniedTitle: "غير مصرح", accessDeniedMessage: "ليس لديك صلاحية عرض الأدوار والصلاحيات." },
    dashboard: { title: "لوحة التحكم", welcome: "مرحباً", overview: "نظرة عامة" },
    treatmentPlans: { title: "خطط العلاج", add: "إضافة خطة علاج", noPlans: "لا توجد خطط علاج" },
    auth: { login: "تسجيل الدخول", register: "التسجيل", email: "البريد الإلكتروني", password: "كلمة المرور", forgotPassword: "نسيت كلمة المرور؟", signIn: "دخول", signUp: "إنشاء حساب", invalidCredentials: "بيانات الدخول غير صحيحة" },
    offline: { syncing: "جاري المزامنة...", disconnected: "أنت غير متصل. سيتم حفظ البيانات محلياً." }
  },
  en: {
    nav: { dashboard: "Dashboard", operation: "Operation Workspace", clinical: "Clinical Workspace", treatmentPlans: "Treatment Plans", patients: "Patients", agenda: "Agenda", queue: "Queue", invoices: "Invoices", inventory: "Inventory", reports: "Reports", analytics: "Analytics", followUp: "Follow-up", settings: "Settings" },
    shell: { workspace: "Workspace", signOut: "Sign out", openMenu: "Open menu", closeMenu: "Close menu" },
    language: { label: "Language", arabic: "العربية", english: "English" },
    common: { add: "Add", edit: "Edit", delete: "Delete", view: "View", open: "Open", close: "Close", save: "Save", cancel: "Cancel", search: "Search", refresh: "Refresh", loading: "Loading...", saving: "Saving...", submit: "Submit", confirm: "Confirm", back: "Back", next: "Next", previous: "Previous", yes: "Yes", no: "No", active: "Active", inactive: "Inactive", status: "Status", details: "Details", notes: "Notes", date: "Date", time: "Time", name: "Name", phone: "Phone", email: "Email", actions: "Actions", noData: "No data", noResults: "No results", required: "Required", error: "Error", success: "Success", unexpectedError: "An unexpected error occurred" },
    patients: { title: "Patients", add: "Add Patient", searchPlaceholder: "Search by patient name or phone number...", list: "Patient List", noMatches: "No patients match your search", loading: "Loading...", active: "Active", inactive: "Inactive", archived: "Archived", blocked: "Blocked", checkIn: "Check in", view: "View", edit: "Edit", delete: "Delete", confirmDelete: "Are you sure you want to delete this patient?", details: "Patient Details", addFiles: "Add Files", medicalFiles: "Medical Files", notFound: "Patient not found", description: "View patient information, history, and medical files", appointment: "Book Appointment", queue: "Check in to Queue", checkingIn: "Checking in...", contact: "Contact Information", phone: "Phone:", secondary: "Secondary:", email: "Email:", channel: "Preferred channel:", personal: "Personal Information", birth: "Date of birth:", gender: "Gender:", referral: "Referral:", registered: "Registered:", notes: "Notes", history: "Patient History", noHistory: "No history recorded", visits: "Visits", lastVisit: "Last visit", preferredProcedure: "Preferred procedure", retentionRisk: "Retention risk", male: "Male", female: "Female", other: "Other", whatsapp: "WhatsApp", sms: "SMS", emailChannel: "Email", phoneChannel: "Phone", checkInFailed: "Check-in failed", editTitle: "Edit Patient", newTitle: "New Patient", editDescription: "Edit the current patient information", newDescription: "Add a new patient to the system", firstName: "First name", lastName: "Last name", firstNameAr: "First name (Arabic)", lastNameAr: "Last name (Arabic)", primaryPhone: "Primary phone", secondaryPhone: "Secondary phone", dob: "Date of birth", chooseGender: "Select gender", preferredChannel: "Preferred channel", chooseChannel: "Select channel", referralSource: "Referral source", referralPlaceholder: "e.g. Facebook, friend referral...", status: "Status", chooseStatus: "Select status", notesPlaceholder: "Any additional notes...", cancel: "Cancel", save: "Save", saving: "Saving...", requiredFirst: "First name is required", requiredLast: "Last name is required", requiredPhone: "Primary phone is required", clinicNotFound: "Error: clinic could not be identified", unexpected: "An unexpected error occurred" },
    agenda: { title: "Agenda", description: "Appointment and scheduling management", newAppointment: "New Appointment", diagnostics: "System Diagnostics", notFound: "Not found", yes: "Yes", no: "No", scheduled: "Scheduled", confirmed: "Confirmed", inSession: "In session", completed: "Completed", weeklyCalendar: "Weekly Calendar", loading: "Loading...", tenantId: "Tenant ID", userId: "User ID", authLoading: "Auth loading", patientCount: "Patient count", doctorCount: "Doctor count", roomCount: "Room count", procedureCount: "Procedure count", patientError: "Patient error", appointmentError: "Appointment error", appointmentCount: "Appointment count" },
    medicalFiles: { title: "Medical Files", currentContext: "Current patient / visit context", intakeContext: "Administrative intake — assign files to a patient when identified", refresh: "Refresh", addFiles: "Add files", assignTitle: "Assign an intake file to a patient", searchPatient: "Search patient by name or phone", noMatchingPatients: "No matching patients.", close: "Close", zoomOut: "Zoom out", zoomIn: "Zoom in", rotate: "Rotate", rotateRight: "Rotate right", reset: "Reset", noPatientFiles: "No medical files for this patient yet.", noIntakeFiles: "No medical files awaiting intake.", assignPatient: "Assign patient…", uploadFailed: "Upload failed", unableToLoad: "Unable to load medical files", unableToLoadPatients: "Unable to load patients", unableToAssign: "Unable to assign file", unableToOpen: "Unable to open file" },
    viewer: { zoom: "Zoom", measure: "Measure", windowLevel: "Window/Level", savingAnnotations: "Saving annotations...", saveAnnotations: "Save annotations", initializeError: "Unable to initialize medical image viewer", saveError: "Unable to save annotations" },
    queue: { title: "Queue", waiting: "Waiting", inService: "In service", completed: "Completed", noPatients: "No patients in the queue" },
    doctorQueue: { title: "My Examination Queue", waitingCount: "Waiting", completedToday: "Completed today", currentPatient: "Current patient", inExam: "In examination", hold: "Hold", complete: "Complete", noCurrent: "No current patient", callNext: "Call next patient", onHold: "On hold", resume: "Resume", waitingList: "Waiting list", noWaiting: "No patients waiting", call: "Call", unknownPatient: "Unknown", file: "File", minutesShort: "m" },
    inventory: { title: "Inventory", items: "Inventory Items", add: "Add Item", search: "Search inventory...", quantity: "Quantity", unit: "Unit", stock: "Stock", minimum: "Minimum", lowStock: "Low stock", outOfStock: "Out of stock", noMatches: "No inventory items match the search", confirmDelete: "Are you sure you want to delete this item?", itemName: "Item name", itemNameEn: "Item name (EN)", itemNameAr: "Item name (AR)", threshold: "Reorder threshold", currentStock: "Current stock", basicDetails: "Basic details", adjustStock: "Adjust stock", transactionType: "Transaction type", transactionHint: "The increase/decrease direction is derived automatically from the transaction type", reason: "Reason / notes", executeAdjustment: "Apply adjustment", adjusting: "Adjusting...", addItem: "Add item", editItem: "Save changes", requiredName: "Item name is required", quantityPositive: "Quantity must be greater than zero", reasonRequired: "Reason is required", transactions: { purchase: "Purchase (+)", purchase_return: "Purchase return (-)", doctor_request: "Doctor request (-)", unused_return: "Unused return (+)", inventory_adjustment_increase: "Increase adjustment (+)", inventory_adjustment_decrease: "Decrease adjustment (-)" } },
    notifications: { title: "Notification Preferences", description: "Manage the channels used to send notifications within the clinic.", loading: "Loading notification preferences...", loadFailed: "Failed to load notification preferences", unavailable: "No notification channels are available", accessDenied: "You do not have permission to edit notification preferences. You can only view the current settings.", retry: "Retry", saveSuccess: "Notification preferences saved successfully", updatedChannels: "Updated {count} notification channels.", saveFailed: "Failed to save notification preferences", savePartial: "Partially saved", partialResult: "Succeeded {success}, failed {failed}.", changeUnsaved: "Unsaved change", enabled: "Enabled", disabled: "Disabled", saving: "Saving...", saveChanges: "Save changes", channels: { whatsapp: { label: "WhatsApp", description: "Send notifications via WhatsApp" }, sms: { label: "SMS", description: "Send notifications via SMS" }, email: { label: "Email", description: "Send notifications via Email" }, in_app: { label: "In-App", description: "Show notifications inside the dashboard" } } },
    invoices: { title: "Invoices", newInvoice: "New Invoice", invoice: "Invoice", total: "Total", paid: "Paid", unpaid: "Unpaid", draft: "Draft" },
    reports: { title: "Reports", generate: "Generate Report", export: "Export", noReports: "No reports" },
    followUp: { title: "Follow-up", noItems: "No follow-up items", add: "Add follow-up" },
    settings: { title: "Settings", save: "Save settings", clinic: "Clinic Settings", users: "Users", roles: "Roles & Permissions", preferences: "Preferences", notifications: "Notifications", subscription: "Subscription", audit: "Activity Log" },
    clinicProfile: { loading: "Loading clinic data...", loadError: "Error loading data", noData: "No clinic data is available", saveSuccess: "Changes saved successfully", saveError: "Save error", unexpected: "An unexpected error occurred", accessDenied: "You do not have permission to edit the clinic profile. Contact an administrator.", identity: "Clinic identity", visualIdentity: "Visual identity", contact: "Contact information", addressSection: "Address", regionalFinancial: "Regional & financial settings", defaultBranch: "Default branch", clinicNameEn: "Clinic name (English)", clinicNameAr: "Clinic name (Arabic)", logoUrl: "Logo URL", logoUrlHelp: "Enter the logo URL. The URL must be valid.", primaryColor: "Primary color", primaryPhone: "Primary phone", whatsapp: "WhatsApp number", address: "Address", addressPlaceholder: "City, district, street...", countryCode: "Country code", timezone: "Time zone", chooseTimezone: "Select time zone", currency: "Currency", chooseCurrency: "Select currency", branchName: "Branch name", branchNameAr: "Arabic name", phone: "Phone", requiredClinicName: "Clinic name is required (at least 2 characters)", timezoneOptions: { utc: "UTC", riyadh: "Riyadh (AST+3)", dubai: "Dubai (AST+4)", kuwait: "Kuwait (AST+3)", qatar: "Qatar (AST+3)", bahrain: "Bahrain (AST+3)", muscat: "Muscat (AST+4)", amman: "Amman (EET+2/+3)", beirut: "Beirut (EET+2/+3)", cairo: "Cairo (EET+2)", istanbul: "Istanbul (TRT+3)" }, currencies: { sar: "Saudi Riyal (SAR)", aed: "UAE Dirham (AED)", kwd: "Kuwaiti Dinar (KWD)", qar: "Qatari Riyal (QAR)", bhd: "Bahraini Dinar (BHD)", omr: "Omani Rial (OMR)", jod: "Jordanian Dinar (JOD)", usd: "US Dollar (USD)", eur: "Euro (EUR)", gbp: "British Pound (GBP)", egp: "Egyptian Pound (EGP)" } },
    roles: { title: "Roles & Permissions", description: "Manage clinic roles and their associated permissions", newRole: "New Role", createRole: "Create Role", systemRoles: "System Roles", customRoles: "Custom Roles", systemRolesInfo: "Ready-made templates provided by CORE SYSTEM. They cannot be edited, but their permissions can be viewed.", customRolesInfo: "Roles created by the clinic with full control over their data and permissions.", noCustomRoles: "No custom roles currently.", createFirstCustomRole: "Click \"New Role\" to create the clinic's first custom role.", editPermissions: "Edit Permissions", editRole: "Edit Role", roleName: "Role name", roleNameArabic: "Arabic name", descriptionLabel: "Description", roleKey: "Technical identifier", roleKeyHint: "Lowercase English letters, numbers, and underscores only", roleKeyPlaceholder: "e.g. senior_doctor", descriptionPlaceholder: "Brief role description", permissions: "Permissions", permissionsCount: "Assigned permissions", permissionsHint: "Use the \"Edit Permissions\" button on the role card to modify permissions.", confirmDeleteTitle: "Confirm role deletion", confirmDeleteMessage: "Are you sure you want to delete this role?", irreversible: "This action cannot be undone.", yesDelete: "Yes, delete role", accessDeniedTitle: "Access denied", accessDeniedMessage: "You do not have permission to view roles and permissions." },
    dashboard: { title: "Dashboard", welcome: "Welcome", overview: "Overview" },
    treatmentPlans: { title: "Treatment Plans", add: "Add Treatment Plan", noPlans: "No treatment plans" },
    auth: { login: "Login", register: "Register", email: "Email", password: "Password", forgotPassword: "Forgot password?", signIn: "Sign in", signUp: "Create account", invalidCredentials: "Invalid credentials" },
    offline: { syncing: "Syncing...", disconnected: "You are offline. Data will be saved locally." }
  }
} as const;

export function getMessages(locale: Locale) {
  return messages[locale];
}
