import type { Locale } from "./messages";
export const portalMessages = {
  ar: {
    unauthorized: "يجب تسجيل الدخول.", clinicUserNotFound: "لم يتم العثور على مستخدم العيادة.", permissionDenied: "ليس لديك صلاحية تنفيذ هذه العملية.", disabled: "بوابة المريض غير مفعلة لهذه العيادة.", channelDisabled: "قناة الإرسال غير مفعلة لهذه العيادة.", fallbackDisabled: "القناة الاحتياطية غير مفعلة لهذه العيادة.", fallbackSame: "يجب أن تختلف القناة الاحتياطية عن القناة الأساسية.", patientNotFound: "لم يتم العثور على المريض.", noDestination: "لا توجد وسيلة اتصال متاحة للمريض.", createFailed: "تعذر إنشاء دعوة البوابة.", queueFailed: "تعذر وضع دعوة البوابة في قائمة الإرسال.", authRequired: "المصادقة مطلوبة.", invalidInvitation: "دعوة غير صالحة.", invitationNotFound: "لم يتم العثور على الدعوة.", invitationInvalid: "لم تعد الدعوة صالحة.", invitationExpired: "انتهت صلاحية الدعوة.", identityMismatch: "بيانات الهوية المصادق عليها لا تطابق الدعوة.", identityCreateFailed: "تعذر إنشاء هوية المريض.", identityActivateFailed: "تعذر تفعيل هوية المريض.", relationshipNotFound: "لم يتم العثور على ارتباط المريض بالعيادة.", linkFailed: "تعذر ربط المريض بالعيادة.", finalizeFailed: "تعذر إكمال الدعوة.", messagingUnavailable: "المراسلة غير متاحة حالياً.", sendMessageFailed: "تعذر إرسال الرسالة.", secureMessages: "الرسائل الآمنة", notUrgentCare: "ليست للحالات العاجلة", noMessagesYet: "لا توجد رسائل بعد.", messagePlaceholder: "اكتب رسالة غير عاجلة إلى العيادة…", sendingMessage: "جارٍ الإرسال…", sendMessage: "إرسال الرسالة", you: "أنت", clinic: "العيادة",
    title: "بوابة المريض", secureAccess: "وصول آمن إلى معلوماتك مع هذه العيادة.", profile: "ملفي", name: "الاسم", fileNumber: "رقم الملف", email: "البريد الإلكتروني", phone: "الهاتف", appointments: "المواعيد", noUpcomingAppointments: "لا توجد مواعيد قادمة.", medicalFiles: "الملفات الطبية", noReleasedFiles: "لم يتم إصدار أي ملفات طبية لك.", advancedExperience: "تجربة المريض المتقدمة", advancedExperienceDescription: "تتوفر المراسلة المتقدمة وإمكانات إشراك المرضى المستقبلية عند تفعيل استحقاق تجربة المريض المتقدمة للعيادة.", security: "الأمان", securityDescription: "يقتصر وصولك إلى البوابة على علاقة المريض بهذه العيادة.", bytes: "بايت", scheduled: "مجدول", portalIdentityInactive: "هوية بوابة المريض الخاصة بك غير مفعلة بعد.", noClinicRelationship: "لا توجد علاقة نشطة مع عيادة لهذا الحساب.", patientRecordUnavailable: "تعذر تحميل سجل المريض.", clinicPortalDisabled: "بوابة المريض غير مفعلة حالياً لهذه العيادة.",
    appointmentStatus: { scheduled: "مجدول", confirmed: "مؤكد", completed: "مكتمل", cancelled: "ملغى", no_show: "لم يحضر", waiting: "قيد الانتظار", in_consultation: "قيد الكشف", pending_close: "بانتظار الإغلاق" },
    appointmentType: { consultation: "استشارة", follow_up: "متابعة", procedure: "إجراء", treatment: "علاج", walk_in: "مراجع دون موعد" },
    missingToken: "رابط الدعوة يفتقد رمز الأمان المطلوب.", activateTitle: "تفعيل بوابة المريض", activationHintEmail: "استخدم عنوان البريد الإلكتروني نفسه الذي استخدمته العيادة لهذه الدعوة.", activationHintPhone: "استخدم رقم الهاتف نفسه الذي استخدمته العيادة لهذه الدعوة.", verificationSentEmail: "تم إرسال رمز تحقق إلى بريدك الإلكتروني.", verificationSentPhone: "تم إرسال رمز تحقق إلى هاتفك.", activationFailed: "فشل التفعيل", verificationCode: "رمز التحقق", sending: "جارٍ الإرسال…", activating: "جارٍ التفعيل…", activatePortal: "تفعيل البوابة", sendCode: "إرسال رمز", sendEmailCode: "إرسال رمز البريد الإلكتروني", sendWhatsAppCode: "إرسال رمز WhatsApp", sendSmsCode: "إرسال رمز SMS"
  },
  en: {
    unauthorized: "You must sign in.", clinicUserNotFound: "Clinic user was not found.", permissionDenied: "You do not have permission to perform this action.", disabled: "Patient Portal is not enabled for this clinic.", channelDisabled: "The selected channel is not enabled for this clinic.", fallbackDisabled: "The fallback channel is not enabled for this clinic.", fallbackSame: "The fallback channel must differ from the primary channel.", patientNotFound: "Patient was not found.", noDestination: "The patient has no available contact destination.", createFailed: "Unable to create the portal invitation.", queueFailed: "Unable to queue the portal invitation.", authRequired: "Authentication is required.", invalidInvitation: "Invalid invitation.", invitationNotFound: "Invitation was not found.", invitationInvalid: "Invitation is no longer valid.", invitationExpired: "Invitation has expired.", identityMismatch: "The authenticated identity does not match the invitation.", identityCreateFailed: "Unable to create the patient identity.", identityActivateFailed: "Unable to activate the patient identity.", relationshipNotFound: "Patient relationship was not found.", linkFailed: "Unable to link the patient to the clinic.", finalizeFailed: "Unable to finalize the invitation.", messagingUnavailable: "Messaging is currently unavailable.", sendMessageFailed: "Unable to send the message.", secureMessages: "Secure messages", notUrgentCare: "Not for urgent care", noMessagesYet: "No messages yet.", messagePlaceholder: "Write a non-urgent message to the clinic…", sendingMessage: "Sending…", sendMessage: "Send message", you: "You", clinic: "Clinic",
    title: "Patient Portal", secureAccess: "Secure access to your information with this clinic.", profile: "My profile", name: "Name", fileNumber: "File number", email: "Email", phone: "Phone", appointments: "Appointments", noUpcomingAppointments: "No upcoming appointments.", medicalFiles: "Medical files", noReleasedFiles: "No medical files have been released to you.", advancedExperience: "Advanced patient experience", advancedExperienceDescription: "Advanced messaging and future patient engagement capabilities are available when the clinic has the Advanced Patient Experience entitlement.", security: "Security", securityDescription: "Your portal access is limited to this clinic relationship.", bytes: "bytes", scheduled: "Scheduled", portalIdentityInactive: "Your patient portal identity is not active yet.", noClinicRelationship: "No active clinic relationship is available for this account.", patientRecordUnavailable: "Patient record could not be loaded.", clinicPortalDisabled: "Patient Portal is not currently enabled for this clinic.",
    appointmentStatus: { scheduled: "Scheduled", confirmed: "Confirmed", completed: "Completed", cancelled: "Cancelled", no_show: "No show", waiting: "Waiting", in_consultation: "In consultation", pending_close: "Pending close" },
    appointmentType: { consultation: "Consultation", follow_up: "Follow-up", procedure: "Procedure", treatment: "Treatment", walk_in: "Walk-in" },
    missingToken: "This invitation link is missing its secure token.", activateTitle: "Activate Patient Portal", activationHintEmail: "Use the same email address that the clinic used for this invitation.", activationHintPhone: "Use the same phone number that the clinic used for this invitation.", verificationSentEmail: "A verification code was sent to your email.", verificationSentPhone: "A verification code was sent to your phone.", activationFailed: "Activation failed", verificationCode: "Verification code", sending: "Sending…", activating: "Activating…", activatePortal: "Activate portal", sendCode: "Send code", sendEmailCode: "Send email code", sendWhatsAppCode: "Send WhatsApp code", sendSmsCode: "Send SMS code"
  }
} as const;
export function getPortalMessages(locale: Locale) { return portalMessages[locale]; }
