import type { Locale } from "./messages";

export const procedureMessages = {
  ar: {
    title: "الخدمات الطبية", description: "إدارة كتالوج الخدمات والإجراءات في العيادة.", count: "خدمة", active: "نشطة", inactive: "معطلة", new: "خدمة جديدة", edit: "تعديل الخدمة", loading: "جاري التحميل...", loadFailed: "فشل تحميل الكتالوج", unexpected: "حدث خطأ غير متوقع", search: "بحث باسم الخدمة أو الرمز...", allSpecialties: "كل التخصصات", allStatuses: "كل الحالات", noResults: "لا توجد خدمات مطابقة", code: "الرمز", name: "اسم الخدمة", nameAr: "اسم الخدمة بالعربية", category: "الفئة", specialty: "التخصص", serviceType: "نوع الخدمة", providerType: "مقدم الخدمة", duration: "المدة (دقيقة)", buffer: "وقت الاحتياط (دقيقة)", price: "السعر", taxIncluded: "السعر شامل الضريبة", taxRate: "نسبة الضريبة", displayOrder: "ترتيب العرض", status: "الحالة", actions: "الإجراءات", save: "حفظ", cancel: "إلغاء", create: "إنشاء", saving: "جاري الحفظ...", activeStatus: "نشطة", inactiveStatus: "معطلة", activate: "تفعيل", deactivate: "تعطيل", saved: "تم الحفظ بنجاح", created: "تم إنشاء الخدمة بنجاح", yes: "نعم", no: "لا", required: "مطلوب",
    errors: { unauthorized: "يجب تسجيل الدخول للمتابعة", tenantResolutionFailed: "تعذر تحديد العيادة", permissionDenied: "ليس لديك صلاحية لتنفيذ هذا الإجراء", createFailed: "تعذر إنشاء الخدمة", updateFailed: "تعذر تحديث الخدمة", notFound: "الخدمة غير موجودة أو لا تملك صلاحية الوصول إليها", statusUpdateFailed: "تعذر تحديث حالة الخدمة", unexpected: "حدث خطأ غير متوقع" }
  },
  en: {
    title: "Medical Services", description: "Manage the clinic service and procedure catalog.", count: "services", active: "active", inactive: "inactive", new: "New service", edit: "Edit service", loading: "Loading...", loadFailed: "Failed to load catalog", unexpected: "An unexpected error occurred", search: "Search by service name or code...", allSpecialties: "All specialties", allStatuses: "All statuses", noResults: "No matching services", code: "Code", name: "Service name", nameAr: "Arabic service name", category: "Category", specialty: "Specialty", serviceType: "Service type", providerType: "Provider type", duration: "Duration (minutes)", buffer: "Buffer (minutes)", price: "Price", taxIncluded: "Tax included", taxRate: "Tax rate", displayOrder: "Display order", status: "Status", actions: "Actions", save: "Save", cancel: "Cancel", create: "Create", saving: "Saving...", activeStatus: "Active", inactiveStatus: "Inactive", activate: "Activate", deactivate: "Deactivate", saved: "Changes saved", created: "Service created", yes: "Yes", no: "No", required: "Required",
    errors: { unauthorized: "You must sign in to continue", tenantResolutionFailed: "Unable to determine the clinic", permissionDenied: "You do not have permission to perform this action", createFailed: "Unable to create the service", updateFailed: "Unable to update the service", notFound: "The service was not found or you do not have access to it", statusUpdateFailed: "Unable to update the service status", unexpected: "An unexpected error occurred" }
  }
} as const satisfies Record<Locale, unknown>;

export function getProcedureMessages(locale: Locale) { return procedureMessages[locale]; }
