import type { Locale } from "./messages";

export const systemPreferencesMessages = {
  ar: {
    title: "تفضيلات النظام", description: "إدارة إعدادات النظام الأساسية للعيادة، بما في ذلك اللغة واتجاه النص والمنطقة الزمنية والعملة.", generalSettings: "الإعدادات العامة", language: "اللغة", selectLanguage: "اختر اللغة", languageHint: "لغة واجهة المستخدم.", direction: "اتجاه النص", selectDirection: "اختر الاتجاه", directionHint: "يحدد اتجاه واجهة التطبيق بما يتوافق مع اللغة.", timezone: "المنطقة الزمنية", selectTimezone: "اختر المنطقة الزمنية", currency: "العملة", selectCurrency: "اختر العملة", currencyHint: "العملة المستخدمة في الفواتير والتقارير المالية.", saved: "تم حفظ التفضيلات بنجاح", savedDescription: "سيتم تطبيق تغييرات اللغة والاتجاه بعد إعادة تحميل الصفحة.", saveFailed: "فشل حفظ التفضيلات", loadFailed: "فشل تحميل تفضيلات النظام. يرجى المحاولة مرة أخرى.", notFound: "لم يتم العثور على تفضيلات النظام.", permissionDenied: "ليس لديك صلاحية تعديل إعدادات النظام.", unsaved: "هناك تغييرات غير محفوظة", languages: { ar: "العربية", en: "الإنجليزية" }, directions: { rtl: "من اليمين إلى اليسار", ltr: "من اليسار إلى اليمين" }, currencies: { SAR: "ريال سعودي (SAR)", AED: "درهم إماراتي (AED)", KWD: "دينار كويتي (KWD)", QAR: "ريال قطري (QAR)", BHD: "دينار بحريني (BHD)", OMR: "ريال عماني (OMR)", JOD: "دينار أردني (JOD)", USD: "دولار أمريكي (USD)", EUR: "يورو (EUR)", GBP: "جنيه إسترليني (GBP)", EGP: "جنيه مصري (EGP)" },
  },
  en: {
    title: "System Preferences", description: "Manage core clinic settings including language, text direction, time zone, and currency.", generalSettings: "General Settings", language: "Language", selectLanguage: "Select language", languageHint: "Application interface language.", direction: "Text direction", selectDirection: "Select direction", directionHint: "Controls the application direction to match the selected language.", timezone: "Time zone", selectTimezone: "Select time zone", currency: "Currency", selectCurrency: "Select currency", currencyHint: "Currency used for invoices and financial reports.", saved: "Preferences saved successfully", savedDescription: "Language and direction changes will apply after the page reloads.", saveFailed: "Failed to save preferences", loadFailed: "Failed to load system preferences. Please try again.", notFound: "System preferences were not found.", permissionDenied: "You do not have permission to edit system settings.", unsaved: "Unsaved changes", languages: { ar: "العربية", en: "English" }, directions: { rtl: "Right to left", ltr: "Left to right" }, currencies: { SAR: "Saudi Riyal (SAR)", AED: "UAE Dirham (AED)", KWD: "Kuwaiti Dinar (KWD)", QAR: "Qatari Riyal (QAR)", BHD: "Bahraini Dinar (BHD)", OMR: "Omani Rial (OMR)", JOD: "Jordanian Dinar (JOD)", USD: "US Dollar (USD)", EUR: "Euro (EUR)", GBP: "British Pound (GBP)", EGP: "Egyptian Pound (EGP)" },
  },
} as const;

export function getSystemPreferencesMessages(locale: Locale) { return systemPreferencesMessages[locale]; }
