import type { Locale } from "./messages";

export const systemPreferencesMessages = {
  ar: {
    title: "تفضيلات النظام", description: "إدارة إعدادات النظام الأساسية للعيادة، بما في ذلك اللغة واتجاه النص والمنطقة الزمنية والعملة.", generalSettings: "الإعدادات العامة", language: "اللغة", selectLanguage: "اختر اللغة", languageHint: "لغة واجهة المستخدم.", direction: "اتجاه النص", selectDirection: "اختر الاتجاه", directionHint: "يحدد اتجاه واجهة التطبيق بما يتوافق مع اللغة.", timezone: "المنطقة الزمنية", selectTimezone: "اختر المنطقة الزمنية", currency: "العملة", selectCurrency: "اختر العملة", currencyHint: "العملة المستخدمة في الفواتير والتقارير المالية.", saved: "تم حفظ التفضيلات بنجاح", savedDescription: "سيتم تطبيق تغييرات اللغة والاتجاه بعد إعادة تحميل الصفحة.", saveFailed: "فشل حفظ التفضيلات", loadFailed: "فشل تحميل تفضيلات النظام. يرجى المحاولة مرة أخرى.", notFound: "لم يتم العثور على تفضيلات النظام.", permissionDenied: "ليس لديك صلاحية تعديل إعدادات النظام.", unsaved: "هناك تغييرات غير محفوظة", languages: { ar: "العربية", en: "الإنجليزية" }, directions: { rtl: "من اليمين إلى اليسار", ltr: "من اليسار إلى اليمين" }, currencies: { DZD: "دينار جزائري (DZD)", BHD: "دينار بحريني (BHD)", KMF: "فرنك قمري (KMF)", DJF: "فرنك جيبوتي (DJF)", EGP: "جنيه مصري (EGP)", IQD: "دينار عراقي (IQD)", JOD: "دينار أردني (JOD)", KWD: "دينار كويتي (KWD)", LBP: "ليرة لبنانية (LBP)", LYD: "دينار ليبي (LYD)", MAD: "درهم مغربي (MAD)", MRU: "أوقية موريتانية (MRU)", OMR: "ريال عماني (OMR)", QAR: "ريال قطري (QAR)", SAR: "ريال سعودي (SAR)", SOS: "شلن صومالي (SOS)", SDG: "جنيه سوداني (SDG)", SYP: "ليرة سورية (SYP)", TND: "دينار تونسي (TND)", AED: "درهم إماراتي (AED)", YER: "ريال يمني (YER)", USD: "دولار أمريكي (USD)", EUR: "يورو (EUR)" },
  },
  en: {
    title: "System Preferences", description: "Manage core clinic settings including language, text direction, time zone, and currency.", generalSettings: "General Settings", language: "Language", selectLanguage: "Select language", languageHint: "Application interface language.", direction: "Text direction", selectDirection: "Select direction", directionHint: "Controls the application direction to match the selected language.", timezone: "Time zone", selectTimezone: "Select time zone", currency: "Currency", selectCurrency: "Select currency", currencyHint: "Currency used for invoices and financial reports.", saved: "Preferences saved successfully", savedDescription: "Language and direction changes will apply after the page reloads.", saveFailed: "Failed to save preferences", loadFailed: "Failed to load system preferences. Please try again.", notFound: "System preferences were not found.", permissionDenied: "You do not have permission to edit system settings.", unsaved: "Unsaved changes", languages: { ar: "Arabic", en: "English" }, directions: { rtl: "Right to left", ltr: "Left to right" }, currencies: { DZD: "Algerian Dinar (DZD)", BHD: "Bahraini Dinar (BHD)", KMF: "Comorian Franc (KMF)", DJF: "Djiboutian Franc (DJF)", EGP: "Egyptian Pound (EGP)", IQD: "Iraqi Dinar (IQD)", JOD: "Jordanian Dinar (JOD)", KWD: "Kuwaiti Dinar (KWD)", LBP: "Lebanese Pound (LBP)", LYD: "Libyan Dinar (LYD)", MAD: "Moroccan Dirham (MAD)", MRU: "Mauritanian Ouguiya (MRU)", OMR: "Omani Rial (OMR)", QAR: "Qatari Riyal (QAR)", SAR: "Saudi Riyal (SAR)", SOS: "Somali Shilling (SOS)", SDG: "Sudanese Pound (SDG)", SYP: "Syrian Pound (SYP)", TND: "Tunisian Dinar (TND)", AED: "UAE Dirham (AED)", YER: "Yemeni Rial (YER)", USD: "US Dollar (USD)", EUR: "Euro (EUR)" },
  },
} as const;

export function getSystemPreferencesMessages(locale: Locale) { return systemPreferencesMessages[locale]; }
