export type Locale = "ar" | "en";

const permissionResources = {
  patients: ["المرضى", "Patients", "إدارة سجلات المرضى", "Manage patient records"], sessions: ["الجلسات", "Sessions", "إدارة الجلسات والزيارات", "Manage sessions and visits"], agenda: ["الأجندة", "Agenda", "المواعيد والتقويم", "Appointments and calendar"], invoices: ["الفواتير", "Invoices", "الفوترة والمدفوعات", "Billing and payments"], inventory: ["المخزون", "Inventory", "إدارة المخزون والمستلزمات", "Manage inventory and supplies"], analytics: ["التحليلات", "Analytics", "التقارير التحليلية", "Analytical reporting"], users: ["المستخدمون", "Users", "إدارة مستخدمي العيادة", "Manage clinic users"], settings: ["الإعدادات", "Settings", "إعدادات العيادة", "Clinic settings"], audit: ["السجل", "Audit Log", "سجل النشاط والتدقيق", "Activity and audit log"], reports: ["التقارير", "Reports", "التقارير التشغيلية", "Operational reports"], followup: ["المتابعة", "Follow-up", "متابعة ما بعد الزيارة", "Post-visit follow-up"], roles: ["الأدوار", "Roles", "إدارة الأدوار والصلاحيات", "Manage roles and permissions"], templates: ["القوالب", "Templates", "قوالب الصلاحيات", "Permission templates"], overrides: ["التجاوزات", "Overrides", "تجاوزات الصلاحيات الفردية", "Individual permission overrides"], subscription: ["الاشتراك", "Subscription", "معلومات الاشتراك", "Subscription information"], notifications: ["التنبيهات", "Notifications", "إعدادات التنبيهات", "Notification settings"], procedures: ["الخدمات الطبية", "Medical Services", "إدارة كتالوج الخدمات والإجراءات", "Manage services and procedures"]
} as const;

const actionLabels = { read: ["عرض", "View"], create: ["إنشاء", "Create"], update: ["تعديل", "Edit"], delete: ["حذف", "Delete"], manage: ["إدارة", "Manage"] } as const;

export const terminology = {
  ar: {
    clinical: {
      title: "المساحة الطبية", description: "الزيارة الطبية والفحص والنتائج والقرار الطبي", refresh: "تحديث", treatmentPlan: "خطة العلاج", visitContext: "سياق الزيارة", patient: "المريض", patientFallback: "مريض", noFileNumber: "بدون رقم ملف", provider: "المقدم", unspecified: "غير محدد", room: "الغرفة", unspecifiedRoom: "غير محددة", appointment: "الموعد", linkedAppointment: "مرتبط بموعد", walkIn: "زيارة بدون موعد", examination: "الفحص الطبي", examinationPlaceholder: "سجل الفحص الذي تم إجراؤه...", findings: "النتائج", findingsPlaceholder: "سجل النتائج والملاحظات الطبية...", decision: "القرار الطبي", decisionPlaceholder: "سجل القرار الطبي الناتج عن الفحص...", procedures: "الإجراءات المرتبطة بالزيارة", selectProcedure: "اختر إجراءً...", add: "إضافة", noProcedures: "لا توجد إجراءات مرتبطة بهذه الزيارة.", remove: "إزالة", saveVisit: "حفظ الزيارة", finishVisit: "إنهاء الزيارة وإعادتها لمساحة التشغيل", noActiveVisit: "لا توجد زيارة طبية نشطة حالياً", takeNext: "استلام المريض التالي", waitingPatients: "المرضى المنتظرون", noWaiting: "لا يوجد مرضى في الانتظار", providerUnspecified: "مقدم غير محدد", wait: "انتظار", minutes: "دقيقة", take: "استلام", returnedToOperation: "عاد إلى التشغيل", noPendingClose: "لا توجد زيارات بانتظار الإنهاء التشغيلي", pendingOperationClose: "بانتظار الإنهاء في مساحة التشغيل", loadFailed: "تعذر تحميل المساحة الطبية", actionFailed: "تعذر تنفيذ الإجراء", saveFailed: "تعذر حفظ الزيارة", finishFailed: "تعذر إنهاء الزيارة"
    },
    operation: {
      title: "مساحة التشغيل", description: "إدارة حركة المريض من الوصول وحتى إعادة الاستلام وإنهاء الزيارة", refresh: "تحديث", searchPlaceholder: "بحث بالمريض أو رقم الملف أو الطبيب...", waiting: "في الانتظار", waitingDescription: "وصل المريض وينتظر التوجيه", inConsultation: "مع مقدم الخدمة", inConsultationDescription: "الزيارة موجودة لدى المساحة الطبية", pendingClose: "بانتظار الاستقبال", pendingCloseDescription: "عاد المريض من المساحة الطبية", completed: "مكتمل", completedDescription: "تم إنهاء الزيارة تشغيلياً", patientFallback: "مريض", directToProvider: "توجيه للطبيب", registerArrival: "تسجيل الوصول", noShow: "لم يحضر", cancel: "إلغاء", clinicalWaiting: "الزيارة لدى المساحة الطبية. تنتظر عودتها إلى الاستقبال.", completeFromReception: "إنهاء الزيارة من الاستقبال", noOperations: "لا توجد عمليات", wait: "انتظار", minutes: "دقيقة", handoffNote: "السحب والإفلات يغيّر الحالة المحفوظة فقط للانتقالات التشغيلية المسموح بها. الانتقال إلى المساحة الطبية والعودة منها يظل تسليماً بين مساحتي العمل ولا يتجاوز صلاحيات المستخدم.", loadFailed: "تعذر تحميل حركة المرضى", actionFailed: "تعذر تنفيذ العملية", invalidTransition: "هذا الانتقال لا يتم من شاشة التشغيل؛ يجب أن يمر عبر مساحة العمل المختصة"
    },
    treatmentPlans: {
      title: "خطط العلاج", description: "خطة علاجية خاصة بالمريض تمتد عبر الوقت والأنشطة والزيارات الفعلية", refresh: "تحديث", newPlan: "خطة علاج جديدة", createTitle: "إنشاء خطة علاج", planTitle: "عنوان الخطة", diagnosis: "ملخص التشخيص", goals: "الأهداف العلاجية", create: "إنشاء", cancel: "إلغاء", openFromPatient: "افتح هذه المساحة من سياق مريض لإنشاء أو إدارة خطة علاجية.", plans: "الخطط", noPlans: "لا توجد خطة علاجية لهذا المريض.", activate: "تفعيل", completePlan: "إكمال الخطة", patient: "المريض", patientFallback: "مريض", diagnosisLabel: "التشخيص", goalsLabel: "الأهداف", linkedVisits: "الزيارات المرتبطة فعلياً", activities: "الأنشطة المخططة", activityName: "اسم النشاط / الجلسة", shortDescription: "وصف مختصر", add: "إضافة", noActivities: "لا توجد أنشطة مخططة بعد.", linkVisit: "ربط الزيارة", linkCurrentVisit: "ربط الزيارة الحالية بالخطة", selectPlan: "اختر خطة علاجية لعرض الأنشطة.", backToMedical: "العودة للمساحة الطبية", loadFailed: "تعذر تحميل خطط العلاج", actionFailed: "تعذر تنفيذ العملية", mustSelectPatient: "يجب تحديد المريض لإنشاء خطة علاجية", status: { draft: "مسودة", active: "نشطة", on_hold: "موقوفة", completed: "مكتملة", cancelled: "ملغاة" }, itemStatus: { planned: "مخطط", scheduled: "مجدول", in_progress: "قيد التنفيذ", completed: "مكتمل", skipped: "متجاوز", cancelled: "ملغى" }
    },
    permissions: { resources: Object.fromEntries(Object.entries(permissionResources).map(([key, value]) => [key, { label: value[0], description: value[2] }])), actions: Object.fromEntries(Object.entries(actionLabels).map(([key, value]) => [key, value[0]])) },
    errors: { saveFailed: "فشل الحفظ", close: "إغلاق", cancel: "إلغاء", loading: "جاري التحميل...", unableToLoadRole: "تعذر تحميل بيانات الدور أو قائمة الصلاحيات", choosePermissions: "اختر الصلاحيات التي تريد تخصيصها لهذا الدور", systemRole: "هذا دور نظامي. لا يمكن تعديل صلاحيات الأدوار النظامية. يمكنك فقط عرض التكوين الحالي.", saved: "تم الحفظ بنجاح", saveChanges: "حفظ التغييرات", failedToSave: "فشل الحفظ" }
  },
  en: {
    clinical: {
      title: "Medical Workspace", description: "Medical visit, examination, findings, and medical decision", refresh: "Refresh", treatmentPlan: "Treatment Plan", visitContext: "Visit Context", patient: "Patient", patientFallback: "Patient", noFileNumber: "No file number", provider: "Provider", unspecified: "Not specified", room: "Room", unspecifiedRoom: "Not specified", appointment: "Appointment", linkedAppointment: "Linked appointment", walkIn: "Walk-in visit", examination: "Medical Examination", examinationPlaceholder: "Record the examination performed...", findings: "Findings", findingsPlaceholder: "Record medical findings and notes...", decision: "Medical Decision", decisionPlaceholder: "Record the medical decision resulting from the examination...", procedures: "Visit Procedures", selectProcedure: "Select a procedure...", add: "Add", noProcedures: "No procedures are linked to this visit.", remove: "Remove", saveVisit: "Save Visit", finishVisit: "Finish Visit and Return to Operation", noActiveVisit: "No active medical visit", takeNext: "Take Next Patient", waitingPatients: "Waiting Patients", noWaiting: "No patients waiting", providerUnspecified: "Provider not specified", wait: "Wait", minutes: "min", take: "Take", returnedToOperation: "Returned to Operation", noPendingClose: "No visits awaiting operational completion", pendingOperationClose: "Awaiting completion in Operation Workspace", loadFailed: "Unable to load Medical Workspace", actionFailed: "Unable to perform the action", saveFailed: "Unable to save the visit", finishFailed: "Unable to finish the visit"
    },
    operation: {
      title: "Operation Workspace", description: "Manage patient flow from arrival through handoff and visit completion", refresh: "Refresh", searchPlaceholder: "Search by patient, file number, or doctor...", waiting: "Waiting", waitingDescription: "Patient arrived and is waiting for direction", inConsultation: "With Provider", inConsultationDescription: "The visit is in the Medical Workspace", pendingClose: "Awaiting Reception", pendingCloseDescription: "Patient returned from the Medical Workspace", completed: "Completed", completedDescription: "Visit completed operationally", patientFallback: "Patient", directToProvider: "Send to Doctor", registerArrival: "Register Arrival", noShow: "No Show", cancel: "Cancel", clinicalWaiting: "The visit is in the Medical Workspace and awaits return to reception.", completeFromReception: "Complete Visit from Reception", noOperations: "No operations", wait: "Wait", minutes: "min", handoffNote: "Drag and drop changes saved state only for allowed operational transitions. Handoff to and from the Medical Workspace remains between workspaces and does not bypass user permissions.", loadFailed: "Unable to load patient flow", actionFailed: "Unable to perform the operation", invalidTransition: "This transition cannot be performed from the operation screen; it must pass through the appropriate workspace"
    },
    treatmentPlans: {
      title: "Treatment Plans", description: "A patient-specific treatment plan spanning time, activities, and actual visits", refresh: "Refresh", newPlan: "New Treatment Plan", createTitle: "Create Treatment Plan", planTitle: "Plan title", diagnosis: "Diagnosis summary", goals: "Treatment goals", create: "Create", cancel: "Cancel", openFromPatient: "Open this workspace from a patient context to create or manage a treatment plan.", plans: "Plans", noPlans: "No treatment plan for this patient.", activate: "Activate", completePlan: "Complete Plan", patient: "Patient", patientFallback: "Patient", diagnosisLabel: "Diagnosis", goalsLabel: "Goals", linkedVisits: "Actual linked visits", activities: "Planned Activities", activityName: "Activity / session name", shortDescription: "Short description", add: "Add", noActivities: "No planned activities yet.", linkVisit: "Link Visit", linkCurrentVisit: "Link Current Visit to Plan", selectPlan: "Select a treatment plan to view activities.", backToMedical: "Return to Medical Workspace", loadFailed: "Unable to load treatment plans", actionFailed: "Unable to perform the operation", mustSelectPatient: "A patient must be selected to create a treatment plan", status: { draft: "Draft", active: "Active", on_hold: "On Hold", completed: "Completed", cancelled: "Cancelled" }, itemStatus: { planned: "Planned", scheduled: "Scheduled", in_progress: "In Progress", completed: "Completed", skipped: "Skipped", cancelled: "Cancelled" }
    },
    permissions: { resources: Object.fromEntries(Object.entries(permissionResources).map(([key, value]) => [key, { label: value[1], description: value[3] }])), actions: Object.fromEntries(Object.entries(actionLabels).map(([key, value]) => [key, value[1]])) },
    errors: { saveFailed: "Failed to save", close: "Close", cancel: "Cancel", loading: "Loading...", unableToLoadRole: "Unable to load role data or permission catalog", choosePermissions: "Select the permissions to assign to this role", systemRole: "This is a system role. System role permissions cannot be edited. You can only view the current configuration.", saved: "Saved successfully", saveChanges: "Save changes", failedToSave: "Failed to save" }
  }
} as const;

export function getTerminology(locale: Locale) { return terminology[locale]; }
