import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import { createClient } from "@/infrastructure/supabase/server";
import { resolveTenantId } from "@/core/auth/resolveTenantId";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import { createCommunicationRequest, createConversation, sendInternalMessage } from "@/domain/communications/communications.actions";

export default async function CommunicationsPage() {
  const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login"); const tenantId=await resolveTenantId(user.id); if(!tenantId)redirect("/login"); const permissions=await getEffectivePermissions(user.id,tenantId); if(!permissions.includes("communications:read" as never))redirect("/"); const ar=(await cookies()).get("core-system-locale")?.value==="ar";
  const [{data:conversations},{data:requests},{data:users},{data:patients}] = await Promise.all([
    supabase.from("communication_conversations").select("id,subject,kind,status,created_at,clinic_patient_id,patient:clinic_patients(first_name,last_name)").eq("tenant_id",tenantId).order("updated_at",{ascending:false}).limit(30),
    supabase.from("communication_requests").select("id,title,priority,status,due_at,created_at,clinic_patient_id,patient:clinic_patients(first_name,last_name)").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(20),
    supabase.from("clinic_users").select("id,full_name,email").eq("tenant_id",tenantId).eq("is_active",true).is("deleted_at",null).order("full_name"),
    supabase.from("clinic_patients").select("id,first_name,last_name,phone_primary,preferred_channel").eq("tenant_id",tenantId).is("deleted_at",null).order("first_name").limit(200),
  ]);
  async function addConversation(fd:FormData){"use server";await createConversation({subject:String(fd.get("subject")||""),recipientUserId:String(fd.get("recipient")||"")||undefined,kind:(String(fd.get("kind")||"internal") as "internal"|"patient"),clinicPatientId:String(fd.get("patient")||"")||undefined});}
  async function addRequest(fd:FormData){"use server";await createCommunicationRequest({title:String(fd.get("title")||""),details:String(fd.get("details")||"")||undefined,assigneeUserId:String(fd.get("assignee")||"")||null,clinicPatientId:String(fd.get("patient")||"")||null,priority:String(fd.get("priority")||"normal") as "low"|"normal"|"high"|"urgent"});}
  async function addMessage(fd:FormData){"use server";await sendInternalMessage({conversationId:String(fd.get("conversation")||""),body:String(fd.get("body")||"")});}
  const patientRows=patients??[];
  return <div className="space-y-8"><header><h1 className="text-2xl font-bold">{ar?"الاتصالات":"Communications"}</h1><p className="mt-1 text-sm text-muted-foreground">{ar?"سجل اتصالات المرضى والرسائل الداخلية والطلبات التشغيلية في سياق واحد، مع بقاء المواعيد والرحلة في نطاقاتها الأصلية.":"Record patient communications, internal messages and operational requests in one context while appointments and journey ownership remain in their domains."}</p></header>
    <div className="grid gap-6 xl:grid-cols-3">
      <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"اتصال جديد":"New communication"}</h2><form action={addConversation} className="space-y-2"><select name="kind" className="w-full rounded border p-2"><option value="patient">{ar?"مع مريض":"Patient"}</option><option value="internal">{ar?"داخلي":"Internal"}</option></select><select name="patient" className="w-full rounded border p-2"><option value="">{ar?"المريض (اختياري للداخلي)":"Patient (optional for internal)"}</option>{patientRows.map((p:any)=><option key={p.id} value={p.id}>{p.first_name} {p.last_name} · {p.phone_primary||""}</option>)}</select><input name="subject" placeholder={ar?"الموضوع":"Subject"} className="w-full rounded border p-2"/><select name="recipient" className="w-full rounded border p-2"><option value="">{ar?"الموظف المرتبط (اختياري)":"Linked staff member (optional)"}</option>{(users??[]).map((u:any)=><option key={u.id} value={u.id}>{u.full_name||u.email}</option>)}</select><button className="w-full rounded bg-primary px-4 py-2 text-primary-foreground">{ar?"بدء الاتصال":"Start communication"}</button></form></section>
      <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"رسالة / ملاحظة":"Message / note"}</h2><form action={addMessage} className="space-y-2"><select name="conversation" required className="w-full rounded border p-2"><option value="">{ar?"المحادثة":"Conversation"}</option>{(conversations??[]).map((c:any)=><option key={c.id} value={c.id}>{c.subject||"No subject"}{c.patient?` · ${c.patient.first_name} ${c.patient.last_name}`:""}</option>)}</select><textarea name="body" required rows={5} placeholder={ar?"اكتب سجل الاتصال أو الرسالة":"Record the call/message/contact"} className="w-full rounded border p-2"/><button className="w-full rounded bg-primary px-4 py-2 text-primary-foreground">{ar?"إرسال/تسجيل":"Send / record"}</button></form></section>
      <section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"طلب تشغيلي":"Operational request"}</h2><form action={addRequest} className="space-y-2"><input name="title" required placeholder={ar?"عنوان الطلب":"Request title"} className="w-full rounded border p-2"/><textarea name="details" rows={3} placeholder={ar?"التفاصيل":"Details"} className="w-full rounded border p-2"/><select name="patient" className="w-full rounded border p-2"><option value="">{ar?"مريض مرتبط":"Related patient"}</option>{patientRows.map((p:any)=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select><select name="assignee" className="w-full rounded border p-2"><option value="">{ar?"تعيين لاحقًا":"Assign later"}</option>{(users??[]).map((u:any)=><option key={u.id} value={u.id}>{u.full_name||u.email}</option>)}</select><select name="priority" className="w-full rounded border p-2"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="urgent">Urgent</option></select><button className="w-full rounded bg-primary px-4 py-2 text-primary-foreground">{ar?"إنشاء الطلب":"Create request"}</button></form></section>
    </div>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"سجل الاتصالات":"Communication history"}</h2><div className="divide-y">{(conversations??[]).map((c:any)=><div key={c.id} className="flex justify-between gap-3 py-3"><span>{c.subject||"No subject"}{c.patient&&<span className="text-sm text-muted-foreground"> · {c.patient.first_name} {c.patient.last_name}</span>}</span><span className="text-sm text-muted-foreground">{c.kind} · {c.status}</span></div>)}{!(conversations??[]).length&&<p className="text-sm text-muted-foreground">No communications yet.</p>}</div></section><section className="rounded-lg border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{ar?"الطلبات التشغيلية":"Operational requests"}</h2><div className="divide-y">{(requests??[]).map((r:any)=><div key={r.id} className="flex justify-between gap-3 py-3"><span>{r.title}{r.patient&&<span className="text-sm text-muted-foreground"> · {r.patient.first_name} {r.patient.last_name}</span>}</span><span className="text-sm text-muted-foreground">{r.priority} · {r.status}</span></div>)}{!(requests??[]).length&&<p className="text-sm text-muted-foreground">No requests yet.</p>}</div></section></div>
  </div>;
}
