import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { createClient } from "@/infrastructure/supabase/server";
import { resolveTenantId } from "@/core/auth/resolveTenantId";
import { getEffectivePermissions } from "@/core/permissions/permissionEngine";
import { FinancialResourceReport } from "@/features/financial-resources/financial-resource-report";
import { FinancialResourcesHome } from "@/features/financial-resources/financial-resources-home";
import type { Locale } from "@/core/i18n/messages";
export default async function FinancialResourcesPage({searchParams}:{searchParams?:Promise<{section?:string}>}){
 const db=await createClient();const{data:{user},error}=await db.auth.getUser();if(error||!user)redirect("/login");const tenantId=await resolveTenantId(user.id);if(!tenantId)redirect("/login");const permissions=await getEffectivePermissions(user.id,tenantId);const section=(await searchParams)?.section;
 const routes:Record<string,string>={invoices:"/invoices",payments:"/financial-resources/payments",plans:"/financial-resources/financial-plans",insurance:"/financial-resources/insurance",inventory:"/inventory",purchasing:"/financial-resources/purchasing",expenses:"/financial-resources/expenses"};if(section&&routes[section])redirect(routes[section]);
 const locale:Locale=(await cookies()).get("core-system-locale")?.value==="ar"?"ar":"en";const today=new Date();const from=new Date(today.getFullYear(),today.getMonth(),1).toISOString().slice(0,10);const to=today.toISOString().slice(0,10);
 const[tenant,invoices,items,suppliers,report]=await Promise.all([db.from("master_tenants").select("currency").eq("id",tenantId).maybeSingle(),permissions.includes("invoices:read")?db.from("clinic_invoices").select("id,total_subunits,amount_paid_subunits,amount_due_subunits").eq("tenant_id",tenantId).limit(500):Promise.resolve({data:[],error:null}),permissions.includes("inventory:read")?db.from("inventory_items").select("id").eq("tenant_id",tenantId).eq("is_active",true).is("deleted_at",null).limit(1000):Promise.resolve({data:[],error:null}),permissions.includes("purchasing:read")?db.from("suppliers").select("id").eq("tenant_id",tenantId).is("deleted_at",null).limit(500):Promise.resolve({data:[],error:null}),permissions.includes("reports:read")?db.rpc("get_financial_resource_summary",{p_tenant_id:tenantId,p_from_date:from,p_to_date:to}):Promise.resolve({data:null,error:null})]);
 const due=(invoices.data??[]).reduce((s:number,i:any)=>s+(i.amount_due_subunits??Math.max(i.total_subunits-i.amount_paid_subunits,0)),0);const summary=(report.data&&typeof report.data==='object'?report.data:{}) as Record<string,number>;
 return <div className="space-y-6 p-4 sm:p-6 lg:p-8"><FinancialResourcesHome locale={locale} currency={tenant.data?.currency??"JOD"} due={due} invoiceCount={(invoices.data??[]).length} itemCount={(items.data??[]).length} supplierCount={(suppliers.data??[]).length} canInvoice={permissions.includes("invoices:create")} canPayment={permissions.includes("invoices:payment")||permissions.includes("expenses:manage")} canPlans={permissions.includes("invoices:update")} canInsurance={permissions.includes("insurance:manage")} canInventory={permissions.includes("inventory:read")} canPurchasing={permissions.includes("purchasing:manage")} canExpense={permissions.includes("expenses:manage")}/>{permissions.includes("reports:read")&&<FinancialResourceReport locale={locale} currency={tenant.data?.currency??"JOD"} summary={summary}/>}</div>;
}
