"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/shared/components/ui/button"; import { Input } from "@/shared/components/ui/input"; import { Label } from "@/shared/components/ui/label"; import { Textarea } from "@/shared/components/ui/textarea"; import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/shared/components/ui/dialog"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select"; import { Calendar, User, Search, UserPlus, Phone } from "lucide-react";
import { createAgendaEvent, updateAgendaEvent } from "@/domain/agenda/agenda.actions"; import { usePermissions } from "@/core/permissions/usePermissions"; import { useI18n } from "@/core/i18n/I18nProvider"; import type { AgendaEventWithRelations } from "@/domain/agenda/agenda.types";
interface PatientOption { id: string; name: string; phone: string; } interface DoctorOption { id: string; name: string; specialization: string | null; } interface RoomOption { id: string; name: string; } interface ProcedureOption { id: string; name: string; duration: number; } interface AgendaEventFormProps { isOpen: boolean; onClose: () => void; tenantId: string; userId: string; event?: AgendaEventWithRelations | null; patients: PatientOption[]; doctors: DoctorOption[]; rooms: RoomOption[]; procedures: ProcedureOption[]; defaultDate?: string; defaultPatientId?: string; } type PatientMode = "search" | "new";

export function AgendaEventForm({ isOpen, onClose, tenantId, userId, event, patients, doctors, rooms, procedures, defaultDate, defaultPatientId }: AgendaEventFormProps) {
  const router = useRouter(); const { locale, agendaForm: t } = useI18n(); const { hasPermission, isLoading: permsLoading } = usePermissions(); const isEditMode = !!event; const [patientMode, setPatientMode] = useState<PatientMode>("search"); const [patientId, setPatientId] = useState<string | null>(defaultPatientId ?? null); const [tempPatientName, setTempPatientName] = useState(""); const [tempPatientPhone, setTempPatientPhone] = useState(""); const [searchQuery, setSearchQuery] = useState(""); const [doctorId, setDoctorId] = useState(""); const [roomId, setRoomId] = useState(""); const [procedureId, setProcedureId] = useState(""); const [date, setDate] = useState(defaultDate ?? new Date().toISOString().split("T")[0]); const [startTime, setStartTime] = useState("09:00"); const [endTime, setEndTime] = useState("09:30"); const [notes, setNotes] = useState(""); const [isLoading, setIsLoading] = useState(false); const [error, setError] = useState("");
  const signature = `${isOpen}:${event?.id ?? "new"}:${defaultDate ?? ""}:${defaultPatientId ?? ""}`; const [lastSignature, setLastSignature] = useState(signature);
  if (signature !== lastSignature) { setLastSignature(signature); if (event) { setPatientMode("search"); setPatientId(event.patient_id || null); setDoctorId(event.doctor_id || ""); setRoomId(event.room_id || ""); setProcedureId(event.procedure_id || ""); setDate(event.scheduled_start.split("T")[0]); setStartTime(event.scheduled_start.split("T")[1]?.slice(0, 5) || "09:00"); setEndTime(event.scheduled_end.split("T")[1]?.slice(0, 5) || "09:30"); setNotes(event.notes || ""); } else { setPatientMode("search"); setPatientId(defaultPatientId ?? null); setDoctorId(""); setRoomId(""); setProcedureId(""); setDate(defaultDate ?? new Date().toISOString().split("T")[0]); setStartTime("09:00"); setEndTime("09:30"); setNotes(""); } setTempPatientName(""); setTempPatientPhone(""); setSearchQuery(""); setError(""); }
  const requiredPermission = isEditMode ? "agenda:update" : "agenda:create"; const permissionError = !permsLoading && isOpen && !hasPermission(requiredPermission) ? (isEditMode ? t.accessDeniedUpdate : t.accessDeniedCreate) : "";
  const filteredPatients = useMemo(() => { const query = searchQuery.trim().toLowerCase(); if (!query) return []; return patients.filter((p) => p.name.toLowerCase().includes(query) || p.phone.includes(query)); }, [patients, searchQuery]);
  function autoEnd(nextStart: string, nextProcedure: string) { const procedure = procedures.find((p) => p.id === nextProcedure); if (!procedure) return null; const [hours, minutes] = nextStart.split(":").map(Number); if (Number.isNaN(hours) || Number.isNaN(minutes)) return null; const start = new Date(); start.setHours(hours, minutes, 0, 0); const end = new Date(start.getTime() + procedure.duration * 60000); return `${String(end.getHours()).padStart(2, "0")}:${String(end.getMinutes()).padStart(2, "0")}`; }
  const localizeError = (code: string | null | undefined) => { if (!code) return t.errors.unexpected; const [key, ...args] = code.split("|"); const e = t.errors; if (key === "AGENDA_CONFLICT_DOCTOR") return e.doctorConflict.replace("{time}", args[0] || ""); if (key === "AGENDA_CONFLICT_ROOM") return e.roomConflict.replace("{time}", args[0] || ""); if (key === "AGENDA_CONFLICT_PATIENT") return e.patientConflict.replace("{time}", args[0] || ""); if (key === "AGENDA_INVALID_STATUS_TRANSITION") return e.invalidStatusTransition.replace("{from}", args[0] || "").replace("{to}", args[1] || ""); if (key === "AGENDA_INVALID_CANCELLATION") return e.invalidCancellation.replace("{status}", args[0] || ""); const direct: Record<string, string> = { AGENDA_TENANT_MISSING: e.tenantMissing, AGENDA_INVALID_TIME_RANGE: e.invalidTimeRange, AGENDA_DURATION_TOO_SHORT: e.invalidTimeRange, AGENDA_DURATION_TOO_LONG: e.invalidTimeRange, AGENDA_DATABASE_ERROR: e.database }; return direct[key] || e.unexpected; };
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); if (permissionError) return; if (patientMode === "search" && !patientId) { setError(t.requiredPatient); return; } if (patientMode === "new" && !tempPatientName.trim()) { setError(t.requiredName); return; } if (patientMode === "new" && !tempPatientPhone.trim()) { setError(t.requiredPhone); return; } if (!doctorId) { setError(t.requiredDoctor); return; } setIsLoading(true); setError(""); const formData = new FormData(); formData.append("tenant_id", tenantId); formData.append("doctor_id", doctorId); formData.append("scheduled_start", `${date}T${startTime}:00`); formData.append("scheduled_end", `${date}T${endTime}:00`); formData.append("created_by", userId); if (roomId) formData.append("room_id", roomId); if (procedureId) formData.append("procedure_id", procedureId); if (notes) formData.append("notes", notes); if (patientMode === "search" && patientId) formData.append("patient_id", patientId); if (patientMode === "new") { formData.append("temp_patient_name", tempPatientName.trim()); formData.append("temp_patient_phone", tempPatientPhone.trim()); } try { const result = isEditMode && event ? await updateAgendaEvent(formData) : await createAgendaEvent(formData); if (result.error) setError(localizeError(result.error)); else { onClose(); router.refresh(); } } finally { setIsLoading(false); } }

  return <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto" dir={locale === "ar" ? "rtl" : "ltr"}><DialogHeader><DialogTitle className="flex items-center gap-2"><Calendar className="h-5 w-5" />{isEditMode ? t.editTitle : t.newTitle}</DialogTitle></DialogHeader><form onSubmit={handleSubmit} className="space-y-4">
    {permissionError && <div className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{permissionError}</div>}{error && <div className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="space-y-3"><Label className="flex items-center gap-2"><User className="h-4 w-4" />{t.patient}</Label>{!isEditMode && <div className="flex gap-2"><Button type="button" size="sm" variant={patientMode === "search" ? "default" : "outline"} onClick={() => setPatientMode("search")}><Search className="me-1 h-3 w-3" />{t.existing}</Button><Button type="button" size="sm" variant={patientMode === "new" ? "default" : "outline"} onClick={() => setPatientMode("new")}><UserPlus className="me-1 h-3 w-3" />{t.newPatient}</Button></div>}{patientMode === "search" ? <div className="space-y-2"><Input placeholder={t.searchPlaceholder} value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} />{searchQuery.trim() && <div className="max-h-40 overflow-y-auto rounded-md border">{filteredPatients.length ? filteredPatients.map((p) => <button type="button" key={p.id} className={`flex w-full items-center justify-between p-2 text-start hover:bg-muted ${patientId === p.id ? "bg-primary/10" : ""}`} onClick={() => setPatientId(p.id)}><span><span className="block text-sm font-medium">{p.name}</span><span className="flex items-center gap-1 text-xs text-muted-foreground"><Phone className="h-3 w-3" />{p.phone}</span></span>{patientId === p.id && <span className="text-primary">✓</span>}</button>) : <div className="p-3 text-center text-sm text-muted-foreground">{t.noPatient}</div>}</div>}{patientId && <div className="rounded-md bg-primary/5 p-2 text-sm">{t.selected}: {patients.find((p) => p.id === patientId)?.name ?? patientId}</div>}</div> : <div className="grid gap-2 sm:grid-cols-2"><div><Label>{t.newPatientName}</Label><Input value={tempPatientName} onChange={(e) => setTempPatientName(e.target.value)} /></div><div><Label>{t.phone}</Label><Input value={tempPatientPhone} onChange={(e) => setTempPatientPhone(e.target.value)} /></div></div>}</div>
    <div className="grid gap-4 sm:grid-cols-2"><div><Label>{t.doctor}</Label><Select value={doctorId} onValueChange={setDoctorId}><SelectTrigger><SelectValue placeholder={t.chooseDoctor} /></SelectTrigger><SelectContent>{doctors.map((d) => <SelectItem key={d.id} value={d.id}>{d.name}{d.specialization ? ` — ${d.specialization}` : ""}</SelectItem>)}</SelectContent></Select></div><div><Label>{t.room}</Label><Select value={roomId || "none"} onValueChange={(v) => setRoomId(v === "none" ? "" : v)}><SelectTrigger><SelectValue placeholder={t.chooseRoom} /></SelectTrigger><SelectContent><SelectItem value="none">—</SelectItem>{rooms.map((r) => <SelectItem key={r.id} value={r.id}>{r.name}</SelectItem>)}</SelectContent></Select></div></div>
    <div><Label>{t.procedure}</Label><Select value={procedureId || "none"} onValueChange={(v) => { setProcedureId(v === "none" ? "" : v); if (v !== "none") { const next = autoEnd(startTime, v); if (next) setEndTime(next); } }}><SelectTrigger><SelectValue placeholder={t.chooseProcedure} /></SelectTrigger><SelectContent><SelectItem value="none">—</SelectItem>{procedures.map((p) => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div>
    <div className="grid gap-4 sm:grid-cols-3"><div><Label>{t.date}</Label><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></div><div><Label>{t.startTime}</Label><Input type="time" value={startTime} onChange={(e) => { setStartTime(e.target.value); const next = autoEnd(e.target.value, procedureId); if (next) setEndTime(next); }} /></div><div><Label>{t.endTime}</Label><Input type="time" value={endTime} onChange={(e) => setEndTime(e.target.value)} /></div></div><div><Label>{t.notes}</Label><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder={t.notesPlaceholder} /></div>
    <DialogFooter><Button type="button" variant="outline" onClick={onClose}>{t.cancel}</Button><Button type="submit" disabled={isLoading || !!permissionError}>{isLoading ? t.saving : isEditMode ? t.save : t.create}</Button></DialogFooter>
  </form></DialogContent></Dialog>;
}
