"use client";

import { useState } from "react";
import { usePermissions } from "@/core/permissions/usePermissions";
import { useTenantId } from "@/core/auth/useTenantId";
import { useI18n } from "@/core/i18n/I18nProvider";
import { useClinicUsers } from "@/domain/users/users.queries";
import { useRoles } from "@/domain/roles/roles.queries";
import { createClinicUser, updateClinicUser, toggleClinicUserActive } from "@/domain/users/users.actions";
import type { ClinicUserWithRole } from "@/domain/users/users.types";
import type { UserRole } from "@/core/permissions/types";
import { Button } from "@/shared/components/ui/button"; import { Input } from "@/shared/components/ui/input"; import { Label } from "@/shared/components/ui/label"; import { Badge } from "@/shared/components/ui/badge"; import { Card, CardContent } from "@/shared/components/ui/card"; import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/shared/components/ui/dialog"; import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/shared/components/ui/select"; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/shared/components/ui/table"; import { Switch } from "@/shared/components/ui/switch"; import { Users, Plus, Pencil, Mail, Phone, ShieldCheck, Shield, AlertTriangle, UserPlus } from "lucide-react";

export function UsersManager() {
  const { locale, admin: a } = useI18n(); const { tenantId } = useTenantId(); const { hasPermission } = usePermissions(); const { data: users = [], isLoading, error, refetch } = useClinicUsers(tenantId); const { data: roles = [] } = useRoles(tenantId);
  const [createOpen, setCreateOpen] = useState(false); const [editOpen, setEditOpen] = useState(false); const [editingUser, setEditingUser] = useState<ClinicUserWithRole | null>(null); const [actionError, setActionError] = useState<string | null>(null);
  const canCreate = hasPermission("users:create"); const canUpdate = hasPermission("users:update"); const canDelete = hasPermission("users:delete"); const dateLocale = locale === "ar" ? "ar" : "en-US-u-nu-latn"; const direction = locale === "ar" ? "rtl" : "ltr";
  if (isLoading) return <div className="flex items-center justify-center py-12" dir={direction}><div className="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent" /><span className="ms-3 text-muted-foreground">{a.users.loading}</span></div>;
  if (error) return <div className="rounded-lg border border-destructive/20 bg-destructive/5 p-6 text-center" dir={direction}><AlertTriangle className="mx-auto mb-2 h-8 w-8 text-destructive" /><p className="font-medium text-destructive">{a.users.loadFailed}</p></div>;
  const actionResultError = (success: boolean) => success ? null : a.users.actionFailed;
  return <div className="space-y-6" dir={direction}>
    <div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-primary/10 p-2"><Users className="h-5 w-5 text-primary" /></div><div><h2 className="text-xl font-semibold">{a.users.title}</h2><p className="text-sm text-muted-foreground">{users.length} {a.users.count}</p></div></div>{canCreate && <Button onClick={() => { setActionError(null); setCreateOpen(true); }}><Plus className="me-2 h-4 w-4" />{a.users.newUser}</Button>}</div>
    {actionError && <div className="rounded-md border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">{actionError}</div>}
    <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>{a.users.user}</TableHead><TableHead>{a.users.role}</TableHead><TableHead>{a.users.status}</TableHead><TableHead>{a.users.createdAt}</TableHead><TableHead>{a.users.actions}</TableHead></TableRow></TableHeader><TableBody>{users.length === 0 ? <TableRow><TableCell colSpan={5} className="py-8 text-center text-muted-foreground">{a.users.noUsers}</TableCell></TableRow> : users.map(user => <TableRow key={user.id} className={!user.is_active ? "opacity-60" : ""}><TableCell><div className="flex flex-col gap-0.5"><span className="font-medium">{user.full_name || "—"}</span><span className="flex items-center gap-1 text-xs text-muted-foreground"><Mail className="h-3 w-3" />{user.email || "—"}</span>{user.phone && <span className="flex items-center gap-1 text-xs text-muted-foreground"><Phone className="h-3 w-3" />{user.phone}</span>}{!user.auth_user_id && <Badge variant="outline" className="mt-1 w-fit text-xs"><AlertTriangle className="me-1 h-3 w-3" />{a.users.pendingAuth}</Badge>}</div></TableCell><TableCell><div className="flex items-center gap-2">{user.is_system_role ? <ShieldCheck className="h-4 w-4" /> : <Shield className="h-4 w-4" />}<span className="text-sm">{locale === "ar" ? user.role_name_ar || user.role_name || user.role : user.role_name || user.role_name_ar || user.role}</span></div></TableCell><TableCell><Badge variant={user.is_active ? "default" : "secondary"}>{user.is_active ? a.users.active : a.users.inactive}</Badge></TableCell><TableCell className="text-sm text-muted-foreground">{user.created_at ? new Date(user.created_at).toLocaleDateString(dateLocale, { numberingSystem: "latn" }) : "—"}</TableCell><TableCell><div className="flex items-center gap-2">{canUpdate && <Button variant="ghost" size="sm" aria-label={a.users.editTitle} onClick={() => { setEditingUser(user); setActionError(null); setEditOpen(true); }}><Pencil className="h-4 w-4" /></Button>}{canDelete && <div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">{user.is_active ? a.users.active : a.users.inactive}</span><Switch checked={user.is_active} onCheckedChange={async checked => { setActionError(null); const result = await toggleClinicUserActive(user.id, checked); if (!result.success) setActionError(actionResultError(result.success)); else void refetch(); }} /></div>}</div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <CreateUserDialog open={createOpen} onOpenChange={setCreateOpen} roles={roles} onError={setActionError} onSuccess={() => { setCreateOpen(false); void refetch(); }} />
    {editingUser && <EditUserDialog open={editOpen} onOpenChange={setEditOpen} user={editingUser} roles={roles} onError={setActionError} onSuccess={() => { setEditOpen(false); setEditingUser(null); void refetch(); }} />}
  </div>;
}

type RoleOption = { id: string; role_key: string; role_name: string; role_name_ar: string | null; is_system_role: boolean };
type DialogProps = { open: boolean; onOpenChange: (value: boolean) => void; roles: RoleOption[]; onError: (message: string | null) => void; onSuccess: () => void };
function CreateUserDialog({ open, onOpenChange, roles, onError, onSuccess }: DialogProps) {
  const { admin: a } = useI18n(); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [role, setRole] = useState<UserRole>("receptionist"); const [roleTemplateId, setRoleTemplateId] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const systemRoles = roles.filter(r => r.is_system_role && r.role_key !== "super_admin");
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); onError(null); setSubmitting(true); const selected = systemRoles.find(r => r.role_key === role); const result = await createClinicUser({ full_name: fullName, email, phone: phone || undefined, role, role_template_id: selected?.id ?? roleTemplateId }); setSubmitting(false); if (!result.success) onError(a.users.actionFailed); else { setFullName(""); setEmail(""); setPhone(""); setRole("receptionist"); setRoleTemplateId(null); onSuccess(); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle className="flex items-center gap-2"><UserPlus className="h-5 w-5" />{a.users.newUser}</DialogTitle><DialogDescription>{a.users.createDescription}</DialogDescription></DialogHeader><form onSubmit={handleSubmit} className="space-y-4"><div className="space-y-2"><Label htmlFor="fullName">{a.users.fullName}</Label><Input id="fullName" value={fullName} onChange={e => setFullName(e.target.value)} placeholder={a.users.placeholderName} required /></div><div className="space-y-2"><Label htmlFor="email">{a.users.email}</Label><Input id="email" type="email" value={email} onChange={e => setEmail(e.target.value)} required /></div><div className="space-y-2"><Label htmlFor="phone">{a.users.phone}</Label><Input id="phone" value={phone} onChange={e => setPhone(e.target.value)} placeholder={a.users.placeholderPhone} /></div><div className="space-y-2"><Label htmlFor="role">{a.users.role}</Label><Select value={role} onValueChange={v => { setRole(v as UserRole); setRoleTemplateId(systemRoles.find(r => r.role_key === v)?.id ?? null); }}><SelectTrigger id="role"><SelectValue placeholder={a.users.chooseRole} /></SelectTrigger><SelectContent>{systemRoles.map(r => <SelectItem key={r.id} value={r.role_key}>{localeLabel(r)}</SelectItem>)}</SelectContent></Select></div><DialogFooter className="gap-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>{a.users.cancel}</Button><Button type="submit" disabled={submitting}>{submitting ? a.users.creating : a.users.create}</Button></DialogFooter></form></DialogContent></Dialog>;
  function localeLabel(r: RoleOption) { return a === undefined ? r.role_name : r.role_name_ar || r.role_name; }
}
function EditUserDialog({ open, onOpenChange, user, roles, onError, onSuccess }: DialogProps & { user: ClinicUserWithRole }) {
  const { locale, admin: a } = useI18n(); const [fullName, setFullName] = useState(user.full_name || ""); const [email, setEmail] = useState(user.email || ""); const [phone, setPhone] = useState(user.phone || ""); const [role, setRole] = useState<UserRole>(user.role); const [roleTemplateId, setRoleTemplateId] = useState<string | null>(user.role_template_id); const [submitting, setSubmitting] = useState(false); const systemRoles = roles.filter(r => r.is_system_role && r.role_key !== "super_admin");
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); onError(null); setSubmitting(true); const selected = systemRoles.find(r => r.role_key === role); const result = await updateClinicUser({ id: user.id, full_name: fullName, email, phone: phone || undefined, role, role_template_id: selected?.id ?? roleTemplateId }); setSubmitting(false); if (!result.success) onError(a.users.actionFailed); else onSuccess(); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>{a.users.editTitle}</DialogTitle></DialogHeader><form onSubmit={handleSubmit} className="space-y-4"><div className="space-y-2"><Label htmlFor="edit-fullName">{a.users.fullName}</Label><Input id="edit-fullName" value={fullName} onChange={e => setFullName(e.target.value)} required /></div><div className="space-y-2"><Label htmlFor="edit-email">{a.users.email}</Label><Input id="edit-email" type="email" value={email} onChange={e => setEmail(e.target.value)} required /></div><div className="space-y-2"><Label htmlFor="edit-phone">{a.users.phone}</Label><Input id="edit-phone" value={phone} onChange={e => setPhone(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="edit-role">{a.users.role}</Label><Select value={role} onValueChange={v => { setRole(v as UserRole); setRoleTemplateId(systemRoles.find(r => r.role_key === v)?.id ?? null); }}><SelectTrigger id="edit-role"><SelectValue placeholder={a.users.chooseRole} /></SelectTrigger><SelectContent>{systemRoles.map(r => <SelectItem key={r.id} value={r.role_key}>{locale === "ar" ? r.role_name_ar || r.role_name : r.role_name || r.role_name_ar}</SelectItem>)}</SelectContent></Select></div><DialogFooter className="gap-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>{a.users.cancel}</Button><Button type="submit" disabled={submitting}>{submitting ? a.users.saving : a.users.save}</Button></DialogFooter></form></DialogContent></Dialog>;
}
