"use client";

import { useState, useEffect } from "react";
import { useI18n } from "@/core/i18n/I18nProvider";
import { usePermissions } from "@/core/permissions/usePermissions";
import { isFeatureEnabled } from "@/core/features/featureRegistry";
import { reportModules } from "@/domain/reports/moduleRegistry";
import { getReportsByModule } from "@/domain/reports/reportRegistry";
import { ReportViewer } from "./report-viewer";
import { Button } from "@/shared/components/ui/button";
import { Label } from "@/shared/components/ui/label";
import { Printer, FileDown, CalendarRange, BarChart3 } from "lucide-react";
import { createClient } from "@/infrastructure/supabase/client";
import { runReport, type ReportResult } from "@/domain/reports/reports.queries";
import type { Permission } from "@/core/permissions/types";

function SimpleSelect({ label, value, onChange, options, placeholder, disabled }: { label: string; value: string; onChange: (v: string) => void; options: { value: string; label: string; labelAr: string }[]; placeholder: string; disabled?: boolean }) { return <div className="space-y-1.5"><Label>{label}</Label><select value={value} onChange={e => onChange(e.target.value)} disabled={disabled} className="flex h-10 w-full rounded-md border bg-background px-3 py-2 text-sm"> <option value="">{placeholder}</option>{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div>; }

export function ReportsShell() {
  const { locale, messages, admin: a } = useI18n(); const { hasPermission, isLoading: permsLoading } = usePermissions(); const [tenantId, setTenantId] = useState<string | null>(null); const [moduleKey, setModuleKey] = useState(""); const [reportKey, setReportKey] = useState(""); const [startDate, setStartDate] = useState(() => { const d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().split("T")[0]; }); const [endDate, setEndDate] = useState(() => { const d = new Date(); return new Date(d.getFullYear(), d.getMonth() + 1, 0).toISOString().split("T")[0]; }); const [modules, setModules] = useState<typeof reportModules>([]); const [result, setResult] = useState<ReportResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; void (async () => { const supabase = createClient(); const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) return; const { data } = await supabase.from("clinic_users").select("tenant_id").eq("auth_user_id", session.user.id).limit(1).maybeSingle(); if (active && data?.tenant_id) setTenantId(data.tenant_id); })(); return () => { active = false; }; }, []);
  useEffect(() => { if (permsLoading || !tenantId) return; void (async () => { const allowed = []; for (const mod of reportModules) { if (hasPermission(mod.requiredPermission as Permission) && await isFeatureEnabled(tenantId, mod.key)) allowed.push(mod); } setModules(allowed); })(); }, [permsLoading, tenantId, hasPermission]);
  const reports = moduleKey ? getReportsByModule(moduleKey) : []; const selected = reports.find(r => r.key === reportKey); const labelFor = (r: { label: string; labelAr: string }) => locale === "ar" ? r.labelAr || r.label : r.label;
  const run = async () => { if (!selected) return; setLoading(true); setError(null); try { setResult(await runReport(selected.dataSource, selected.needsDateRange ? startDate : undefined, selected.needsDateRange ? endDate : undefined)); } catch { setResult(null); setError(messages.common.unexpectedError); } finally { setLoading(false); } };
  const handleModuleChange = (value: string) => { setModuleKey(value); setReportKey(""); setResult(null); setError(null); };
  return <div className="space-y-6" dir={locale === "ar" ? "rtl" : "ltr"}><div className="rounded-lg border bg-card p-4 shadow-sm"><div className="mb-2 flex items-center gap-2"><BarChart3 className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold">{a.reports.title}</h2></div><p className="text-sm text-muted-foreground">{a.reports.description}</p></div><div className="space-y-4 rounded-lg border bg-card p-4 shadow-sm"><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><SimpleSelect label={a.reports.module} value={moduleKey} onChange={handleModuleChange} options={modules.map(m => ({ value: m.key, label: labelFor(m), labelAr: m.labelAr }))} placeholder={a.reports.chooseModule} disabled={permsLoading || modules.length === 0} /><SimpleSelect label={a.reports.report} value={reportKey} onChange={setReportKey} options={reports.map(r => ({ value: r.key, label: labelFor(r), labelAr: r.labelAr }))} placeholder={moduleKey ? a.reports.chooseReport : a.reports.chooseModuleFirst} disabled={!moduleKey || reports.length === 0} /></div>{selected?.needsDateRange && <div className="flex flex-col gap-3 sm:flex-row"><div><Label>{a.reports.from}</Label><input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} className="mt-1 h-10 rounded-md border bg-background px-3 text-sm" /></div><div><Label>{a.reports.to}</Label><input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} className="mt-1 h-10 rounded-md border bg-background px-3 text-sm" /></div></div>}<div className="flex flex-wrap gap-2"><Button onClick={() => void run()} disabled={!selected || loading}><CalendarRange className="me-2 h-4 w-4" />{loading ? a.reports.loading : a.reports.view}</Button><Button variant="outline" onClick={() => window.print()} disabled={!result}><Printer className="me-2 h-4 w-4" />{a.reports.print}</Button><Button variant="outline" onClick={() => window.print()} disabled={!result}><FileDown className="me-2 h-4 w-4" />{a.reports.exportPdf}</Button></div></div>{error && <div className="rounded-lg border border-destructive bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}{result && <ReportViewer reportLabel={selected ? labelFor(selected) : ""} result={result} />}</div>;
}
