-- Workforce & Operations reconciliation snapshot.
-- This migration records the live Workforce Operations schema in repository
-- migration lineage without deleting or recreating existing live data.
-- It is intentionally idempotent: existing tables, indexes, policies and
-- trigger are preserved; missing objects can be reconstructed on a fresh DB.

create table if not exists public.workforce_leave_types (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, name text not null, name_ar text, annual_entitlement_days numeric not null default 0, carry_forward_days numeric not null default 0, paid boolean not null default true, status text not null default 'active', created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.workforce_leave_requests (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, employee_id uuid not null, leave_type_id uuid not null, starts_on date not null, ends_on date not null, days numeric not null, reason text, status text not null default 'pending', approved_by uuid, approved_at timestamptz, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.workforce_payroll_periods (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, period_start date not null, period_end date not null, status text not null default 'open', currency text not null default 'JOD', locked_at timestamptz, locked_by uuid, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.workforce_payroll_entries (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, payroll_period_id uuid not null, employee_id uuid not null, base_salary_subunits integer not null default 0, allowances_subunits integer not null default 0, overtime_subunits integer not null default 0, bonuses_subunits integer not null default 0, commissions_subunits integer not null default 0, deductions_subunits integer not null default 0, net_subunits integer not null default 0, status text not null default 'draft', notes text, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.workforce_candidates (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, staffing_need_id uuid, first_name text not null, last_name text not null, phone text, email text, stage text not null default 'candidate', notes text, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.workforce_benefits (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, employee_id uuid not null, benefit_name text not null, benefit_name_ar text, value_subunits integer not null default 0, currency text not null default 'JOD', starts_on date, ends_on date, status text not null default 'active', notes text, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create unique index if not exists workforce_leave_types_pkey on public.workforce_leave_types(id);
create unique index if not exists workforce_leave_types_tenant_id_id_key on public.workforce_leave_types(tenant_id,id);
create unique index if not exists workforce_leave_requests_pkey on public.workforce_leave_requests(id);
create index if not exists workforce_leave_tenant_employee_idx on public.workforce_leave_requests(tenant_id,employee_id,status);
create unique index if not exists workforce_payroll_periods_pkey on public.workforce_payroll_periods(id);
create unique index if not exists workforce_payroll_periods_tenant_id_id_key on public.workforce_payroll_periods(tenant_id,id);
create unique index if not exists workforce_payroll_periods_tenant_id_period_start_period_end_key on public.workforce_payroll_periods(tenant_id,period_start,period_end);
create index if not exists workforce_payroll_tenant_period_idx on public.workforce_payroll_periods(tenant_id,period_start,period_end);
create unique index if not exists workforce_payroll_entries_pkey on public.workforce_payroll_entries(id);
create unique index if not exists workforce_payroll_entries_payroll_period_id_employee_id_key on public.workforce_payroll_entries(payroll_period_id,employee_id);
create unique index if not exists workforce_candidates_pkey on public.workforce_candidates(id);
create unique index if not exists workforce_benefits_pkey on public.workforce_benefits(id);

alter table public.workforce_leave_types enable row level security;
alter table public.workforce_leave_requests enable row level security;
alter table public.workforce_payroll_periods enable row level security;
alter table public.workforce_payroll_entries enable row level security;
alter table public.workforce_candidates enable row level security;
alter table public.workforce_benefits enable row level security;

do $$ begin
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_leave_types' and policyname='workforce_read') then create policy workforce_read on public.workforce_leave_types for select to authenticated using(tenant_id=get_current_tenant_id() and (has_tenant_permission(tenant_id,'workforce:read') or has_tenant_permission(tenant_id,'workforce:manage'))); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_leave_types' and policyname='workforce_manage') then create policy workforce_manage on public.workforce_leave_types for all to authenticated using(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')) with check(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_leave_requests' and policyname='workforce_read') then create policy workforce_read on public.workforce_leave_requests for select to authenticated using(tenant_id=get_current_tenant_id() and (has_tenant_permission(tenant_id,'workforce:read') or has_tenant_permission(tenant_id,'workforce:manage'))); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_leave_requests' and policyname='workforce_leave') then create policy workforce_leave on public.workforce_leave_requests for all to authenticated using(tenant_id=get_current_tenant_id() and (has_tenant_permission(tenant_id,'workforce:leave') or has_tenant_permission(tenant_id,'workforce:manage'))) with check(tenant_id=get_current_tenant_id() and (has_tenant_permission(tenant_id,'workforce:leave') or has_tenant_permission(tenant_id,'workforce:manage'))); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_leave_requests' and policyname='workforce_manage') then create policy workforce_manage on public.workforce_leave_requests for all to authenticated using(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')) with check(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_payroll_periods' and policyname='workforce_payroll_read') then create policy workforce_payroll_read on public.workforce_payroll_periods for select to authenticated using(tenant_id=get_current_tenant_id() and (has_tenant_permission(tenant_id,'workforce:payroll') or has_tenant_permission(tenant_id,'workforce:manage'))); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_payroll_periods' and policyname='workforce_payroll') then create policy workforce_payroll on public.workforce_payroll_periods for all to authenticated using(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:payroll')) with check(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:payroll')); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_payroll_periods' and policyname='workforce_manage') then create policy workforce_manage on public.workforce_payroll_periods for all to authenticated using(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')) with check(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_payroll_entries' and policyname='workforce_payroll_entries_read') then create policy workforce_payroll_entries_read on public.workforce_payroll_entries for select to authenticated using(tenant_id=get_current_tenant_id() and (has_tenant_permission(tenant_id,'workforce:payroll') or has_tenant_permission(tenant_id,'workforce:manage'))); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_payroll_entries' and policyname='workforce_payroll_entries') then create policy workforce_payroll_entries on public.workforce_payroll_entries for all to authenticated using(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:payroll')) with check(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:payroll')); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_payroll_entries' and policyname='workforce_manage') then create policy workforce_manage on public.workforce_payroll_entries for all to authenticated using(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')) with check(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_candidates' and policyname='workforce_read') then create policy workforce_read on public.workforce_candidates for select to authenticated using(tenant_id=get_current_tenant_id() and (has_tenant_permission(tenant_id,'workforce:read') or has_tenant_permission(tenant_id,'workforce:manage'))); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_candidates' and policyname='workforce_manage') then create policy workforce_manage on public.workforce_candidates for all to authenticated using(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')) with check(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_benefits' and policyname='workforce_read') then create policy workforce_read on public.workforce_benefits for select to authenticated using(tenant_id=get_current_tenant_id() and (has_tenant_permission(tenant_id,'workforce:read') or has_tenant_permission(tenant_id,'workforce:manage'))); end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='workforce_benefits' and policyname='workforce_manage') then create policy workforce_manage on public.workforce_benefits for all to authenticated using(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')) with check(tenant_id=get_current_tenant_id() and has_tenant_permission(tenant_id,'workforce:manage')); end if;
end $$;

create or replace function public.approve_workforce_leave_request(p_tenant_id uuid,p_leave_request_id uuid,p_decision text) returns jsonb language plpgsql security definer set search_path to 'public','pg_catalog' as $$ declare v_request public.workforce_leave_requests%rowtype; v_clinic_user_id uuid; v_timezone text; v_block_id uuid; begin select cu.id into v_clinic_user_id from public.clinic_users cu where cu.auth_user_id=auth.uid() and cu.tenant_id=p_tenant_id and cu.is_active=true and cu.deleted_at is null limit 1; if v_clinic_user_id is null then raise exception 'Unauthorized'; end if; if not public.has_tenant_permission(p_tenant_id,'workforce:leave') and not public.has_tenant_permission(p_tenant_id,'workforce:manage') then raise exception 'Permission denied'; end if; if p_decision not in ('approved','rejected') then raise exception 'Invalid leave decision'; end if; select * into v_request from public.workforce_leave_requests where id=p_leave_request_id and tenant_id=p_tenant_id for update; if not found then raise exception 'Leave request not found'; end if; if v_request.status <> 'pending' then raise exception 'Leave request is already decided'; end if; update public.workforce_leave_requests set status=p_decision,approved_by=case when p_decision='approved' then v_clinic_user_id else null end,approved_at=case when p_decision='approved' then now() else null end,updated_at=now() where id=v_request.id and tenant_id=p_tenant_id; if p_decision='approved' then select coalesce(mt.timezone,'UTC') into v_timezone from public.master_tenants mt where mt.id=p_tenant_id; insert into public.workforce_unavailability_blocks(tenant_id,employee_id,absence_type,starts_at,ends_at,reason,status,created_by) values(p_tenant_id,v_request.employee_id,'leave',((v_request.starts_on::text||' 00:00:00')::timestamp at time zone coalesce(v_timezone,'UTC')),(((v_request.ends_on+1)::text||' 00:00:00')::timestamp at time zone coalesce(v_timezone,'UTC')),v_request.reason,'approved',v_clinic_user_id) returning id into v_block_id; end if; return jsonb_build_object('success',true,'status',p_decision,'unavailability_block_id',v_block_id); end; $$;
create or replace function public.promote_workforce_candidate_to_employee(p_tenant_id uuid,p_candidate_id uuid,p_position_id uuid default null::uuid,p_hire_date date default current_date) returns jsonb language plpgsql security definer set search_path to 'public','pg_catalog' as $$ declare v_candidate public.workforce_candidates%rowtype; v_employee_id uuid; v_clinic_user_id uuid; begin select cu.id into v_clinic_user_id from public.clinic_users cu where cu.auth_user_id=auth.uid() and cu.tenant_id=p_tenant_id and cu.is_active=true and cu.deleted_at is null limit 1; if v_clinic_user_id is null then raise exception 'Unauthorized'; end if; if not public.has_tenant_permission(p_tenant_id,'workforce:recruitment') and not public.has_tenant_permission(p_tenant_id,'workforce:manage') then raise exception 'Permission denied'; end if; select * into v_candidate from public.workforce_candidates where id=p_candidate_id and tenant_id=p_tenant_id for update; if not found then raise exception 'Candidate not found'; end if; if v_candidate.stage='hired' then raise exception 'Candidate already hired'; end if; insert into public.workforce_employees(tenant_id,first_name,last_name,phone,email,position_id,hire_date,status,created_by) values(p_tenant_id,v_candidate.first_name,v_candidate.last_name,v_candidate.phone,v_candidate.email,p_position_id,p_hire_date,'active',v_clinic_user_id) returning id into v_employee_id; update public.workforce_candidates set stage='hired',updated_at=now() where id=v_candidate.id and tenant_id=p_tenant_id; return jsonb_build_object('success',true,'employee_id',v_employee_id); end; $$;
create or replace function public.prevent_agenda_during_workforce_unavailability() returns trigger language plpgsql security definer set search_path to 'public','pg_catalog' as $$ begin if new.doctor_id is not null and new.deleted_at is null and coalesce(new.status,'') not in ('cancelled','canceled') then if exists(select 1 from public.workforce_employees e join public.workforce_unavailability_blocks b on b.employee_id=e.id where e.tenant_id=new.tenant_id and e.user_id=new.doctor_id and b.tenant_id=new.tenant_id and b.status='approved' and b.starts_at < coalesce(new.buffer_end,new.scheduled_end) and b.ends_at > new.scheduled_start) then raise exception 'Doctor is unavailable during the selected time because of an approved workforce absence'; end if; end if; return new; end; $$;
do $$ begin if not exists(select 1 from pg_trigger where tgname='trg_agenda_workforce_unavailability' and tgrelid='public.master_agenda_events'::regclass) then create trigger trg_agenda_workforce_unavailability before insert or update of doctor_id,scheduled_start,scheduled_end,buffer_end,status,deleted_at on public.master_agenda_events for each row execute function public.prevent_agenda_during_workforce_unavailability(); end if; end $$;
do $$ begin if to_regclass('public.workforce_leave_types') is null or to_regclass('public.workforce_leave_requests') is null or to_regclass('public.workforce_payroll_periods') is null or to_regclass('public.workforce_payroll_entries') is null or to_regclass('public.workforce_candidates') is null or to_regclass('public.workforce_benefits') is null then raise exception 'Workforce Operations reconciliation incomplete'; end if; if to_regprocedure('public.approve_workforce_leave_request(uuid,uuid,text)') is null or to_regprocedure('public.promote_workforce_candidate_to_employee(uuid,uuid,uuid,date)') is null then raise exception 'Workforce Operations RPC reconciliation incomplete'; end if; end $$;
