-- Ideal Scenario remediation: Workforce owns all approved availability-blocking absences.
create table if not exists public.workforce_unavailability_blocks(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.master_tenants(id) on delete cascade,employee_id uuid references public.workforce_employees(id) on delete cascade,absence_type text not null check(absence_type in('leave','sick_leave','conference','seminar','official_holiday','permission','departure','other')),starts_at timestamptz not null,ends_at timestamptz not null,reason text,status text not null default 'approved' check(status in('pending','approved','cancelled')),created_by uuid references public.clinic_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at>starts_at));
create index if not exists workforce_unavailability_tenant_employee_idx on public.workforce_unavailability_blocks(tenant_id,employee_id,starts_at,ends_at);
alter table public.workforce_unavailability_blocks enable row level security;
create policy workforce_unavailability_read on public.workforce_unavailability_blocks for select to authenticated using(tenant_id=public.get_current_tenant_id() and(public.has_tenant_permission(tenant_id,'workforce:read') or public.has_tenant_permission(tenant_id,'workforce:manage')));
create policy workforce_unavailability_manage on public.workforce_unavailability_blocks for all to authenticated using(tenant_id=public.get_current_tenant_id() and public.has_tenant_permission(tenant_id,'workforce:manage')) with check(tenant_id=public.get_current_tenant_id() and public.has_tenant_permission(tenant_id,'workforce:manage'));
create or replace function public.get_workforce_unavailability(p_tenant_id uuid,p_employee_id uuid,p_start timestamptz,p_end timestamptz)
returns table(starts_at timestamptz,ends_at timestamptz,absence_type text,reason text) language sql security definer set search_path to 'public' as $$ select u.starts_at,u.ends_at,u.absence_type,u.reason from public.workforce_unavailability_blocks u where u.tenant_id=p_tenant_id and u.status='approved' and(u.employee_id=p_employee_id or u.employee_id is null) and u.starts_at<p_end and u.ends_at>p_start order by u.starts_at $$;
revoke all on function public.get_workforce_unavailability(uuid,uuid,timestamptz,timestamptz) from public;
grant execute on function public.get_workforce_unavailability(uuid,uuid,timestamptz,timestamptz) to authenticated,service_role;
