-- Final payroll aggregation corrections: normalized other earnings and benefit employee contributions.
create or replace function public.create_workforce_payroll_entry_with_commissions(p_tenant_id uuid,p_payroll_period_id uuid,p_employee_id uuid,p_allowances_subunits integer default 0,p_overtime_subunits integer default 0,p_bonuses_subunits integer default 0,p_deductions_subunits integer default 0,p_created_by uuid default null) returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare v_actor uuid; v_period record; v_employment record; v_existing uuid; v_commissions integer:=0; v_structured_deductions integer:=0; v_advance_installments integer:=0; v_net integer; v_entry_id uuid; v_allowances integer:=0; v_overtime integer:=0; v_bonuses integer:=0; v_other integer:=0; v_benefit record;
begin
 if public.get_current_tenant_id() is distinct from p_tenant_id or not public.has_tenant_permission(p_tenant_id,'workforce:payroll') then return jsonb_build_object('success',false,'error','Permission denied'); end if;
 v_actor:=coalesce(p_created_by,auth.uid()); if v_actor is null or not exists(select 1 from public.clinic_users where id=v_actor and tenant_id=p_tenant_id and is_active and deleted_at is null) then return jsonb_build_object('success',false,'error','Actor does not belong to tenant'); end if;
 select * into v_period from public.workforce_payroll_periods where id=p_payroll_period_id and tenant_id=p_tenant_id; if not found then return jsonb_build_object('success',false,'error','Payroll period not found'); end if;
 if v_period.status not in ('open','processing') then return jsonb_build_object('success',false,'error','Payroll period is not open for entries'); end if;
 select id into v_existing from public.workforce_payroll_entries where tenant_id=p_tenant_id and payroll_period_id=p_payroll_period_id and employee_id=p_employee_id limit 1; if v_existing is not null then return jsonb_build_object('success',false,'error','Payroll entry already exists for this employee and period','entry_id',v_existing); end if;
 select * into v_employment from public.workforce_employment_records where tenant_id=p_tenant_id and employee_id=p_employee_id and status='active' and effective_from <= v_period.period_end and (effective_to is null or effective_to >= v_period.period_start) order by effective_from desc limit 1; if not found then return jsonb_build_object('success',false,'error','No active employment record covers this payroll period'); end if;
 select coalesce(sum(case when lower(r.basis) in ('percentage','percent','collected_revenue') then round(c.eligible_amount_subunits*(r.rate/100.0)) when lower(r.basis) in ('fixed','fixed_amount') then coalesce(r.fixed_amount_subunits,0) else 0 end),0)::integer into v_commissions from public.workforce_commission_entries c join public.workforce_commission_rules r on r.id=c.commission_rule_id and r.tenant_id=c.tenant_id where c.tenant_id=p_tenant_id and c.employee_id=p_employee_id and c.status='approved' and c.calculated_at >= (v_period.period_start::timestamp at time zone 'UTC') and c.calculated_at < ((v_period.period_end+1)::timestamp at time zone 'UTC');
 select coalesce(sum(case when earning_type='allowance' then amount_subunits else 0 end),0),coalesce(sum(case when earning_type='overtime' then amount_subunits else 0 end),0),coalesce(sum(case when earning_type='bonus' then amount_subunits else 0 end),0),coalesce(sum(case when earning_type='other_earning' then amount_subunits else 0 end),0) into v_allowances,v_overtime,v_bonuses,v_other from public.workforce_payroll_earnings where tenant_id=p_tenant_id and employee_id=p_employee_id and payroll_period_id=p_payroll_period_id and status='approved';
 v_allowances:=v_allowances+greatest(coalesce(p_allowances_subunits,0),0); v_overtime:=v_overtime+greatest(coalesce(p_overtime_subunits,0),0); v_bonuses:=v_bonuses+greatest(coalesce(p_bonuses_subunits,0),0);
 for v_benefit in select id,employee_contribution_subunits,currency,benefit_name from public.workforce_benefits where tenant_id=p_tenant_id and employee_id=p_employee_id and status='active' and employee_contribution_subunits>0 and starts_on<=v_period.period_end and (ends_on is null or ends_on>=v_period.period_start) loop
   if not exists(select 1 from public.workforce_payroll_deductions d where d.tenant_id=p_tenant_id and d.payroll_period_id=p_payroll_period_id and d.employee_id=p_employee_id and d.source_type='benefit' and d.source_id=v_benefit.id and d.status='approved') then
     insert into public.workforce_payroll_deductions(tenant_id,employee_id,payroll_period_id,deduction_type,amount_subunits,currency,source_type,source_id,reason,status,created_by,approved_by,approved_at) values(p_tenant_id,p_employee_id,p_payroll_period_id,'benefit_contribution',v_benefit.employee_contribution_subunits,v_benefit.currency,'benefit',v_benefit.id,'Employee contribution: '||v_benefit.benefit_name,'approved',v_actor,v_actor,now());
   end if;
 end loop;
 select coalesce(sum(d.amount_subunits),0)::integer into v_structured_deductions from public.workforce_payroll_deductions d where d.tenant_id=p_tenant_id and d.employee_id=p_employee_id and d.payroll_period_id=p_payroll_period_id and d.status='approved';
 select coalesce(sum(i.amount_subunits),0)::integer into v_advance_installments from public.workforce_advance_installments i join public.workforce_employee_advances a on a.id=i.advance_id and a.tenant_id=i.tenant_id where i.tenant_id=p_tenant_id and a.employee_id=p_employee_id and i.status='due' and i.due_date between v_period.period_start and v_period.period_end;
 v_structured_deductions:=coalesce(v_structured_deductions,0)+coalesce(v_advance_installments,0);
 v_net:=v_employment.base_salary_subunits+v_allowances+v_overtime+v_bonuses+v_other+v_commissions-greatest(v_structured_deductions+greatest(coalesce(p_deductions_subunits,0),0),0);
 insert into public.workforce_payroll_entries(tenant_id,payroll_period_id,employee_id,base_salary_subunits,allowances_subunits,overtime_subunits,bonuses_subunits,commissions_subunits,deductions_subunits,net_subunits,status,notes,created_by) values(p_tenant_id,p_payroll_period_id,p_employee_id,v_employment.base_salary_subunits,v_allowances,v_overtime,v_bonuses+v_other,v_commissions,greatest(v_structured_deductions+greatest(coalesce(p_deductions_subunits,0),0),0),v_net,'draft','Generated from employment, approved earnings, approved commissions, benefit contributions, deductions, and due advance installments',v_actor) returning id into v_entry_id;
 update public.workforce_advance_installments set status='allocated',payroll_entry_id=v_entry_id where tenant_id=p_tenant_id and status='due' and due_date between v_period.period_start and v_period.period_end and advance_id in (select id from public.workforce_employee_advances where tenant_id=p_tenant_id and employee_id=p_employee_id);
 return jsonb_build_object('success',true,'entry_id',v_entry_id,'base_salary_subunits',v_employment.base_salary_subunits,'allowances_subunits',v_allowances,'overtime_subunits',v_overtime,'bonuses_subunits',v_bonuses,'other_earnings_subunits',v_other,'commissions_subunits',v_commissions,'structured_deductions_subunits',v_structured_deductions,'net_subunits',v_net);
exception when others then return jsonb_build_object('success',false,'error',sqlerrm); end; $$;
